justeattakeaway/pie

.github/workflows/build.yml, CHANGELOG.md, apps/pie-microsite/.eleventy.js, apps/pie-microsite/package.json, apps/pie-microsite/src/_includes/head-common.njk, apps/pie-microsite/src/_includes/header.njk, apps/pie-microsite/src/_includes/nav.njk, package.json, turbo.json, yarn.lock
=> add github pages deployment

apps/pie-microsite/CHANGELOG.md, apps/pie-microsite/package.json, apps/pie-microsite/src/assets/styles/components/_navToggle.scss, apps/pie-microsite/src/assets/styles/components/_tabs.scss
- Styling for tabs alignment.
- zindex issue on background.
- Linting error.
=> v1.15.0 - Design fixes

.github/workflows/build.yml, CHANGELOG.md, apps/pie-microsite/src/assets/styles/base/_layout.scss, package.json, yarn.lock
v1.13.0
*September 23, 2022*
- Linting step to GitHub workflow
- Split out GitHub actions workflow into separate jobs
=> pie@v1.13.0 - SCSS linting GH action

.github/workflows/CODEOWNERS, CHANGELOG.md
Latest – to be added to the next release
- `CODEOWNERS` file with the `@justeat/ui-senior-reviewers` set as reviewers for `pie-microsite`
=> pie - add codeowners file

apps/pie-microsite/CHANGELOG.md, apps/pie-microsite/package.json, apps/pie-microsite/src/_data/projectSettings.js, apps/pie-microsite/src/_includes/gtm.njk, apps/pie-microsite/src/_includes/head-common.njk
v1.23.0
*November 29, 2022*
- GTM script for production builds
=> pie-microsite@v1.23.0 - add GTM to production builds

.github/workflows/build.yml, CHANGELOG.md, package.json
v1.21.0
*December 8, 2022*
- Automatic PR reminder to check visual changes in Percy
- Ensure visual tests don't run on draft PRs.
=> pie@1.21.0 - Add Percy reminder + prevent execution on drafts

apps/pie-microsite/CHANGELOG.md, apps/pie-microsite/package.json, apps/pie-microsite/src/_includes/head-common.njk
v1.27.0
*December 19, 2022*
- Commented out GTM script until we have a privacy policy and cookie banner in place
=> pie-microsite@v1.27.0 - Remove analytics script

.github/workflows/build.yml, CHANGELOG.md, package.json
v1.21.1
*December 20, 2022*
- CI failure on `main` due to execution of visual review PR comment step.
=> pie@1.21.1 - Fix issue with CI on main

apps/pie-microsite/CHANGELOG.md, apps/pie-microsite/package.json, apps/pie-microsite/src/_11ty/shortcodes/tokensTable/index.js, apps/pie-microsite/src/_11ty/shortcodes/tokensTable/tokenTypes/colour.js, apps/pie-microsite/src/_11ty/shortcodes/tokensTable/tokenTypes/font.js, apps/pie-microsite/src/_11ty/shortcodes/tokensTable/tokenTypes/radius.js, apps/pie-microsite/src/_11ty/shortcodes/tokensTable/tokenTypes/spacing.js
- token specific logic out of `tokensTable/index.js` to separate files
=> pie-microsite@v1.40.0 - move token specific logic to separate files

apps/pie-microsite/CHANGELOG.md, apps/pie-microsite/package.json, apps/pie-microsite/src/assets/styles/components/_contentPage.scss, apps/pie-microsite/src/assets/styles/components/_notification.scss, apps/pie-microsite/src/assets/styles/plugins/_prism.scss, apps/pie-microsite/src/content/pages/foundations/typography/code.md
This PR is a follow-up to my previous work on typography and design token pages to address the designer's notes.
- Align the notification icon to the top
- Bottom margin of prism code snippets to be 24px
- Lists to have a 32px bottom margin if it's followed by a heading
- h2 to have a top margin of 56px if followed by a paragraph
- Headings hierarchy of typography code snippets page
=> pie-microsite@v1.45.1 - Address design reviews for design tokens/typography pages

.changeset/chatty-geese-cheer.md, apps/pie-microsite/src/content/pages/foundations/elevation/android.md
... based on feedback from design review.
=> Update text formatting on android elevation page

.changeset/great-pumas-marry.md, apps/pie-microsite/src/content/pages/support/faq.md
=> [Content page] - FAQs

.changeset/shy-donuts-act.md, apps/pie-microsite/src/content/pages/all-about-pie/what-is-pie.md
- adds [Content page] What is PIE?
=> [Content page] What is PIE?

.changeset/khaki-rockets-explode.md, apps/pie-microsite/src/content/pages/all-about-pie/roadmap.md, apps/pie-microsite/test/snapshots/expected-routes.snapshot.json
=> Adds roadmap page

.changeset/purple-kids-wash.md, apps/pie-microsite/src/content/pages/support/contact-us.md, apps/pie-microsite/test/snapshots/expected-routes.snapshot.json
- adds [Content page] - Contact us
=> [Content page] - Contact us

.changeset/red-windows-fail.md, apps/pie-microsite/src/content/pages/all-about-pie/our-vision.md, apps/pie-microsite/test/snapshots/expected-routes.snapshot.json
=> our vision page

apps/pie-microsite/src/_includes/head.njk
Explicitly inform web crawlers they can index and crawl the microsite
=> pie-microsite: add index and follow rules for spiders

.github/workflows/build.yml
Reverts justeattakeaway/pie#187
=> Revert "Attempt to fix deploy"

.changeset/happy-sheep-help.md, apps/pie-storybook/stories/pie-button.stories.ts, packages/components/pie-button/src/button.scss, packages/components/pie-button/src/index.ts
[Added] - state styling to button (focus/hover/active/disabled)
=> feat(pie-button): add button state styles

.changeset/nervous-planets-sip.md, .changeset/tough-guests-yawn.md, apps/pie-docs/src/all-about-pie/our-vision-principles.json, apps/pie-docs/src/all-about-pie/what-is-pie.md
[Changed] - Copy in What is PIE? and Our Vision pages based on ux feedback
[Changed] - Add question mark to What is PIE? nav key
=> docs(pie-docs): copy updates to what is pie and our vision

.changeset/gorgeous-buses-tickle.md, apps/pie-docs/src/designers/getting-started/overview.md
[Changed] - Designers getting started page copy based on ux feedback
=> Getting started copy

yarn.lock
=> fix(pie-monorepo): fix yarn.lock conflict

.changeset/chatty-shrimps-look.md, renovate.json
=> chore(pie-monorepo): update renovate commit message prefix

.changeset/dirty-oranges-whisper.md, .changeset/popular-buttons-suffer.md, apps/examples/wc-react18/src/styles.css, apps/examples/wc-vue3/README.md, apps/examples/wc-vue3/package.json, apps/examples/wc-vue3/src/App.vue, apps/examples/wc-vue3/src/styles.css, apps/examples/wc-vue3/tsconfig.json, apps/examples/wc-vue3/vite.config.ts, yarn.lock
- Add pie-button web component to Vue 3 example app
- Fix stylelint issues in React example app
=> feat(wc-vue3): add button component to vue example app

.changeset/cuddly-baboons-work.md, .changeset/sweet-wombats-work.md, apps/pie-docs/src/all-about-pie/roadmap.md, apps/pie-docs/src/all-about-pie/what-is-pie.md, apps/pie-docs/src/assets/styles/components/_list.scss, apps/pie-docs/src/designers/getting-started/overview.md, apps/pie-docs/src/engineers/getting-started/overview.md
[Changed] - Amend copy on various pages based on design feedback
[Changed] - Use 24px spacing between icon list items
=> docs(pie-docs): make copy amendments

.changeset/few-ducks-talk.md, apps/pie-docs/src/designers/contributing/design-checklist.json, apps/pie-docs/src/designers/getting-started/best-practices.md, apps/pie-docs/src/designers/getting-started/figma-files.md, apps/pie-docs/src/designers/getting-started/getting-started.json, apps/pie-docs/src/designers/getting-started/overview.md, apps/pie-docs/src/foundations/design-tokens/updates-and-maintenance.md
=> docs(pie-docs): Copy changes for designers pages

.changeset/ninety-peas-pay.md, .github/workflows/build.yml
**[Changed]** - Updated Concurrency > cancel-in-progress: true to stop any builds in progress when new changes are pushed to a branch
=> ci(pie-monorepo): updated concurrency - cancel-in-progress: true

.changeset/long-spiders-work.md, .changeset/twenty-wolves-trade.md, apps/examples/wc-next13/pages/index.tsx, apps/examples/wc-nuxt3/app.vue, apps/examples/wc-react18/src/App.js, apps/examples/wc-vue3/src/App.vue, apps/pie-storybook/stories/pie-button.stories.ts, packages/components/pie-button/src/index.ts
[Added] - Slot functionality to pie-button component and associated SB and example app integrations
=> feat(pie-button): add slot to pie button

.changeset/real-flowers-try.md, packages/components/pie-button/package.json
- [Fixed] - Added module entry for component
=> fix(pie-button): added module entry in package.json

.changeset/orange-scissors-change.md, apps/examples/wc-nuxt3/app.vue, apps/examples/wc-nuxt3/nuxt.config.ts, apps/examples/wc-nuxt3/package.json, yarn.lock
=> chore(wc-nuxt3): removed pie button from nuxt3 example app to fix build

.changeset/polite-cooks-double.md
Fixes a bug with existing changeset file.
=> fix(pie-monorepo): fix changeset file

.changeset/neat-eggs-hang.md, packages/components/pie-button/src/index.ts
[Added] Declare global statement back in.
=> fix(pie-button): add in declare statement to ts file

.changeset/famous-bugs-confess.md, apps/examples/wc-nuxt3/app.vue, apps/examples/wc-nuxt3/nuxt.config.ts, apps/examples/wc-nuxt3/package.json, yarn.lock
[Added] Pie button and markup to nuxt3 example folder.
=> feat(pie-monorepo): adds Nuxt3 button

.changeset/dirty-ants-destroy.md, .github/workflows/amplify-deploy.yml, .github/workflows/ci.yml
=> ci(pie-monorepo): updated amplify deploy to support bucket name

.changeset/short-buttons-divide.md, .github/workflows/ci.yml
[Fixed] - Bucket name being passed to CI workflow
=> fix(pie-monorepo): fix bucket name for main

.changeset/wicked-moons-sneeze.md, apps/pie-storybook/.storybook/preview.js, apps/pie-storybook/package.json, apps/pie-storybook/stories/pie-button.stories.ts, apps/pie-storybook/stories/withGlobalDirection.ts, apps/pie-storybook/stories/withStorybookDirection.ts, yarn.lock
Gives us a toolbar button that toggles between right to left and left to right writing directions in a story. 
[Changed] - Upgrade to Storybook 7 and add a writing direction toolbar dropdown
=> feat(pie-button): create an rtl toolbar button in storybook

.changeset/famous-trains-shave.md, apps/examples/wc-nuxt3/package.json
Missed as part of my previous PR 🤦🏼‍♂️
=> chore(pie-monorepo): add version property to nuxt3 app

.changeset/eight-plants-relate.md, .changeset/lovely-rats-crash.md, apps/pie-docs/src/_11ty/shortcodes/index.js, apps/pie-docs/src/_11ty/shortcodes/notifications/globalTokensWarning.js, apps/pie-docs/src/assets/styles/components/_notification.scss, apps/pie-docs/src/foundations/colour/tokens/global.md, apps/pie-docs/src/foundations/elevation/tokens/global.md, apps/pie-docs/src/foundations/radius/tokens/global.md, apps/pie-docs/src/foundations/spacing/tokens/alias.md, apps/pie-docs/src/foundations/spacing/tokens/global.md, apps/pie-docs/src/foundations/typography/tokens/global.md
[Added] - a reusable warning about global token usage to all global tokens pages
[Added] - a reusable warning about global token usage to all global tokens pages
=> feat(pie-docs): add global token usage warning to all global pages

.changeset/sixty-bottles-brake.md, apps/pie-docs/src/accessibility/accessibility-resources.md, apps/pie-docs/test/snapshots/expected-routes.snapshot.json
[Added] - Accessibility resources page
=> feat(pie-docs): Add accessibility resources page 

apps/pie-storybook/package.json, yarn.lock
Reverts justeattakeaway/pie#463
=> Revert "chore(pie-storybook): Update storybook to v7.0.12"

.changeset/happy-islands-jog.md, apps/pie-docs/test/helpers/configuration-helper.js
[Fixed] - Issue where cookie banner wasn't disappearing in Playwright due to new www.pie.design > pie.design redirect
=> fix(pie-docs): fixed Playwright baseUrl

.changeset/five-eels-melt.md, .github/pie-docs-rewrites.txt
[Added] - text file to document PIE documentation site redirect rules
=> docs(pie-monorepo): add rewrite rules text file for PIE documentation site

.changeset/hungry-shirts-lick.md, apps/pie-docs/src/accessibility/testing-for-accessibility.md, apps/pie-docs/src/all-about-pie/what-is-pie.md, apps/pie-docs/src/designers/how-we-support-you.md
[Updated] - markdown lists to use correct icons
=> feat(pie-docs): use correct icons for lists

.changeset/warm-walls-do.md, packages/tools/pie-wrapper-react/README.md
[Added] - further documentation on `custom-elements.json`
=> docs(pie-wrapper-react): updated docs on custom-element.json

.changeset/odd-timers-destroy.md, configs/pie-components-config/vite.config.js, packages/components/pie-button/package.json, packages/components/pie-button/vite.config.js, packages/components/pie-icon-button/package.json, packages/components/pie-icon-button/vite.config.js, packages/components/pie-modal/package.json, packages/components/pie-modal/vite.config.js
[Changed] - Made Vite config extendable
=> feat(pie-components-config): made shared vite config extendable

.changeset/fast-wombats-fry.md, packages/components/pie-modal/src/modal.scss
[Fixed] - PieModal CSS by adding logical property
=> fix(pie-modal): add missing css logical property

.changeset/wise-hotels-accept.md, packages/components/pie-button/README.md, packages/components/pie-icon-button/README.md, packages/components/pie-modal/README.md
[Added] Read me percy config examples
=> docs(pie-docs): add readme details about percy visual tests

.changeset/young-geese-arrive.md, packages/tools/pie-stylelint-config/rules/base.js
- [Added] - Rule for custom property naming convention
=> chore(stylelint-config-pie): added rule for custom prop naming convention

.github/workflows/changeset-release.yml
Reverting changes that stopped version packages PR's from being generated.
=> revert(pie-monorepo): revert git username setup

.changeset/rotten-pens-prove.md, apps/pie-storybook/stories/pie-icon-button.stories.ts, packages/components/pie-icon-button/README.md, packages/components/pie-icon-button/src/defs.ts, packages/components/pie-icon-button/src/iconButton.scss, packages/components/pie-icon-button/src/index.ts, packages/components/pie-icon-button/test/visual/pie-icon-button.spec.ts, packages/tools/pie-wrapper-react/custom-elements.json
- [Added] - `size` prop added to pie-icon-button
=> feat(pie-icon-button): size prop added to component and storybook

.github/workflows/changeset-release.yml
=> fix(pie-monorepo): makes pie-bot creds persistent for changesets

packages/components/pie-button/README.md, packages/components/pie-icon-button/README.md, packages/components/pie-modal/README.md
- Updated the component READMEs so they are all consistent (and amended a couple of errors I spotted)
=> docs(pie-monorepo): making component readmes consistent

.changeset/dry-cars-call.md, packages/components/pie-button/src/defs.ts, packages/components/pie-icon-button/src/defs.ts, packages/components/pie-modal/src/defs.ts
- [Changed] - Updated defs to use different array type syntax
=> format(pie-icon-button): updated defs to use different array type syntax

.changeset/mean-cooks-nail.md, packages/tools/pie-wrapper-react/custom-elements.json, packages/tools/pie-wrapper-react/scripts/add-react-wrapper.js
[Added] Order by length to custom-elements.json to prevent reordering (stops us having to commit unneeded changes in this file)
=> feat(pie-wrapper-react): fixed order of custom-elements.json

packages/components/pie-button/src/defs.ts, packages/components/pie-icon-button/src/defs.ts, packages/components/pie-modal/src/defs.ts, packages/tools/pie-wrapper-react/custom-elements.json
Add descriptive jsdoc comments to component props
=> docs(pie-monorepo): add descriptive jsdoc comments to WC props

.changeset/friendly-islands-reply.md, .changeset/tricky-cobras-hang.md, packages/tools/pie-icons/bin/process-svg.js
- Fix invalid changeset entry
- Use `path.sep` when processing icon filepaths
=> format(pie-monorepo): [Fixed] - Changeset error and icon build inconsistencies

.changeset/nervous-jeans-tie.md, .changeset/tender-lobsters-rest.md, packages/components/pie-button/src/index.ts, packages/components/pie-icon-button/src/index.ts, packages/components/pie-modal/src/index.ts
---
"@justeattakeaway/pie-icon-button": minor
---
[Changed] - Set all component props to public
=> refactor(pie-monorepo): set component props to public

.changeset/tender-kiwis-help.md, apps/pie-storybook/.storybook/preview.js, apps/pie-storybook/stories/pie-button.stories.ts, packages/components/pie-button/README.md, packages/components/pie-button/src/button.scss, packages/components/pie-button/src/defs.ts, packages/components/pie-button/test/visual/pie-button.spec.ts, packages/components/pie-webc-testing/src/helpers/components/web-component-test-wrapper/WebComponentTestWrapper.ts, packages/components/pie-webc-testing/src/helpers/components/web-component-test-wrapper/webComponentTestWrapper.scss, packages/tools/pie-wrapper-react/custom-elements.json
---
---
[Added] - inverse and ghost-inverse variants to pie-button
=> feat(pie-button): inverse and ghost-inverse style variants

.changeset/friendly-ads-cover.md, .eslintrc.js, apps/pie-storybook/stories/pie-button.stories.ts, packages/components/pie-button/README.md, packages/components/pie-button/src/button.scss, packages/components/pie-button/src/defs.ts, packages/components/pie-button/src/index.ts, packages/components/pie-button/test/visual/pie-button.spec.ts, packages/tools/pie-wrapper-react/custom-elements.json
=> feat(pie-button): add loading state

.changeset/forty-teachers-decide.md, .github/workflows/example-apps-ci.yml
---
"pie-monorepo": patch
---
[Removed] - Duplicate `needs` property .github/workflows/example-apps-ci.yml
=> fix(pie-monorepo): fix example app deploy

.changeset/shaggy-games-tan.md, apps/pie-storybook/stories/pie-button.stories.ts, apps/pie-storybook/stories/pie-icon-button.stories.ts, apps/pie-storybook/stories/pie-modal.stories.ts, apps/pie-storybook/types/SlottedComponentProps.ts, apps/pie-storybook/types/StoryMeta.ts, apps/pie-storybook/types/index.ts
---
---
[Added] - Typed stories
=> Storybook types

.changeset/rare-needles-yawn.md, apps/pie-storybook/stories/pie-modal.stories.ts, packages/components/pie-modal/README.md, packages/components/pie-modal/src/defs.ts, packages/components/pie-modal/src/index.ts, packages/components/pie-modal/src/modal.scss, packages/components/pie-modal/test/visual/pie-modal.spec.ts, packages/tools/pie-wrapper-react/custom-elements.json
---
"@justeattakeaway/pie-modal": minor
---
[Added] - loading spinner to modal
=> feat(pie-modal): add loading spinner to modal

.changeset/flat-books-hunt.md, apps/pie-storybook/package.json, yarn.lock
---
---
[Changed] - Upgrade Storybook to 7.1.0
=> feat(pie-storybook): DSW-000 upgrade storybook to 7.1.0

.changeset/warm-mails-report.md, packages/components/pie-button/.eslintignore, packages/components/pie-button/package.json, packages/components/pie-button/playwright-lit-visual.config.ts, packages/components/pie-button/playwright-lit.config.ts, packages/components/pie-button/playwright/index.ts, packages/components/pie-button/test/component/pie-button.spec.ts, packages/components/pie-button/tsconfig.json, packages/components/pie-icon-button/.eslintignore, packages/components/pie-icon-button/package.json, packages/components/pie-icon-button/playwright-lit-visual.config.ts, packages/components/pie-icon-button/playwright-lit.config.ts, packages/components/pie-icon-button/playwright/index.ts, packages/components/pie-icon-button/src/iconButton.scss, packages/components/pie-icon-button/tsconfig.json, packages/components/pie-modal/.eslintignore, packages/components/pie-modal/package.json, packages/components/pie-modal/playwright-lit-visual.config.ts, packages/components/pie-modal/playwright-lit.config.ts, packages/components/pie-modal/playwright/index.ts, packages/components/pie-modal/tsconfig.json, packages/components/pie-webc-core/.eslintignore, packages/components/pie-webc-core/package.json, packages/components/pie-webc-core/src/mixins/rtl/rtlMixin.ts, packages/components/pie-webc-core/tsconfig.json, packages/components/pie-webc-testing/.eslintignore, packages/components/pie-webc-testing/package.json, packages/components/pie-webc-testing/tsconfig.json, packages/tools/pie-wrapper-react/custom-elements.json, yarn.lock
---
"@justeattakeaway/pie-webc-testing": minor
"@justeattakeaway/pie-icon-button": minor
"@justeattakeaway/pie-webc-core": minor
"@justeattakeaway/pie-wrapper-react": minor
"@justeattakeaway/pie-modal": minor
---
[Changed] - Add js/ts linting and fix errors
=> chore(pie-monorepo): DSW-1022 add js linting to components

.changeset/mighty-badgers-buy.md, apps/pie-docs/src/assets/styles/components/_simpleTable.scss, apps/pie-docs/src/foundations/elevation/tokens/global.md, apps/pie-docs/src/foundations/radius/tokens/global.md, apps/pie-docs/src/foundations/typography/tokens/global.md, apps/pie-docs/src/tokensMetadata.json
---
"pie-docs": minor
---
[Updated] - elevation and radius global token pages to use `simpleTable` over `tokensTable`
=> feat(pie-docs): DSW-870 update radius and elevation global token pages

.changeset/early-crews-decide.md, .changeset/quiet-ways-rest.md, apps/pie-storybook/stories/toggle-switch.stories.ts, packages/components/pie-toggle-switch/.eslintignore, packages/components/pie-toggle-switch/LICENSE, packages/components/pie-toggle-switch/README.md, packages/components/pie-toggle-switch/declaration.d.ts, packages/components/pie-toggle-switch/package.json, packages/components/pie-toggle-switch/playwright-lit-visual.config.ts, packages/components/pie-toggle-switch/playwright-lit.config.ts, packages/components/pie-toggle-switch/src/defs.ts, packages/components/pie-toggle-switch/src/index.ts, packages/components/pie-toggle-switch/src/toggle-switch.scss, packages/components/pie-toggle-switch/tsconfig.json, packages/components/pie-toggle-switch/vite.config.js, packages/components/pie-webc-testing/src/helpers/get-all-prop-combos.ts, packages/tools/generator-pie-component/README.md, packages/tools/generator-pie-component/src/app/templates/src/component.scss, packages/tools/generator-pie-component/src/app/templates/src/defs.ts, packages/tools/pie-wrapper-react/custom-elements.json, yarn.lock
"@justeattakeaway/pie-toggle-switch": minor
"@justeattakeaway/pie-wrapper-react": minor
---
[Added] - Created package skeleton for pie-toggle-switch component
NOTE: I've removed the test commands as they fail due to no tests existing yet. Will add them back in on the next PR and there is a ticket to set up generated tests to prevent this in future 👍
=> feat(pie-toggle-switch): DSW-990 add empty package skeleton

.changeset/shy-radios-reflect.md, .husky/commit-msg, .husky/pre-push
- Added `pre-push` eslint command
=> feat(pie-monorepo): DSW-920 added pre-push eslint command

.changeset/famous-melons-confess.md, .github/workflows/ci.yml
=> ci(pie-monorepo): DSW-000 only run visual tests on non-draft PRs

.changeset/tiny-carrots-float.md, packages/components/pie-modal/src/index.ts, yarn.lock
[Fixed] - Re-add property decorator for modal position prop
=> fix(pie-modal): DSW-1048 fix modal position prop

.changeset/hip-keys-nail.md
This mr brings icon packages back in sync
=> release(pie-icons): DSW-000 brings icon packages back in sync

.changeset/ninety-shoes-brush.md, apps/pie-storybook/.storybook/preview-body.html, apps/pie-storybook/.storybook/preview.js, apps/pie-storybook/package.json, yarn.lock
[Added] - pie-css added to storybook
=> feat(pie-storybook): DSW-1040 pie-css added to storybook

apps/examples/wc-vanilla/index.html, apps/examples/wc-vanilla/main.js, apps/examples/wc-vanilla/package.json, apps/examples/wc-vanilla/style.css, yarn.lock
[Added] - pie-css added to vanilla app
=> feat(pie-monorepo): DSW-1040 add pie-css to wc-vanilla app

apps/examples/wc-next13/package.json, apps/examples/wc-next13/pages/index.tsx, yarn.lock
Adds `pie-css` to the next-13 example app
=> feat(pie-toggle-switch): DSW-1040 add pie-css to next13 example app

.changeset/long-numbers-dress.md, packages/tools/generator-pie-component/README.md
[Added] - how to set up VRT to the readme
this section should be removed when the steps are to the pie.docs with more details on how to get started.
=> refactor(pie-generator-component): DSW-000 add how to set VRT to the component generator

apps/examples/wc-angular12/angular.json, apps/examples/wc-angular12/package.json, apps/examples/wc-angular12/src/index.html, apps/examples/wc-angular12/src/styles.scss, yarn.lock
Adds `pie-css` to the Angular example app
=> feat(pie-monorepo): DSW-1040 integrate pie-css with angular app

apps/examples/wc-next10/package.json, apps/examples/wc-next10/pages/_app.jsx, apps/examples/wc-next10/pages/_document.jsx, yarn.lock
add `pie-css` to next 10 example app
=> feat(pie-monorepo): DSW-1040 integrate pie-css with next 10 example app

apps/examples/wc-react18/package.json, apps/examples/wc-react18/public/index.html, apps/examples/wc-react18/src/App.js, yarn.lock
add `pie-css` to react-18 example app
=> feat(pie-monorepo): DSW-1040 integrate pie-css with react-18 app

apps/examples/wc-nuxt2/nuxt.config.js, apps/examples/wc-nuxt2/package.json, apps/examples/wc-nuxt3/nuxt.config.ts, apps/examples/wc-nuxt3/package.json, yarn.lock
integrate pie-css with nuxt2 and nuxt3 apps
=> feat(pie-monorepo): DSW-1040 integrate pie-css with nuxt2 and nuxt3 apps

apps/examples/wc-react17/.eslintrc.js, apps/examples/wc-react17/package.json, apps/examples/wc-react17/public/index.html, apps/examples/wc-react17/src/App.css, apps/examples/wc-react17/src/App.js, apps/examples/wc-react17/src/styles.css, apps/examples/wc-vue3/package.json, apps/examples/wc-vue3/src/main.ts, yarn.lock
integrate pie-css  with react 17 and vue 3
=> feat(pie-monorepo): DSW-1040 integrate pie-css  with react 17 and vue 3

apps/pie-storybook/.storybook/preview-body.html, apps/pie-storybook/stories/pie-link.stories.ts, packages/components/pie-link/README.md, packages/components/pie-link/src/defs.ts, packages/components/pie-link/src/index.ts, packages/components/pie-link/src/link.scss, packages/components/pie-link/test/component/pie-link.spec.ts, packages/components/pie-link/test/visual/pie-link.spec.ts, packages/tools/pie-wrapper-react/custom-elements.json
=> feat(pie-link): DSW-1056 create basic functionality of pie link

.changeset/mean-zebras-sell.md, apps/pie-storybook/stories/pie-toggle-switch.stories.ts, packages/components/pie-toggle-switch/src/defs.ts, packages/components/pie-toggle-switch/src/index.ts, packages/components/pie-toggle-switch/src/toggle-switch.scss, packages/components/pie-toggle-switch/test/component/pie-toggle-switch.spec.ts, packages/components/pie-toggle-switch/test/visual/pie-toggle-switch.spec.ts, packages/tools/pie-wrapper-react/custom-elements.json
[Added] - Label and labelplacement to the toggle switch 
Some of the work of this PR is carried out from here https://github.com/justeattakeaway/pie/pull/705
=> feat(pie-toggle-switch): DSW-998 add label

.changeset/olive-humans-allow.md, apps/pie-storybook/stories/pie-cookie-banner.stories.ts, packages/components/pie-cookie-banner/.eslintignore, packages/components/pie-cookie-banner/LICENSE, packages/components/pie-cookie-banner/README.md, packages/components/pie-cookie-banner/declaration.d.ts, packages/components/pie-cookie-banner/package.json, packages/components/pie-cookie-banner/playwright-lit-visual.config.ts, packages/components/pie-cookie-banner/playwright-lit.config.ts, packages/components/pie-cookie-banner/playwright/index.html, packages/components/pie-cookie-banner/playwright/index.ts, packages/components/pie-cookie-banner/src/cookie-banner.scss, packages/components/pie-cookie-banner/src/defs.ts, packages/components/pie-cookie-banner/src/index.ts, packages/components/pie-cookie-banner/test/accessibility/pie-cookie-banner.spec.ts, packages/components/pie-cookie-banner/test/component/pie-cookie-banner.spec.ts, packages/components/pie-cookie-banner/test/visual/pie-cookie-banner.spec.ts, packages/components/pie-cookie-banner/tsconfig.json, packages/components/pie-cookie-banner/vite.config.js, packages/tools/generator-pie-component/README.md, yarn.lock
---
"@justeattakeaway/pie-cookie-banner": minor
---
[Added] - New pie-cookie-banner component (just generated files)
=> feat(pie-cookie-banner): DSW-1126 generate cookie-banner component

.changeset/yellow-radios-glow.md, packages/components/pie-toggle-switch/src/index.ts, packages/components/pie-toggle-switch/test/component/pie-toggle-switch.spec.ts, yarn.lock
[Added] label toggling support.
=> feat(pie-toggle-switch): DSW-1081 adds support for toggling switch via label

.changeset/tidy-files-boil.md, apps/pie-storybook/stories/pie-button.stories.ts, packages/components/pie-button/README.md, packages/components/pie-button/src/button.scss, packages/components/pie-button/src/defs.ts, packages/components/pie-button/test/component/pie-button.spec.ts, packages/components/pie-button/test/visual/pie-button.spec.ts
- [Added] - outline-inverse variant for pie-button
=> feat(pie-button): DSW-1139 outline inverse button

yarn.lock
- yarn.lock seems to be out of sync, resulting in unresolved package imports in CI.
=> fix(pie-monorepo): DSW-000 update yarn lock

.changeset/moody-pots-rush.md, packages/components/pie-cookie-banner/src/index.ts, packages/components/pie-cookie-banner/test/component/pie-cookie-banner.spec.ts
---
"@justeattakeaway/pie-cookie-banner": minor
---
[Changed] - Use button tag for manage preferences link and update test naming to start with 'should'
=> feat(pie-cookie-banner): DSW-1127 use button for manage preferences link

.changeset/small-fishes-compete.md, .github/workflows/ci.yml
So to avoid running pie-doc visual tests in this job
=> ci(pie-monorepo): DSW-1175 update browser visual tests filter

.changeset/happy-cooks-join.md, apps/pie-storybook/.storybook/main.ts, apps/pie-storybook/package.json, yarn.lock
... and add missing peer dependencies
[Changed] - update storybook to v7.4.0
[Added] - missing peer dependencies
=> docs(pie-storybook): DSW-000 update storybook to v7.4.0

.changeset/early-teachers-tickle.md, .changeset/modern-ducks-call.md, apps/pie-storybook/.storybook/preview.js, apps/pie-storybook/.storybook/viewports.js, apps/pie-storybook/stories/pie-button.stories.ts, packages/components/pie-button/src/button.scss
[Fixed] - transparency mode added to hsl mixin for ghost and outline buttons
[Added] - added some more custom bgs and device viewports
=> fix(pie-button): DSW-1181 transparency mode added to hsl mixin for ghost and outline buttons

.changeset/eighty-rockets-carry.md, apps/pie-storybook/.storybook/preview.js, apps/pie-storybook/stories/pie-card-container.stories.ts, packages/components/pie-card-container/README.md, packages/components/pie-card-container/src/card-container.scss, packages/components/pie-card-container/src/defs.ts, packages/components/pie-card-container/test/visual/pie-card-container.spec.ts, yarn.lock
[Added] - support outline, inverse and outline-inverse variants
=> feat(pie-card-container): DSW-1167 add variant prop to card

apps/pie-storybook/.storybook/preview.ts, apps/pie-storybook/interfaces/story-options.ts, apps/pie-storybook/stories/pie-button.stories.ts, apps/pie-storybook/stories/pie-card-container.stories.ts, apps/pie-storybook/stories/pie-divider.stories.ts, apps/pie-storybook/stories/pie-icon-button.stories.ts, apps/pie-storybook/stories/pie-link.stories.ts, apps/pie-storybook/stories/pie-toggle-switch.stories.ts, apps/pie-storybook/types/StoryOptions.ts, apps/pie-storybook/utilities/index.ts
- Modal and cookie banner are still to-do, but I'll attempt this in a following PR. They're a bit more complicated because they have multiple templates.
=> refactor(pie-storybook): DSW-1218 make story creation more generic

apps/pie-storybook/stories/pie-cookie-banner.stories.ts, apps/pie-storybook/stories/pie-modal.stories.ts, yarn.lock
Small refactor to align these stories with the other components'. I thought it would be a bit trickier but I was just over-complicating it 😄
=> refactor(pie-storybook): DSW-1218 use createStory for modal and cookie banner

.changeset/tame-icons-cheer.md, packages/components/pie-cookie-banner/src/index.ts, packages/components/pie-cookie-banner/test/component/pie-cookie-banner.spec.ts, packages/components/pie-cookie-banner/test/visual/pie-cookie-banner.spec.ts
[Added] - hook up text links to button actions
=> feat(pie-cookie-banner): DSW-1215 hook up text links to button actions

.changeset/mean-badgers-sniff.md, packages/tools/generator-pie-component/src/app/templates/pie-placeholder.__stories__.ts
- [Added] - use createStory in component generator
- [Fixed] - whitespace in generated story file
=> feat(generator-pie-component): DSW-1218 use createStory in component generator

.changeset/forty-geckos-work.md, apps/pie-storybook/stories/pie-card-container.stories.ts, packages/components/pie-card-container/README.md, packages/components/pie-card-container/src/card-container.scss, packages/components/pie-card-container/src/defs.ts, packages/components/pie-card-container/src/index.ts, packages/components/pie-card-container/test/component/pie-card-container.spec.ts, packages/components/pie-card-container/test/visual/pie-card-container.spec.ts, yarn.lock
[Added] Button and Link behavior to the card container
=> feat(pie-card-container): DSW-1192 support link and button behavior

.changeset/wet-kids-teach.md, packages/tools/pie-css/README.md
[Added] - README written for pie-css
=> docs(pie-css): DSW-000 pie-css readme updated

.changeset/shy-spies-behave.md, apps/pie-storybook/stories/pie-link.stories.ts, packages/components/pie-card-container/test/component/pie-card-container.spec.ts, packages/components/pie-link/README.md, packages/components/pie-link/src/defs.ts, packages/components/pie-link/src/index.ts, packages/components/pie-link/test/component/pie-link.spec.ts
[Added] aria labels to the pie link
=> feat(pie-link): DSW-1020 add aria labels

.changeset/selfish-paws-behave.md, packages/components/pie-toggle-switch/src/defs.ts, packages/components/pie-toggle-switch/src/index.ts, packages/components/pie-toggle-switch/src/toggle-switch.scss, packages/components/pie-toggle-switch/test/component/pie-toggle-switch.spec.ts
[Fixed] - The label should have the same cursor as the control itself
[Fixed]- The cursor should be disabled, following the same pattern as the Button
=> fix(pie-toggle-switch): DSW-1123 address design feedback

.changeset/cold-bears-kiss.md, packages/components/pie-cookie-banner/src/cookie-banner.scss, packages/tools/pie-css/README.md, packages/tools/pie-css/css/input.css, packages/tools/pie-css/test/css/__snapshots__/css.spec.ts.snap
[Added] - z-index tokens to the pie-css package. 
📓 the z-index values are defined and designed with the help of @jordifornellsJET
📓 the ticket description includes a spreadsheet that analyzes the priority order of our components on a webpage. 
[Fixed] - Ensure the cookie banner has a correct stacking order
=> feat(pie-css): DSW-1204 z-index css variables 

.changeset/chatty-pumas-fry.md, apps/pie-docs/src/components/avatar/avatar.md
=> feat(pie-docs): DSW-000 update avatar status

.changeset/slimy-chicken-count.md, packages/components/pie-modal/src/modal.scss, yarn.lock
- [Changed] - Update header styles to fix spacing inconsistencies
The problems were to do with the spacing above the header text being incorrect when the text flows onto multiple lines, and also changing when buttons were present or not.
=> cosmetic(pie-modal): DSW-1316 fix modal header spacing issues

.changeset/gold-queens-report.md, apps/pie-docs/package.json, yarn.lock
---
"pie-docs": minor
---
[Updated] - Dependencies:
@types/markdown-it 13.0.0 > 13.0.2
markdown-it 13.0.1 > 13.0.2
node-html-parser 16.1.5 > 16.1.10
=> chore(pie-docs): DSW-000 update dependencies

.changeset/selfish-boxes-explain.md, .github/workflows/changeset-release.yml, apps/pie-storybook/package.json, yarn.lock
This PR fixes the conditional to generate the Slack message on successful publish
=> feat(pie-monorepo): DSW-1330 fix conditional for generating slack message

.changeset/silver-queens-train.md, apps/examples/wc-nuxt3/nuxt.config.ts
[Fixed] - Stop Nuxt re-compiling monorepo packages
Linked to this issue, [which has more details](https://github.com/nuxt/nuxt/issues/18823).
=> fix(pie-monorepo): DSW-000 fix nuxt3 build issue

commitlint.config.js, renovate.json
- When renovate generates a commit message it puts the message in lowercase. This is the simplest option as the alternative is turning off the forcing of lowercase for commit messages entirely.
=> ci(pie-monorepo): DSW-000 update commitlint to accept lowercase ticket numbers

.github/workflows/pr-title-linter.yml
- Missed a bit, so updating the github workflow too
=> ci(pie-monorepo): DSW-000 update pr linter workflow to accept lowercase ticket numbers

.changeset/nasty-monkeys-own.md, apps/pie-storybook/.storybook/main.ts, apps/pie-storybook/package.json, apps/pie-storybook/stories/pie-cookie-banner.stories.ts, packages/components/pie-cookie-banner/README.md, packages/components/pie-cookie-banner/src/defs.ts, packages/components/pie-cookie-banner/src/index.ts, packages/components/pie-cookie-banner/test/component/pie-cookie-banner.spec.ts, packages/components/pie-cookie-banner/test/visual/pie-cookie-banner.spec.ts, yarn.lock
=> feat(pie-cookie-banner): DSW-1397 add hasPrimaryActionsOnly prop

commitlint.config.js
- Revert change which was breaking commitlint
=> ci(pie-monorepo): DSW-000 revert header pattern regex

.github/project-labeler.yml, .github/workflows/ci.yml, apps/pie-storybook/package.json, apps/pie-storybook/stories/pie-notification.stories.ts, packages/components/pie-notification/.eslintignore, packages/components/pie-notification/README.md, packages/components/pie-notification/declaration.d.ts, packages/components/pie-notification/package.json, packages/components/pie-notification/playwright-lit-visual.config.ts, packages/components/pie-notification/playwright-lit.config.ts, packages/components/pie-notification/playwright/index.html, packages/components/pie-notification/playwright/index.ts, packages/components/pie-notification/src/defs.ts, packages/components/pie-notification/src/index.ts, packages/components/pie-notification/src/notification.scss, packages/components/pie-notification/test/accessibility/pie-notification.spec.ts, packages/components/pie-notification/test/component/pie-notification.spec.ts, packages/components/pie-notification/test/visual/pie-notification.spec.ts, packages/components/pie-notification/tsconfig.json, packages/components/pie-notification/vite.config.js, packages/tools/generator-pie-component/README.md, yarn.lock
=> feat(pie-notification): DSW-1347 generate notification skeleton

.changeset/eleven-cherries-worry.md, packages/components/pie-form-label/README.md, packages/components/pie-notification/README.md, packages/components/pie-spinner/README.md, packages/tools/generator-pie-component/src/app/templates/README.md
=> fix(generator-pie-component): DSW-000 update readme to align with latest updates

.changeset/long-meals-help.md, packages/components/pie-cookie-banner/src/localisation-utils.ts
=> fix(pie-cookie-banner): DSW-000 TS errors fix

.changeset/giant-falcons-burn.md, packages/components/pie-cookie-banner/package.json, yarn.lock
It's already listed as a `devDependency`, where it should be.
=> chore(pie-cookie-banner): DSW-000 fix incorrect merge conflict resolution

.changeset/gentle-elephants-visit.md, apps/pie-docs/src/components/template/motion.md, yarn.lock
[Added] - Motion content placeholders
=> feat(pie-docs): DSW-1446 added motion placeholder content

.changeset/wet-garlics-share.md, apps/pie-docs/src/_11ty/shortcodes/componentDetailsTable.js, apps/pie-docs/src/_11ty/shortcodes/index.js, apps/pie-docs/src/assets/styles/_dependencies.scss, apps/pie-docs/src/assets/styles/components/_componentDetailsTable.scss, apps/pie-docs/src/components/template/style.md, apps/pie-docs/src/components/template/style/colour-tokens.json, apps/pie-docs/src/components/template/style/style.md, apps/pie-docs/src/components/template/style/typography-tokens.json, apps/pie-docs/src/components/template/template.json
-  add component style template
=> feat(pie-docs): DSW-1325 add component style template

.changeset/sweet-otters-double.md, apps/pie-docs/src/assets/js/contents.js
=> feat(pie-docs): DSW-000 contents bug

.changeset/yellow-students-camp.md, packages/components/pie-modal/package.json, packages/components/pie-modal/src/index.ts, packages/components/pie-modal/src/modal.scss, yarn.lock
[Changed] - reuse pie-spinner in pie-modal
=> feat(pie-modal): DSW-1430 add pie-spinner to pie-modal

.changeset/bright-jeans-watch.md, apps/pie-docs/src/_11ty/shortcodes/componentDetailsTable.js, apps/pie-docs/src/components/template/code.md, apps/pie-docs/src/components/template/code/code.md, apps/pie-docs/src/components/template/code/events.json, apps/pie-docs/src/components/template/code/methods.json, apps/pie-docs/src/components/template/code/props.json, apps/pie-docs/src/components/template/code/slots.json
=> feat(pie-docs): DSW-000 add base code page template

.changeset/breezy-tips-decide.md, apps/pie-storybook/stories/pie-button.stories.tsx, packages/components/pie-button/README.md, packages/components/pie-button/src/button.scss, packages/components/pie-button/src/defs.ts, packages/components/pie-button/src/index.ts, packages/components/pie-button/test/component/pie-button.spec.ts, packages/components/pie-button/test/visual/pie-button-size.spec.ts, packages/components/pie-button/test/visual/pie-button.spec.ts
[Added] - `isResponsive` and `responsiveSize` prop
=> feat(pie-button): DSW-1293 implement responsive mode

.changeset/smooth-tigers-doubt.md, apps/pie-docs/src/components/button/code/props.json, apps/pie-storybook/stories/pie-button.stories.tsx
This is a follow-up to Raouf's comments on the [previous PR](https://github.com/justeattakeaway/pie/pull/986)
- Update `pie-docs` `props.json`
- Add conditional to `responsiveSize` prop Button Story
=> chore(pie-button): DSW-000 follow-up changes for DSW-1293 code review

.changeset/rich-dryers-wash.md, dangerfile.js
[Fixed] - danger check allow pre-json changes through
=> fix(pie-monorepo): DSW-000 fixed dangerjs issue for version prs

apps/pie-docs/src/components/button/code/code.md, apps/pie-docs/src/components/button/code/props.json, apps/pie-docs/src/components/icon-button/code/code.md, apps/pie-docs/src/components/icon-button/code/props.json, apps/pie-docs/src/components/template/code/code.md, apps/pie-docs/test/snapshots/expected-routes.snapshot.json, apps/pie-storybook/stories/pie-icon-button-docs/variants.mdx, packages/components/pie-icon-button/README.md
- adds the code page for the icon button component.
📓 this branch is created on top the overview page so the first should be merged first
=> feat(pie-docs): DSW-1484 add code section for icon button

.changeset/pre.json
CI wasn't able to automatically exit pre-release as we forgot to add the code to add / commit the changes after exiting.
I'll add this functionality as a future ticket, but for now, this is the easiest way to unblock the pipeline :)
=> ci(pie-monorepo): DSW-000 exit pre-release

.github/workflows/changeset-snapshot.yml, yarn.lock
Test PR to check snapshot functionality.
=> fix(pie-monorepo): DSW-000 use correct env var for snapshot functionality

.github/workflows/changeset-snapshot.yml
Added this block of code as seen in the Polaris repo to prevent the snapshot release failing - https://github.com/Shopify/polaris/blob/main/.github/workflows/snapit.yml#L63C1-L68C52
=> ci(pie-monorepo): DSW-000 checkout correct branch for snapshot release

.github/workflows/changeset-snapshot.yml
=> ci(pie-monorepo): DSW-000 correct yarn script

.changeset/slimy-dodos-try.md, apps/pie-storybook/stories/pie-card.stories.ts, packages/components/pie-icon-button/src/iconButton.scss, yarn.lock
[Changed] - the icon size of the xsmall icon-button should be 20px
[Changed] - rely on the padding prop to apply padding for the card stories
=> fix(pie-icon-button): DSW-000 address design feedback for icon button and card

.changeset/bar.md, .changeset/brown-feet-smell.md, .github/workflows/changeset-snapshot.yml
=> ci(pie-monorepo): DSW-000 build before snapshot

.changeset/two-falcons-decide.md, .github/workflows/changeset-snapshot.yml
=> chore(pie-monorepo): DSW-000 add turbo token to snapshot build

.changeset/tame-mayflies-suffer.md, .github/workflows/changeset-snapshot.yml, apps/pie-storybook/package.json
=> chore(pie-monorepo): DSW-000 ignore apps during snapshot comment

.changeset/flat-moons-know.md, .github/workflows/changeset-snapshot.yml
=> chore(pie-monorepo): DSW-000 use both methods of setting github token

packages/components/pie-webc-core/README.md, yarn.lock
=> docs(pie-webc-core): DSW-000 add readme contents

.changeset/nine-otters-battle.md, packages/components/pie-cookie-banner/locales/bg-bg.json, packages/components/pie-cookie-banner/locales/de-de.json, packages/components/pie-cookie-banner/locales/dk-dk.json, packages/components/pie-cookie-banner/locales/en-gb.json, packages/components/pie-cookie-banner/locales/fr-fr.json, packages/components/pie-cookie-banner/locales/it-it.json, packages/components/pie-cookie-banner/locales/nl-nl.json, packages/components/pie-cookie-banner/locales/pl-pl.json, packages/components/pie-cookie-banner/src/index.ts, yarn.lock
- [Changed] - URLs for the cookie statement and tech list
=> feat(pie-cookie-banner): DSW-1506 added cookie urls

.github/workflows/closed.yml
=> ci(pie-monorepo): DSW-000 fix function to get GH envs

.github/workflows/closed.yml
=> ci(pie-monorepo): DSW-000 fix conditional values in GH actions workflow

.github/actions/amplify-teardown/action.yml, .github/workflows/closed.yml
=> fix(pie-monorepo): DSW-000 correct environment-name format

.github/workflows/changeset-snapshot.yml, yarn.lock
=> chore(pie-monorepo): DSW-1540 improve changeset snapshot messaging

.github/workflows/changeset-snapshot.yml, yarn.lock
=> chore(pie-monorepo): DSW-1540 use correct environment variables

.github/workflows/changeset-snapshot.yml
=> chore(pie-monorepo): DSW-1540 add link to workflow tooling wiki page

.changeset/honest-penguins-wink.md, .changeset/ten-impalas-mate.md, apps/pie-storybook/stories/pie-input.stories.ts, packages/components/pie-input/src/index.ts, yarn.lock
---
---
[Added] - Use the FormControlMixin to add form association logic to the input component
---
---
[Added] - A form integration story for pie input to start testing form data and submission
=> feat(pie-input): DSW-1582 add form association logic

.github/workflows/closed.yml
This PR should provide the closed.yml workflow a token with more permisisons, allowing it to delete envs.
=> chore(pie-monorepo): DSW-000 use token with increased permissions to delete GH envs of closed PRs

package.json, yarn.lock
Snyk insists on doing this as part of a bigger PR, but I thought I'd just test this update and it works fine on its own. It helps that we're only using the CLI rather than any imported functions.
=> chore(pie-monorepo): DSW-000 update rimraf to v5

apps/pie-docs/src/components/tag/code/code.md, apps/pie-docs/src/components/tag/code/props.json, apps/pie-docs/src/components/tag/code/slots.json, apps/pie-docs/src/components/tag/overview/overview.md, apps/pie-docs/test/snapshots/expected-routes.snapshot.json, packages/components/pie-tag/README.md
=> feat(pie-tag): DSW-1523 add pie tag code docs

.github/workflows/dangerjs-checks.yml
=> fix(pie-monorepo): DSW-000 correct logical operator

.changeset/eighty-items-wash.md, packages/components/pie-card/src/index.ts, packages/components/pie-card/test/component/pie-card.spec.ts, packages/components/pie-form-label/src/index.ts, packages/components/pie-icon-button/src/index.ts, packages/components/pie-spinner/src/index.ts
Fixes components props with inconsistencies highlighted by the `lit-plugin`.
=> fix(pie-card): DSW-000 Fix components props consistency issues

.github/actions/amplify-teardown/action.yml, .github/workflows/closed.yml
Changes have already been tested and merged in the partner repo - https://github.com/justeattakeaway/pie-local-partner/actions/runs/7572654000/job/20622990639
=> ci(pie-monorepo): DSW-000 fixes an issue where GH / Amplify teardown had insufficient permissions

.changeset/healthy-parrots-relate.md, packages/tools/pie-css/scss/functions/_unitModifiers.scss
=> fix(pie-css): DSW-000 fix stylelint error

packages/components/pie-switch/test/visual/pie-switch.spec.ts, turbo.json
- Fix pie-switch linting
- Fix our turbo.json caching config
- Updated wiki section with info about caching behaviour - https://github.com/justeattakeaway/pie/wiki/Contributing-Guide#turborepo
=> fix(pie-switch): DSW-000 fix linting

.changeset/twenty-wolves-drop.md, apps/pie-docs/src/componentStatusData.js
[Changed] - component status updates
=> docs(pie-docs): DSW-000 component status updates

.changeset/itchy-chefs-wink.md, packages/components/pie-tag/test/visual/pie-tag.spec.ts
[Fixed] - Percy test mounting issue
=> fix(pie-tag): DSW-000 percy visual test fix

.changeset/weak-shrimps-wave.md, packages/components/pie-switch/test/visual/pie-switch.spec.ts, packages/components/pie-webc-testing/src/helpers/index.ts, packages/components/pie-webc-testing/src/helpers/set-rtl-direction.ts
- Added exportable RTL function
- Updated `pie-switch`'s visual test to use new function
=> refactor(pie-webc-testing): DSW-1676 added exportable RTL function

.changeset/wet-cobras-burn.md, packages/components/pie-tag/src/tag.scss
=> fix(pie-tag): DSW-000 address design feedback

.changeset/lemon-mugs-rule.md, packages/components/pie-button/test/visual/pie-button.spec.ts, packages/components/pie-card/test/visual/pie-card.spec.ts, packages/components/pie-divider/test/visual/pie-divider.spec.ts, packages/components/pie-form-label/test/visual/pie-form-label.spec.ts, packages/components/pie-icon-button/test/visual/pie-icon-button.spec.ts, packages/components/pie-link/test/visual/pie-link.spec.ts, packages/components/pie-spinner/test/visual/pie-spinner.spec.ts, packages/components/pie-tag/test/visual/pie-tag.spec.ts, yarn.lock
---
---
[Changed] - Standardise component mount/unmount approach across component tests
=> refactor(pie-monorepo): DSW-0 standardise mount/unmount test syntax

.changeset/fresh-shoes-stare.md, apps/pie-storybook/stories/pie-cookie-banner.stories.ts, packages/components/pie-cookie-banner/README.md, packages/components/pie-cookie-banner/src/defs.ts, packages/components/pie-cookie-banner/src/index.ts
=> feat(pie-cookie-banner): DSW-1702 cookie banner prop bug

apps/pie-storybook/stories/pie-cookie-banner.stories.ts
The versioning PR is failing due to that https://github.com/justeattakeaway/pie/pull/1234
=> fix(pie-storybook): DSW-000 remove quotes from a prop value in cookie banner

.changeset/thick-rabbits-shout.md, dangerfile.js
- Added Danger fail for future PRs to stop them being merged before the PR checklists are complete/up-to-date
=> feat(pie-monorepo): DSW-000 added danger check for pr checkboxes

.changeset/forty-donuts-reflect.md, apps/pie-docs/test/system/footer.spec.js
- Un-skipped the privacy policy test.
=> fix(pie-docs): DSW-1721 Privacy policy 200 fix

.changeset/dull-ligers-obey.md, .changeset/sweet-parents-compare.md, packages/components/pie-assistive-text/package.json, packages/tools/generator-pie-component/README.md, yarn.lock
[Fixed] - Add missing pie-icons-webc dependency
[Added] - Instructions to component generator readme to update workspace dependencies
No visual changes.
No visual changes.
=> chore(pie-assistive-text): DSW-000 add missing pie-icons-webc dependency

.changeset/chatty-owls-fix.md, packages/components/pie-chip/src/index.ts
=> fix(pie-chip): DSW-000 import pie-spinner in the component

.changeset/soft-houses-sneeze.md, apps/pie-docs/src/all-about-pie/roadmap.md, yarn.lock
Updates the docs site roadmap page to reflect the latest information
=> docs(pie-docs): DSW-1510 update roadmap

.github/project-labeler.yml, packages/components/pie-webc/.gitignore, packages/components/pie-webc/package.json, packages/components/pie-webc/src/index.ts, packages/components/pie-webc/src/react.ts, yarn.lock
- No changes for individual components.
- No changes for individual components.
=> feat(pie-webc): DSW-1657 add button and modal to component bundle

.changeset/itchy-days-explain.md, .changeset/new-tomatoes-give.md, apps/pie-storybook/stories/pie-modal.stories.ts, packages/components/pie-chip/src/index.ts, packages/components/pie-cookie-banner/src/index.ts, packages/components/pie-modal/src/index.ts, packages/components/pie-webc-core/src/functions/dispatchCustomEvent.ts, packages/components/pie-webc-core/src/functions/index.ts, packages/components/pie-webc-core/src/test/functions/dispatchCustomElement/MockComponent.ts, packages/components/pie-webc-core/src/test/functions/dispatchCustomElement/dispatchCustomEvent.browser.spec.ts, packages/components/pie-webc-core/vite.config.js, packages/tools/generator-pie-component/vite.config.js, packages/tools/pie-icons-webc/vite.config.js, vite.config.js
---
"@justeattakeaway/pie-webc-core": minor
---
[Added] - dispatchCustomEvent helper function
---
"@justeattakeaway/pie-cookie-banner": patch
"@justeattakeaway/pie-modal": patch
---
[Changed] - local dispatchCustomEvent function replaced with a helper from `pie-webc-core` package
=> feat(pie-webc-core): DSW-1732 dispatch custom event helper function

apps/pie-docs/src/foundations/illustration/illustration.json, apps/pie-docs/src/foundations/illustration/illustration.md, apps/pie-docs/src/foundations/illustration/library.md, apps/pie-docs/src/foundations/illustration/pattern.md, apps/pie-docs/src/foundations/illustration/product.md, apps/pie-docs/src/foundations/radius/radius.md, apps/pie-docs/src/foundations/spacing/spacing.md, apps/pie-docs/src/foundations/typography/typography.md, yarn.lock
=> docs(pie-docs): DSW-1388 initial setup for the illustration page

.changeset/chilled-experts-warn.md, .changeset/nasty-llamas-grab.md, apps/pie-storybook/CHANGELOG.md, apps/pie-storybook/package.json, package.json, packages/components/pie-tag/CHANGELOG.md, packages/components/pie-tag/package.json, packages/tools/pie-icons-react/package.json, packages/tools/pie-icons-vue/package.json, packages/tools/pie-icons-webc/package.json, packages/tools/pie-icons/CHANGELOG.md, packages/tools/pie-icons/package.json
Reverts justeattakeaway/pie#1299
For some reason, this caused issues in main - https://github.com/justeattakeaway/pie/actions/runs/8021868236/job/21915605707
=> chore(pie-monorepo): DSW-000 Revert "Version Packages"

.changeset/heavy-mayflies-wonder.md, apps/pie-storybook/stories/pie-assistive-text.stories.ts, apps/pie-storybook/stories/pie-input.stories.ts, packages/components/pie-input/README.md, packages/components/pie-input/package.json, packages/components/pie-input/src/defs.ts, packages/components/pie-input/src/index.ts, packages/components/pie-input/test/component/pie-input.spec.ts, packages/components/pie-input/test/visual/pie-input.spec.ts, yarn.lock
[Added] - Integrate assistive text component into input
=> feat(pie-input): DSW-1648 integrate assistive text component into input

.changeset/brown-rivers-work.md, apps/pie-docs/src/components/chip/code/code.md, apps/pie-docs/src/components/chip/code/props.json, apps/pie-docs/src/components/chip/code/slots.json, apps/pie-docs/src/components/chip/overview/overview.md, apps/pie-docs/src/components/tag/code/props.json, apps/pie-docs/test/snapshots/expected-routes.snapshot.json, apps/pie-storybook/stories/pie-chip-docs/variants.mdx, packages/components/pie-chip/README.md, packages/components/pie-tag/README.md
- adds the code section of the chip component
=> feat(pie-docs): DSW-1639 Add the chip code page

packages/components/pie-cookie-banner/test/component/pie-cookie-banner.spec.ts, packages/components/pie-cookie-banner/test/helpers/page-object/pie-cookie-banner.page.ts, packages/components/pie-modal/test/component/pie-modal.spec.ts, packages/components/pie-modal/test/helpers/page-object/pie-modal.page.ts
- Updated pie modal page object to match format in pie cookie banner
- No docs site changes.
- No docs site changes.
=> refactor(pie-modal): DSW-000 pie modal page object refactor

packages/components/pie-cookie-banner/README.md, yarn.lock
Simply adds section to the cookie banner readme about cookie management
=> docs(pie-cookie-banner): DSW-000 mention cookie handling in readme

.changeset/stupid-zebras-cough.md, apps/pie-storybook/stories/pie-input.stories.ts, packages/components/pie-input/README.md, packages/components/pie-input/src/defs.ts, packages/components/pie-input/src/index.ts, packages/components/pie-input/test/component/pie-input.spec.ts
Adds a new `required` prop to the input component
=> feat(pie-input): DSW-1584 add required prop

.changeset/eleven-singers-brake.md, .github/workflows/ci.yml
---
---
[Added] - Automatic changeset generation for Synk PR's
=> feat(pie-monorepo): DSW-000 Automatically generate changesets for  Snyk dependency updates

.changeset/nervous-waves-report.md, packages/components/pie-input/package.json, packages/components/pie-input/src/index.ts, yarn.lock
---
---
[Added] - Use the element internals polyfill in pie-input component
=> feat(pie-input): DSW-000 add element internals polyfill

dangerfile.js
- Don't run danger checks for changeset files if the PR author is renovate
Recommended reviewing with whitespace changes hidden.
=> chore(pie-monorepo): DSW-000 Exclude renovate PRs from changeset category requirements

dangerfile.js
I missed one of the checks in the previous PR, so that is now included. I have also extracted the renovate / dependabot checks into variables.
Again it is also recommended to hide whitespace changes when reviewing 😄
=> chore(pie-monorepo): DSW-000 ignore all changeset checks for renovate PRs

.changeset/hungry-socks-unite.md, apps/pie-storybook/stories/pie-notification.stories.ts, packages/components/pie-notification/src/index.ts, packages/components/pie-notification/src/notification.scss, packages/components/pie-notification/test/component/pie-notification.spec.ts
Addresses the design review feedback:
- The icons size should be 24 x 24px
- The top padding of the icon is currently 4px, and needs to be reduced to 2px
- The title should use token 'heading-s/narrow' (16px, 24lh)
- Update the story title text to `heading` to be consistent
- The space between the title and supporting text should be 4px
- The supporting text shouldn't run underneath the close icon.
- When 'stacked actions = true', the leading action should be above.
=> fix(pie-notification): DSW-1963 address design review notes

packages/components/README.md, yarn.lock
Small PR to add some more information on developing components based on feedback during our external contributors retro
=> docs(pie-monorepo): DSW-000 add info on developing components to readme

.changeset/silent-bottles-impress.md, apps/pie-docs/src/_data/resourceSettings.js, apps/pie-docs/src/_data/resourceTypes.js, apps/pie-docs/src/componentStatusData.js, apps/pie-docs/src/components/tag/overview/overview.md
- Unified the Android libraries into just Android PIE 
- Updated the component status to the latest revision
=> docs(pie-docs): DSW-000 update component status for android

.changeset/six-files-peel.md, apps/pie-docs/README.md, apps/pie-docs/src/all-about-pie/what-is-pie.md, apps/pie-docs/src/designers/getting-started/overview.md
Philip run an audit of content and identified small changes that can be done already in copy. Those are included in this PR. Additionally some changes in the pie-docs README based on feedback from our team. For details of the audit, please refer to DSW-2028.
=> docs(pie-docs): DSW-000 small content updates and README improvements

.changeset/eight-buckets-speak.md, apps/pie-docs/src/components/notification/code/code.md, apps/pie-docs/src/components/notification/code/events.json, apps/pie-docs/src/components/notification/code/props.json, apps/pie-docs/src/components/notification/code/slots.json, apps/pie-docs/test/snapshots/expected-routes.snapshot.json, apps/pie-storybook/stories/pie-notification-docs/variants.mdx, packages/components/pie-notification/src/defs.ts, packages/components/pie-notification/src/index.ts
- adds the code section of the Notification component
=> feat(pie-notification): DSW-1899 add the code section to docs

.changeset/wild-beers-think.md, apps/pie-storybook/.storybook/styles/component-status.scss
=> fix(pie-storybook): DSW-2059 fix misaligned icon

.changeset/tall-hounds-cry.md, packages/components/pie-modal/package.json
Please click the `Preview` tab and select a different PR template if your change isn't for an                                            existing web component.
[PIE Docs Template](?expand=1&template=docs_template.md)
[New Web Component Template](?expand=1&template=new_component_template.md)
═══════════════════════════════════════════════════════════
=> feat(pie-modal): DSW-000 updated component status to beta

.changeset/healthy-ladybugs-shake.md, packages/components/pie-checkbox/test/component/pie-checkbox.spec.ts
Please click the `Preview` tab and select a different PR template if your change isn't for an                                            existing web component.
[PIE Docs Template](?expand=1&template=docs_template.md)
[New Web Component Template](?expand=1&template=new_component_template.md)
═══════════════════════════════════════════════════════════
=> format(pie-checkbox): DSW-000 fixed line breaks causing linting errors

.github/workflows/closed.yml
- Updated `closed.yml` with `per_page: 100` to close AWS deployments
=> ci(pie-monorepo): DSW-2146 updated closed.yml with `per_page: 100` to cover more closures

.changeset/ninety-lamps-grab.md, .changeset/shaggy-squids-occur.md, packages/components/pie-assistive-text/package.json, packages/components/pie-text-input/package.json
---
"@justeattakeaway/pie-text-input": minor
---
[Changed] - Bumped the text-input status from Alpha to Beta
=> feat(pie-text-input): DSW-000 promote to beta

.changeset/lemon-stingrays-relate.md, packages/components/pie-checkbox/package.json, yarn.lock
"@justeattakeaway/pie-checkbox": patch
---
[Added] - Missing dependency on pie-assistive-text
---
=> fix(pie-checkbox): DSW-000 add missing pie-assistive-text dependency

.github/workflows/dangerjs-checks.yml, dangerfile.js
Prevent danger checks until PR is ready for review
=> chore(pie-monorepo): DSW-000 do not run danger checks on drafts

.github/workflows/amplify-deploy.yml
- Updated `amplify-deploy.yml` to fix pie-docs demployments
=> ci(pie-docs): DSW-000 updated amplify deployment for pie docs

apps/examples/wc-next13/package.json, yarn.lock
Renovate is failing on #1527, so trying manually.
=> chore(pie-monorepo): DSW-000 upgrade next version in next 13 example app

packages/components/pie-assistive-text/test/visual/pie-assistive-text.spec.ts
- Fixed bug with promise resolution in visual test in Pie Assistive Text
=> fix(pie-assistive-text): DSW-1969 updated visual test to fix promise bug

.changeset/silver-dryers-attack.md, apps/examples/wc-angular12/package.json, apps/examples/wc-angular12/src/app/app.component.ts, yarn.lock
- Update Angular example app to use `pie-webc` for component dependencies.
=> feat(pie-monorepo): DSW-2056 pie webc integration angular12

.changeset/dry-frogs-grin.md, .changeset/wicked-crews-serve.md, apps/pie-storybook/stories/pie-checkbox-group.stories.ts, apps/pie-storybook/stories/pie-checkbox.stories.ts, packages/components/pie-checkbox-group/README.md, packages/components/pie-checkbox-group/package.json, packages/components/pie-checkbox-group/src/defs-react.ts, packages/components/pie-checkbox-group/src/defs.ts, packages/components/pie-checkbox-group/src/index.ts, packages/components/pie-checkbox-group/test/component/pie-checkbox-group.spec.ts, packages/components/pie-checkbox/README.md, packages/components/pie-checkbox/src/defs.ts, packages/components/pie-checkbox/src/index.ts, yarn.lock
**"@justeattakeaway/pie-checkbox-group": minor
"pie-storybook": patch**
---
[Added] - main logic for checkbox-group
---
"@justeattakeaway/pie-checkbox": minor
---
[Added] - event listener for pie-checkbox-group-disabled custom event
[Removed] - aria prop since aria attributes should be passed to the component directly
**Note:** css styles along with Percy tests update will come in a separate PR
The Aperture PR: https://github.com/justeattakeaway/pie-aperture/pull/176
=> feat(pie-checkbox-group): DSW-2182 main component functionality

.github/workflows/changeset-snapshot/test-aperture.js, .github/workflows/ci.yml, .github/workflows/example-apps-ci.yml
Fixed example apps jobs in `main` and fixes issue with docs / storybook change detection
=> chore(pie-monorepo): DSW-000 Fix example apps and modify change detection filter

.changeset/bright-swans-beam.md, .github/workflows/ci.yml, apps/pie-docs/turbo.json, apps/pie-storybook/turbo.json, package.json, packages/tools/pie-css/turbo.json, packages/tools/pie-icons-react/turbo.json, packages/tools/pie-icons-vue/turbo.json, packages/tools/pie-icons-webc/turbo.json, packages/tools/pie-icons/turbo.json, turbo.json, yarn.lock
=> ci(pie-monorepo): DSW-000 downgrade turbo to v1

.changeset/real-clocks-swim.md, apps/pie-storybook/.storybook/preview.ts
Alphabetically sorts the components in the Storybook sidebar
=> feat(pie-storybook): DSW-000 alphabetically sort components and stories

.changeset/eleven-timers-decide.md, apps/pie-docs/src/components/checkbox/overview/code.md, apps/pie-docs/src/components/checkbox/overview/events.json, apps/pie-docs/src/components/checkbox/overview/props.json, apps/pie-docs/src/components/checkbox/overview/slots.json, apps/pie-docs/test/snapshots/expected-routes.snapshot.json, packages/components/pie-checkbox/README.md
=> docs(pie-checkbox): DSW-2221 code page checkbox

.changeset/fifty-jars-sparkle.md, packages/components/pie-assistive-text/src/assistive-text.scss, packages/components/pie-assistive-text/src/index.ts, packages/components/pie-assistive-text/test/component/pie-assistive-text.spec.ts
---
"@justeattakeaway/pie-assistive-text": minor
---
[Changed] - Use classmap for assistive-text variant styles
=> feat(pie-assistive-text): DSW-2280 use classmap for variant styles

.changeset/slow-seahorses-hear.md, apps/pie-docs/src/assets/styles/components/_contentLayout.scss
[Changed] - contentLayout styles
=> feat(pie-docs): DSW-2361 change container height

.changeset/spotty-donkeys-peel.md, apps/pie-storybook/stories/pie-switch.stories.ts, packages/components/pie-switch/src/defs-react.ts, packages/components/pie-switch/src/defs.ts, packages/components/pie-switch/src/index.ts, packages/components/pie-switch/src/switch.scss, packages/components/pie-switch/test/component/pie-switch.spec.ts, packages/components/pie-switch/test/visual/pie-switch.spec.ts, yarn.lock
=> refactor(pie-switch): DSW-2280 use classes instead of attributes for styling

.changeset/nice-clocks-prove.md, .github/workflows/ci.yml, dangerfile.js, yarn.lock
Reverts justeattakeaway/pie#1724
=> revert(pie-monorepo): DSW-000 auto updated lockfile and dangerjs check for missing lock file

.changeset/real-bobcats-run.md, apps/pie-docs/src/componentStatusData.js, packages/components/pie-checkbox-group/package.json, packages/components/pie-checkbox/package.json
Feature url: https://pr1729-docs.pie.design/components/checkbox/
=> docs(pie-checkbox): DSW-000 checkbox and checkbox-group from Alpha to Beta

.changeset/lemon-kids-scream.md, package.json, packages/tools/pie-icons/package.json, yarn.lock
- Use latest webpack to resolve security alerts
#1735 #1737 #1738 #1739 #1740 #1741
=> chore(pie-icons): DSW-000 use latest webpack for security fixes

.github/workflows/changeset-snapshot/test-aperture.js, .github/workflows/ci.yml, .github/workflows/labeler.yml
Note: This fix will only be applied once merged to `main`
=> ci(pie-monorepo): DSW-2251 actions/labeler to v5

.changeset/chilled-tools-wonder.md, .changeset/thick-singers-train.md, packages/components/pie-button/test/accessibility/pie-button.spec.ts, packages/components/pie-button/test/visual/pie-button.spec.ts, packages/components/pie-spinner/src/defs-react.ts, packages/components/pie-spinner/src/defs.ts, packages/components/pie-spinner/src/index.ts, packages/components/pie-spinner/src/spinner.scss, packages/components/pie-spinner/test/accessibility/pie-spinner.spec.ts, packages/components/pie-spinner/test/component/pie-spinner.spec.ts, packages/components/pie-spinner/test/visual/pie-spinner.spec.ts, packages/components/pie-tag/test/accessibility/pie-tag.spec.ts, packages/components/pie-tag/test/visual/pie-tag.spec.ts, packages/components/pie-webc-testing/src/helpers/defs.ts, yarn.lock
=> refactor(pie-spinner): DSW-2280 use classes instead of attributes for styling

.changeset/moody-spoons-lay.md, packages/components/pie-lottie-player/src/index.ts
- [Fixed] - pie-lottie-player autoplay prop behaviour
=> fix(pie-lottie-player): DSW-000 fix autoPlayDisabled prop

.changeset/red-singers-press.md, packages/components/pie-notification/src/index.ts, packages/components/pie-notification/src/notification.scss, packages/components/pie-notification/test/component/pie-notification.spec.ts, yarn.lock
Removes custom HTML attributes used solely for styling and replaces with `classMap`
=> cosmetic(pie-notification): DSW-2280 use classmaps

.changeset/late-beds-clap.md, packages/components/pie-card/src/card.scss
[Changed] - Update the background color of the inverse card from `$color-container-dark` to `$color-container-inverse`
=> fix(pie-card): DSW-2287 update inverse variant tokens

.changeset/thin-boats-jog.md, apps/pie-storybook/package.json, yarn.lock
I encountered a resolution error when running Storybook locally (despite running `yarn`) and this appeared to fix the issue
your changes (can list changeset entries if preferable)
=> chore(pie-storybook): DSW-000 add pie-lottie-player as dep to storybook

.github/workflows/amplify-deploy.yml, apps/pie-docs/src/_11ty/collections/index.js, apps/pie-docs/src/_11ty/shortcodes/tokensTable/tokenTypes/radius.js, apps/pie-docs/src/_11ty/shortcodes/tokensTable/tokenTypes/spacing.js, apps/pie-docs/src/assets/img/components/icon-button/overview.svg, apps/pie-docs/src/foundations/colour/tokens/alias/toggled-content/dark-alias.content.md, apps/pie-docs/src/foundations/colour/tokens/alias/toggled-content/light-alias.content.md, packages/components/pie-checkbox/test/accessibility/pie-checkbox.spec.ts, packages/components/pie-checkbox/test/component/pie-checkbox.spec.ts
=> chore(pie-monorepo): DSW-000 update tagged commit for deployment-action in amplify script

apps/pie-storybook/stories/pie-card.stories.ts
=> format(pie-storybook): DSW-000 fix linting error

.changeset/long-actors-exercise.md, .github/actions/setup-repo/action.yml, package.json, packages/components/pie-webc-core/package.json, packages/tools/pie-icons-react/package.json, packages/tools/pie-icons-vue/package.json, packages/tools/pie-icons-webc/package.json, yarn.lock
- Combines the following automated PRs:
- #1948 
- #1942 
- #1687
=> chore(pie-monorepo): DSW-000 update several package versions to resolve security warnings

apps/pie-docs/README.md
[Changed] - Updated README instructions about snapshot testing
=> docs(pie-docs): DSW-000 update README testing instructions

.github/workflows/labeler.yml
Temporarily disable step breaking the labeler workflow
=> fix(pie-monorepo): DSW-000 disable step breaking the labeler workflow

packages/components/pie-textarea/test/visual/pie-textarea.spec.ts, packages/components/pie-toast/test/component/pie-toast.spec.ts
- Tiny change to reduce the usage of magic numbers in our test code
=> refactor(pie-monorepo): DSW-2470 convert test magic numbers to constants

.changeset/bright-cows-sparkle.md, packages/tools/generator-pie-component/src/app/prompts.ts
https://github.com/user-attachments/assets/96c650b3-3454-4497-94e1-135ab5973b6f
=> feat(generator-pie-component): DSW-000 Add yo prompt package validation

.changeset/olive-rings-look.md, packages/components/pie-button/package.json, packages/components/pie-divider/package.json, packages/components/pie-icon-button/package.json, packages/components/pie-link/package.json, packages/components/pie-modal/package.json, packages/components/pie-spinner/package.json, packages/components/pie-switch/package.json, packages/components/pie-tag/package.json
- Bumps some components to version `1.0.0`
=> feat(pie-monorepo): DSW-000 bump some components to v1

.github/actions/run-script/action.yml, package.json
=> fix(pie-monorepo): DSW-000 Revert change to fix visual reg on PRs

.github/workflows/labeler-get-labels.yml
- Fixes the path of the labeler workflow artifact
- Sets the retention period for the artifact
=> fix(pie-monorepo): DSW-000 fix labeler artifact path

.github/workflows/labeler-get-labels.yml
- Adds a fetch step in labeler workflow for fetching the main branch
=> fix(pie-monorepo): DSW-000 add missing step in labeler workflow

packages/tools/pie-monorepo-utils/__tests__/changeset-snapshot/create-and-publish.spec.js, packages/tools/pie-monorepo-utils/changeset-snapshot/create-and-publish.js, packages/tools/pie-monorepo-utils/changeset-snapshot/test-aperture.js, packages/tools/pie-monorepo-utils/create-icons-update-pr/create-icons-update-pr.js, packages/tools/pie-monorepo-utils/pr-labeler/get-added-component-packages.js, packages/tools/pie-monorepo-utils/pr-labeler/get-labels.js, packages/tools/pie-monorepo-utils/pr-labeler/set-labels.js, turbo.json
=> chore(pie-monorepo-utils): DSW-000 fix lint error

.github/dependabot.yml
Have tried a number of suggestions to catch these schema errors - https://github.com/dependabot/dependabot-core/issues/4605
However this still slipped through 🫠
=> chore(pie-monorepo): DSW-000 fix dependabot formatting

apps/pie-storybook/test/utilities/index.test.ts, yarn.lock
fixes linting issue to unblock https://github.com/justeattakeaway/pie/pull/2101
---
- [-] N/A I have reviewed the `PIE Storybook`/`PIE Docs` PR preview.
- [-] N/A If …
=> fix(pie-monorepo): DSW-000 fix lint

apps/pie-storybook/stories/testing/pie-cookie-banner.test.stories.ts
- Added `cookie-banner` to storybook test deployment
=> ci(pie-cookie-banner): DSW-000 add cookie banner story into test deploy

package.json, packages/tools/pie-css/turbo.json, packages/tools/pie-icons-react/turbo.json, packages/tools/pie-icons-vue/turbo.json, packages/tools/pie-icons-webc/turbo.json, packages/tools/pie-icons/turbo.json, turbo.json, yarn.lock
Reverts justeattakeaway/pie#2117
=> revert(pie-monorepo): DSW-000 add $TURBO_DEFAULT$ to turbo.json inputs

.changeset/cold-jobs-exist.md, packages/components/pie-toast-provider/package.json, packages/components/pie-toast/package.json, yarn.lock
- Moved the toast and toast-provider component to beta
---
- [-] N/A I have reviewed the `PIE Storybook`/`PIE Docs` PR preview.
- [-] N/A If there are visual test …
=> feat(pie-toast-provider): DSW-0000 move toast and toast provider to beta

packages/components/pie-cookie-banner/test/component/pie-cookie-banner-locale.spec.ts, packages/components/pie-cookie-banner/test/component/pie-cookie-banner.spec.ts, packages/components/pie-cookie-banner/test/helpers/page-object/pie-cookie-banner.page.ts
- [-] N/A I have reviewed visual test updates properly before approving.
- [-] N/A I have added thorough tests where applicable (unit / component / visual).
- [-] N/A If changes will affect consumers of the package, I have created a changeset entry.
- [-] N/A If a changeset file has been created, I have tested these changes in [PIE Aperture](https://github.com/justeattakeaway/pie-aperture/) using the `/test-aperture` command.
---
- [-] N/A I have …
=> fix(pie-cookie-banner): DSW-000 fix cookie-banner tests

apps/pie-storybook/stories/testing/pie-chip.test.stories.ts, apps/pie-storybook/stories/testing/pie-toast-provider.test.stories.ts
- Fix ESLint warnings by replacing console.log with console.info
---
=> fix(pie-monorepo): DSW-000 replace console.log with console.info

apps/pie-storybook/stories/pie-notification.stories.ts, apps/pie-storybook/stories/testing/pie-notification.test.stories.ts
- Ensures HTML can be used in the slot for Notification content in Storybook (no component changes)
(https://github.com/justeattakeaway/pie-aperture/) using the `/test-aperture` command.
---
| Aperture PR            | N/A |
| NextJS 14 deployment   | N/A |
| Nuxt 3 deployment      | N/A |
| Vanilla deployment     | N/A |
- [-] N/A I have reviewed the Aperture changes …
=> fix(pie-notification): DSW-000 allow html in the notification slot

apps/pie-storybook/.storybook/backgrounds.ts, apps/pie-storybook/.storybook/preview.ts, apps/pie-storybook/stories/testing/pie-card.test.stories.ts, apps/pie-storybook/stories/testing/pie-divider.test.stories.ts, apps/pie-storybook/types/StoryOptions.ts, apps/pie-storybook/utilities/index.ts, packages/components/pie-card/playwright-lit-visual.config.ts, packages/components/pie-card/playwright-lit.config.ts, packages/components/pie-card/src/index.ts, packages/components/pie-card/test/accessibility/pie-card.spec.ts, packages/components/pie-card/test/component/pie-card.spec.ts, packages/components/pie-card/test/helpers/page-object/pie-card-default.page.ts, packages/components/pie-card/test/helpers/page-object/pie-card-with-image.page.ts, packages/components/pie-card/test/helpers/page-object/pie-card.component.ts, packages/components/pie-card/test/helpers/page-object/selectors.ts, packages/components/pie-card/test/visual/pie-card.spec.ts, packages/components/pie-card/turbo.json, yarn.lock
- [-] N/A I have added thorough tests where applicable (unit / component / visual).
- [-] N/A If changes will affect consumers of the package, I have created a changeset entry.
- [-] N/A If a changeset file has been created, I have tested these changes in [PIE Aperture](https://github.com/justeattakeaway/pie-aperture/) using the `/test-aperture` command.
---
=> refactor(pie-card): DSW-2370 tests to use `@playwright/test`

apps/pie-storybook/stories/testing/pie-assistive-text.test.stories.ts, packages/components/pie-assistive-text/playwright-lit-visual.config.ts, packages/components/pie-assistive-text/playwright-lit.config.ts, packages/components/pie-assistive-text/test/accessibility/pie-assistive-text.spec.ts, packages/components/pie-assistive-text/test/component/pie-assistive-text.spec.ts, packages/components/pie-assistive-text/test/helpers/page-object/selectors.ts, packages/components/pie-assistive-text/test/visual/pie-assistive-text.spec.ts, packages/components/pie-assistive-text/turbo.json
=> refactor(pie-assistive-text): DSW-2331 tests to use `@playwright/test`

apps/pie-storybook/stories/testing/pie-form-label.test.stories.ts, packages/components/pie-form-label/playwright-lit-visual.config.ts, packages/components/pie-form-label/playwright-lit.config.ts, packages/components/pie-form-label/test/accessibility/pie-form-label.spec.ts, packages/components/pie-form-label/test/component/pie-form-label.spec.ts, packages/components/pie-form-label/test/helpers/page-object/selectors.ts, packages/components/pie-form-label/test/visual/pie-form-label.spec.ts, packages/components/pie-form-label/turbo.json
=> refactor(pie-form-label): DSW-2375 tests to use `@playwright/test`

apps/pie-storybook/stories/testing/pie-spinner.test.stories.ts, packages/components/pie-spinner/playwright-lit-visual.config.ts, packages/components/pie-spinner/playwright-lit.config.ts, packages/components/pie-spinner/test/accessibility/pie-spinner.spec.ts, packages/components/pie-spinner/test/component/pie-spinner.spec.ts, packages/components/pie-spinner/test/helpers/page-object/selectors.ts, packages/components/pie-spinner/test/visual/pie-spinner.spec.ts, packages/components/pie-spinner/turbo.json
---
- [-] NA I have reviewed the Aperture changes (if added)
- [-] NA I have reviewed the Aperture changes (if added)
=> refactor(pie-spinner): DSW-2381 tests to use `@playwright/test`

apps/pie-storybook/stories/testing/pie-icon-button.test.stories.ts, packages/components/pie-icon-button/playwright-lit-visual.config.ts, packages/components/pie-icon-button/playwright-lit.config.ts, packages/components/pie-icon-button/test/accessibility/pie-icon-button.spec.ts, packages/components/pie-icon-button/test/component/pie-icon-button.spec.ts, packages/components/pie-icon-button/test/helpers/page-object/selectors.ts, packages/components/pie-icon-button/test/visual/pie-icon-button.spec.ts, packages/components/pie-icon-button/turbo.json
=> refactor(pie-icon-button): DSW-2376 tests to use `@playwright/test`

.changeset/funny-rabbits-drum.md, packages/components/pie-thumbnail/src/defs.ts, packages/components/pie-thumbnail/src/index.ts, packages/components/pie-thumbnail/src/thumbnail.scss
- Updates the background color prop classes to camelCase
---
=> fix(pie-thumbnail): DSW-2584 update background class names to camelCase

apps/pie-storybook/stories/testing/pie-checkbox-group.test.stories.ts, packages/components/pie-checkbox-group/playwright-lit-visual.config.ts, packages/components/pie-checkbox-group/playwright-lit.config.ts, packages/components/pie-checkbox-group/src/index.ts, packages/components/pie-checkbox-group/test/accessibility/pie-checkbox-group.spec.ts, packages/components/pie-checkbox-group/test/component/pie-checkbox-group.spec.ts, packages/components/pie-checkbox-group/test/helpers/page-object/selectors.ts, packages/components/pie-checkbox-group/test/visual/pie-checkbox-group.spec.ts, packages/components/pie-checkbox-group/turbo.json
Refactor the pie-checkbox-group to use `@playwright/test`
---
=> refactor(pie-checkbox-group): DSW-2372 tests to use `@playwright/test`

.changeset/thin-donkeys-argue.md, packages/components/pie-radio-group/package.json, packages/components/pie-radio/package.json
- Moves `pie-radio` and `pie-radio-group` to `beta`
---
| Aperture PR            | [N/A](#) |
| NextJS 14 deployment   | [N/A](#) |
| Nuxt 3 deployment      | [N/A](#) |
| Vanilla deployment     | [N/A](#) |
=> chore(pie-radio-group): DSW-2512 move to beta

apps/pie-storybook/utilities/index.ts, packages/tools/pie-icons-webc/test/visual/pie-icons-webc.spec.ts
fixes the CI of https://github.com/justeattakeaway/pie/actions/runs/13140674137/job/36666902477?pr=2185
---
- [-] NA If there are visual test updates, I have reviewed them.
- [-] NA If there are visual test updates, I have reviewed them.
=> fix(pie-monorepo): DSW-000 fix Version Packages PR linting ci 

.changeset/serious-beans-scream.md, packages/components/pie-notification/src/notification.scss, yarn.lock
- Use the correct colour token for pie-notification to avoid it simply falling back to the page's default.
---
| Aperture PR            | [🔗](https://github.com/justeattakeaway/pie-aperture/pull/248) |
| NextJS 14 deployment   | [🔗](https://pr248-aperture-nextjs-app-v14.pie.design/components/notification) |
| Nuxt 3 deployment      | [🔗](https://pr248-aperture-nuxt-app.pie.design/components/notification) |
| Vanilla deployment     | [🔗](https://pr248-aperture-vanilla-app.pie.design/components/notifica …
=> cosmetic(pie-notification): PEW-89 use colour token for notification text

.github/workflows/update-icons.yml
- add env var for GH token in the workflow for updating icons
--- …
=> fix(pie-monorepo): DSW-000 add env var for GH token

packages/tools/pie-icons/bin/create-changeset.mjs, packages/tools/pie-icons/bin/update-icons.mjs
- updates `pie-docs` snapshots when the update-icons automation is used
--- …
=> fix(pie-icons): DSW-000 ensure to update pie-docs snapshots when updating icons

packages/components/pie-modal/turbo.json
- Updated `pie-modal` `turbo.json` to support new testing framework.
- [-] I have reviewed …
=> fix(pie-modal): DSW-000 updated turbo json

.github/workflows/update-icons.yml
- pass TURBO_TOKEN env var in the `update-icons` workflow
--- …
=> fix(pie-monorepo): DSW-000 pass TURBO_TOKEN env var

.github/actions/setup-playwright/action.yml
- Should fix an error about deprecation warning of `actions/cache` version we were using.
- [-] If a changeset file has been created, I have tested these changes in [PIE Aperture]
- …
=> chore(pie-monorepo): DSW-000 update actions/cache

package.json, packages/tools/pie-monorepo-utils/changeset-snapshot/utils.js
=> fix(pie-monorepo): DSW-000 update snapit command

.github/PULL_REQUEST_TEMPLATE/docs_template.md, .github/PULL_REQUEST_TEMPLATE/new_component_template.md
Updated PR checklists with tracker checks
=> docs(pie-monorepo): DSW-000 updating PR checklist with tracker checks

.changeset/dirty-games-chew.md, packages/components/pie-cookie-banner/cdn.vite.config.js
Update the build step to bundle *everything* for CDN consumers of the cookie banner
=> chore(pie-cookie-banner): DSW-2679 update vite config to bundle all cdn deps

.changeset/hungry-zoos-press.md, .changeset/old-cameras-shop.md, .changeset/plenty-dolphins-sneeze.md, .github/workflows/changeset-release.yml, packages/components/README.md, packages/components/pie-cookie-banner/package.json, packages/tools/pie-css/package.json, packages/tools/pie-monorepo-utils/pie-cdn/publish-to-cdn.js, packages/tools/pie-monorepo-utils/utils/find-monorepo-root.js
>[!NOTE]
>I did try to write tests for this, but have run into issues with mocking, especially the calls to `aws` cli. I've done a fair amount of manual testing, but there may be issues to address with how the script is invoked by GHA.
---
"@justeattakeaway/pie-monorepo-utils": minor
---
[Updated] - cdn publishing functionality to handle multiple packages
---
"@justeattakeaway/pie-cookie-banner": minor
"@justeattakeaway/pie-css": minor
---
[Added] - `pieMetadata` properties for cdn publishing
---
- [-] …
=> feat(pie-monorepo): DSW-2679 add mechanism to upload multiple components to CDN

.github/pull_request_template.md
- Added a checklist check (missed from previous PR review update)
=> docs(pie-monorepo): DSW-000 updating PR checklist with tracker check

.changeset/unlucky-cobras-wait.md, packages/tools/generator-pie-component/README.md
- updated the generator readme to include how to export sub-components
- [-] If a changeset file has been created, I have tested these changes in [PIE Aperture]
(https://github.com/justeattakeaway/pie-aperture/) using the `/test-aperture` command.
--- …
=> fix(generator-pie-component): DSW-000 update readme to include how to export sub components

.changeset/beige-onions-scream.md, packages/components/pie-select/package.json
Promote component status to beta
=> chore(pie-select): DSW-2776 promote to beta status

.changeset/fast-buses-flash.md, .github/workflows/amplify-deploy.yml, .github/workflows/changeset-release.yml, .github/workflows/ci.yml, apps/pie-storybook/README.md, apps/pie-storybook/package.json, configs/pie-components-config/playwright-native-config.js, packages/components/README.md, packages/tools/pie-monorepo-utils/__tests__/changeset-snapshot/create-and-publish.spec.js, yarn.lock
[Fixed] - Security patch to add scope to pie-storybook pkg
---
=> fix(pie-storybook): DSW-3025 security patch to add scope to pie-storybook pkg

.changeset/funny-melons-walk.md
Updates the scope of an existing changeset file to fix the build in `main`
=> fix(pie-monorepo): DSW-000 update changeset file scope

.changeset/eighty-foxes-punch.md, apps/pie-storybook/stories/icons.stories.ts, apps/pie-storybook/stories/pie-assistive-text.stories.ts, apps/pie-storybook/stories/pie-breadcrumb.stories.ts, apps/pie-storybook/stories/pie-button.stories.ts, apps/pie-storybook/stories/pie-card.stories.ts, apps/pie-storybook/stories/pie-checkbox-group.stories.ts, apps/pie-storybook/stories/pie-checkbox.stories.ts, apps/pie-storybook/stories/pie-chip.stories.ts, apps/pie-storybook/stories/pie-cookie-banner.stories.ts, apps/pie-storybook/stories/pie-divider.stories.ts, apps/pie-storybook/stories/pie-form-label.stories.ts, apps/pie-storybook/stories/pie-icon-button.stories.ts, apps/pie-storybook/stories/pie-link.stories.ts, apps/pie-storybook/stories/pie-list.stories.ts, apps/pie-storybook/stories/pie-lottie-player.stories.ts, apps/pie-storybook/stories/pie-modal.stories.ts, apps/pie-storybook/stories/pie-notification.stories.ts, apps/pie-storybook/stories/pie-radio-group.stories.ts, apps/pie-storybook/stories/pie-radio.stories.ts, apps/pie-storybook/stories/pie-select.stories.ts, apps/pie-storybook/stories/pie-spinner.stories.ts, apps/pie-storybook/stories/pie-switch.stories.ts, apps/pie-storybook/stories/pie-tag.stories.ts, apps/pie-storybook/stories/pie-text-input.stories.ts, apps/pie-storybook/stories/pie-textarea.stories.ts, apps/pie-storybook/stories/pie-thumbnail.stories.ts, apps/pie-storybook/stories/pie-toast-provider.stories.ts, apps/pie-storybook/stories/pie-toast.stories.ts, packages/tools/generator-pie-component/src/app/templates/pie-placeholder.__stories__.ts
- Moves components into a 'Components' section in Storybook
---
| Aperture PR            | [N/A](#) |
| NextJS 14 deployment   | [N/A](#) |
| Nuxt 3 deployment      | [N/A](#) |
| Vanilla deployment     | [N/A](#) |
=> feat(pie-storybook): DSW-2994 new components section

.changeset/eighty-fishes-dress.md, apps/pie-docs/src/components/assistive-text/code/code.md, apps/pie-docs/src/components/button/code/code.md, apps/pie-docs/src/components/card/code/code.md, apps/pie-docs/src/components/checkbox-group/code/code.md, apps/pie-docs/src/components/checkbox/code/code.md, apps/pie-docs/src/components/chip/code/code.md, apps/pie-docs/src/components/divider/code/code.md, apps/pie-docs/src/components/icon-button/code/code.md, apps/pie-docs/src/components/link/code/code.md, apps/pie-docs/src/components/modal/code/code.md, apps/pie-docs/src/components/notification/code/code.md, apps/pie-docs/src/components/radio-group/code/code.md, apps/pie-docs/src/components/radio/code/code.md, apps/pie-docs/src/components/select-input/code/code.md, apps/pie-docs/src/components/switch/code/code.md, apps/pie-docs/src/components/tag/code/code.md, apps/pie-docs/src/components/text-input/code/code.md, apps/pie-docs/src/components/textarea/code/code.md, apps/pie-docs/src/components/thumbnail/code/code.md, apps/pie-docs/src/components/toast/code/code.md, apps/pie-docs/src/components/toast/toast-provider/code.md, apps/pie-docs/src/patterns/cookie-banner/code/code.md
- Fixes the storybook links for all component code pages
=> fix(pie-docs): DSW-2996 fix broken Storybook links

.changeset/eighty-doors-sin.md, packages/components/pie-switch/package.json
[Changed] - set @justeattakeaway/pie-wrapper-react as dev dependency
---
=> fix(pie-switch): DSW-3081 set dependency as dev dependency

.changeset/fifty-melons-grab.md, apps/pie-storybook/stories/contribution/testing/aperture-integration-tests.mdx, apps/pie-storybook/stories/contribution/testing/testing-overview.mdx, yarn.lock
-  Aperture integration testing page
https://pr2429-storybook.pie.design/?path=/docs/contribution-testing-aperture-integration-tests--docs
---
[-] N/A I have verified that all acceptance criteria for this ticket have been completed.
[-] N/A I have reviewed the Aperture changes (if added)
[-] N/A If there are visual test updates, I have reviewed them.
[-] N/A I have verified that all acceptance criteria for this ticket have been completed.
[-] N/A I have reviewed the Aperture changes (if added)
[-] N/A If there are visual test updates, I have reviewed them.
=> feat(pie-storybook): DSW-3002 add integration testing docs to sb

.changeset/nasty-zoos-retire.md, packages/components/pie-assistive-text/package.json, packages/components/pie-breadcrumb/package.json, packages/components/pie-button/package.json, packages/components/pie-card/package.json, packages/components/pie-checkbox-group/package.json, packages/components/pie-checkbox/package.json, packages/components/pie-chip/package.json, packages/components/pie-cookie-banner/package.json, packages/components/pie-divider/package.json, packages/components/pie-form-label/package.json, packages/components/pie-icon-button/package.json, packages/components/pie-link/package.json, packages/components/pie-lottie-player/package.json, packages/components/pie-modal/package.json, packages/components/pie-notification/package.json, packages/components/pie-radio-group/package.json, packages/components/pie-radio/package.json, packages/components/pie-select/package.json, packages/components/pie-spinner/package.json, packages/components/pie-switch/package.json, packages/components/pie-tag/package.json, packages/components/pie-text-input/package.json, packages/components/pie-textarea/package.json, packages/components/pie-thumbnail/package.json, packages/components/pie-toast-provider/package.json, packages/components/pie-toast/package.json
Points to storybook for all component package.json files
=> feat(pie-monorepo): DSW-3106 point homepages to storybook

.changeset/tough-pears-refuse.md, apps/pie-storybook/.storybook/preview.ts, apps/pie-storybook/stories/introduction/typescript-usage.mdx
- Adds a new TS usage guide to Storybook
=> feat(pie-storybook): DSW-3138 add ts usage guide

.changeset/slimy-rings-burn.md, apps/pie-storybook/stories/contribution/overview.mdx
- mention #help-designsystem in the contribution guide
=> feat(pie-storybook): DSW-3138 mention #help-designsystem channel for PRs

.changeset/calm-panthers-relate.md, .changeset/clean-doors-travel.md, packages/components/pie-text-input/README.md, packages/components/pie-textarea/README.md
- adds a small pitfalls section to text-input and textarea
=> feat(pie-storybook): DSW-3051 input value pitfalls section to readmes

.gitignore
Updates gitignore to correctly ignore vite config timestamp files
=> fix(pie-monorepo): DSW-000 Update vite.config.ts.timestamp .gitignore

apps/pie-docs/package.json, apps/pie-docs/playwright-browsers.config.ts, apps/pie-docs/playwright-visual.config.ts
- Moved `playwright-visual.config.ts` and `playwright-browsers.config.ts` from the monorepo root to `apps/pie-docs`
- Updated routing for specified files
---
- [-] I …
=> test(pie-docs): DSW-3266 Moved playwright config from root to pie-docs

.changeset/early-hounds-draw.md, .changeset/twelve-spies-joke.md, .changeset/warm-hornets-turn.md, apps/pie-storybook/stories/testing/icons.test.stories.ts, packages/tools/pie-icons-configs/configs.ts, packages/tools/pie-icons-webc/PieIconComponent.ts, packages/tools/pie-icons-webc/build.js, packages/tools/pie-icons-webc/test/component/icon-webc.spec.js
- [Fixed] class prop behaviour to ensure base classes are never removed
- [Fixed] size prop behaviour and failed test for large icons
- [Added] story for testing custom classes
---
- [-] If there are …
=> fix(pie-icons-webc): DSW-3175 ensure custom classes don't override base classe

.changeset/fresh-nails-think.md, apps/pie-docs/src/assets/styles/components/_scrollToTop.scss, apps/pie-docs/src/assets/styles/components/_toggle.scss, apps/pie-storybook/stories/introduction/design-tokens-cookbook.mdx, packages/components/pie-card/src/card.scss, packages/components/pie-modal/src/modal.scss, packages/components/pie-toast/src/toast.scss
- Updated components to use the new set of elevation tokens.
---
- [-] I …
=> feat(pie-monorepo): DSW-3285 update components to use new elevation tokens

.github/workflows/amplify-deploy.yml, .github/workflows/ci.yml, .github/workflows/example-apps-ci.yml
- Minor fixes to permissions
---
- [-] If there …
=> ci(pie-monorepo): DSW-3267 updated fix for ci files

.changeset/yellow-pears-play.md, .github/workflows/changeset-snapshot.yml, .github/workflows/ci.yml, .github/workflows/dangerjs-checks.yml, .github/workflows/example-apps-ci.yml, .github/workflows/test-aperture.yml, .github/workflows/update-icons.yml, package.json, yarn.lock
---
---
[Updated] - Volta config for Node 22 support
>[!NOTE]
> Also removed 16.x / 18.x from engines since we currently have no CI that runs against it.
---
=> chore(pie-monorepo): DSW-2789 add support for Node 22

.changeset/great-bears-perform.md, apps/pie-docs/src/componentStatusData.js
- Fix links to Snacks components
---
=> fix(pie-docs): DSW-2848 fix links to Snacks components

.changeset/clean-swans-repeat.md, .changeset/sour-olives-cover.md, apps/pie-storybook/stories/pie-select.stories.ts, apps/pie-storybook/stories/testing/pie-select.test.stories.ts, packages/components/pie-select/README.md, packages/components/pie-select/src/defs.ts, packages/components/pie-select/src/index.ts, packages/components/pie-select/test/component/pie-select.spec.ts
=> feat(pie-select): DSW-3351 add value property

.changeset/silver-papayas-kick.md, packages/components/pie-select/src/index.ts
---
| Aperture PR            | [🔗](https://github.com/justeattakeaway/pie-aperture/pull/331) |
=> feat(pie-select): DSW-3351 fix onChange event

.github/workflows/ci.yml, apps/pie-docs/package.json
- Added Percy zip env variable to zip up percy runs and stop percy runs on main failing
---
| Task                   | Link …
=> fix(pie-docs): DSW-3430 updated with Percy env variable to zip percy runs
