apps/pie-microsite/CHANGELOG.md
apps/pie-microsite/package.json
apps/pie-microsite/src/_11ty/shortcodes/contentPageImage.js
apps/pie-microsite/src/assets/styles/components/_contentPage.scss
apps/pie-microsite/src/content/pages/foundations/colour/overview.md

v1.16.2
*September 22, 2022*
- Use lists rather than captions for some colour images
- figcaption lists (not needed)

pie-microsite@v1.16.2 - remove figcaption lists

---

CHANGELOG.md
package.json
packages/tools/pie-icons/.eslintrc.json
packages/tools/pie-icons/CHANGELOG.md
packages/tools/pie-icons/bin/build-icons-json.js
packages/tools/pie-icons/bin/build-icons-object.js
packages/tools/pie-icons/bin/get-svgs.js
packages/tools/pie-icons/bin/process-svg.js
packages/tools/pie-icons/bin/process-svgs.js
packages/tools/pie-icons/package.json
packages/tools/pie-icons/src/__tests__/__snapshots__/replace.test.js.snap
packages/tools/pie-icons/src/__tests__/replace.test.js
turbo.json
yarn.lock

- ESLint fix NPM Script
- `"tag": "beta"` property added to `package.json`.
- ESLint fixes across JS files
- Moved common `devDependencies` like Babel, ESLint and Jest out of package to mono-repo root.

pie-icons@v2.0.0-beta.1 – Updating pie-icons with ESLint and devdependency tidy up

---

packages/tools/pie-icons/CHANGELOG.md
packages/tools/pie-icons/package.json
packages/tools/pie-icons/src/icon.js

- Updating icon classname modifier to be camelcase (i.e. `c-pieIcon--About` > `c-pieIcon--about`)

pie-icons@v2.0.0-beta.2 - Updating icon classname to be camelCase

---

.github/workflows/build.yml
CHANGELOG.md
package.json

v1.16.1
*October 13, 2022*
### Changed
- add more granular config to the GitHub actions file for running on pushes to main and PRs

@v1.16.1 - Update github actions config

---

apps/pie-microsite/CHANGELOG.md
apps/pie-microsite/package.json
apps/pie-microsite/src/assets/styles/components/_tabs.scss

v1.21.0
*November 21, 2022*
- Unwanted horizontal page scrolling caused by left margin on page tabs
- Overlap/conflict between page tags and page content toggles caused by z-index

PIE microsite @v1.21.0 - css fixes

---

.gitignore
CHANGELOG.md
packages/tools/pie-icons-vue/CHANGELOG.md
packages/tools/pie-icons-vue/package.json

- `.gitignore` dist folder exemption causing dist output not to be published. Have modified to be the same specificity as package `files` setting.

pie-icons-vue@2.0.0-beta.1 – Fixing dist output of module

---

CHANGELOG.md
package.json
yarn.lock

v1.21.2
*January 16, 2022*
- Issue with incorrect `chromedriver` version on GitHub Actions.

pie@1.21.2 - Fix Chromedriver on CI

---

apps/pie-microsite/CHANGELOG.md
apps/pie-microsite/package.json
apps/pie-microsite/src/_11ty/shortcodes/tokensTable/index.js
apps/pie-microsite/src/__tests__/_11ty/shortcodes/__snapshots__/tokensTable.test.js.snap
apps/pie-microsite/src/__tests__/_11ty/shortcodes/tokensTable.test.js
apps/pie-microsite/src/assets/styles/components/_tokensTable.scss
apps/pie-microsite/src/content/pages/foundations/typography/tokens/global.md
apps/pie-microsite/src/tokenCategories.json
apps/pie-microsite/src/tokensMetadata.json

🎶 
- `CPMono` font hasn't been added yet 
- Font sizes tokens on designs are numerical but they are alphabetical in the pie tokens package
- `$style-strikethrough` token isn't shipped in the package so I ignored it for now

pie-microsite@v1.36.0 Typography Page - List and group global tokens on global page

---

packages/tools/pie-stylelint-config/README.md

adds the npm badge to the readme - I don't think this warrants a version change nor changeset

pie-styleint-config - npm badge in readme

---

apps/pie-microsite/CHANGELOG.md
apps/pie-microsite/package.json
apps/pie-microsite/src/content/pages/foundations/radius/tokens/alias.md
apps/pie-microsite/src/content/pages/foundations/radius/tokens/global.md

v1.42.1
*January 20, 2023*
- Punctuation in Radius Global and Alias copy from `:` to `.`

pie-microsite@v1.42.1 - updated punctuation in radius alias and global sections

---

apps/pie-microsite/.eleventy.js
apps/pie-microsite/CHANGELOG.md
apps/pie-microsite/package.json
apps/pie-microsite/src/_11ty/filters/markdown.js
apps/pie-microsite/src/_11ty/index.js
apps/pie-microsite/src/_11ty/libraries/index.js
apps/pie-microsite/src/content/pages/foundations/design-tokens/updates-and-maintenance.md
apps/pie-microsite/src/utilities/markdown.js
yarn.lock

adds [markdown-it-attrs ](https://github.com/arve0/markdown-it-attrs) as a dev package to support opening markdown links in a new tab when needed. 
📓 currently we only need to open links in a new tab when the link requires authentication, for example, Okta to adhere to [WCAG 2.0](https://www.w3.org/TR/WCAG20-TECHS/) guidelines.
📓 to open a link in a new tab, we need to add {target="_blank"} at the end of the markdown element. such as `[google](https://www.google.com) {target="_blank"}`
📓 please check out [11ty docs](https://www.11ty.dev/docs/languages/markdown/#add-your-own-plugins) for a walkthrough of how to modify a library instance.

pie-microsite@v1.44.0 - add support for opening markdown links in a new tab

---

apps/pie-microsite/CHANGELOG.md
apps/pie-microsite/package.json
apps/pie-microsite/src/assets/styles/components/_contentPage.scss

- H2 wide & narrow sizes to be inline with the new design sizes.

v1.46.0 - Fixes h2 sizes for narrow and wide devices.

---

.editorconfig
CHANGELOG.md

- `.editorconfig` updated – matches old mono-repo settings now, which matches up with our current linting rulesets

root@v1.23.0 – editorconfig update

---

packages/tools/pie-icons/package.json
yarn.lock

Super trivial update to the clean script, to make it work properly with turborepo. Also, removes the dependency at this package level, as not needed (it's in the root dependencies)

#trivial – Tidying up rimraf in pie-icons

---

.github/workflows/build.yml
CHANGELOG.md
package.json

v1.25.1
*Febuary 3, 2022*
- Issue with dist's not being available to changesets release job.

pie-monorepo - Fix release CI workflow

---

.github/workflows/build.yml
.github/workflows/remove-preview-deploy.yml

This PR:
- Fixes a type for the `main` storybook deploy.
- Ensures Storybook previews get deleted after merging.

Ensure Storybook previews are removed after merge + Fix property name in GHA config

---

.changeset/famous-chairs-perform.md
apps/pie-microsite/src/_includes/nav.njk
package.json
yarn.lock

[Changed] use `help-circle` icon for `Support` section of nav

pie-microsite: change support icon

---

.changeset/selfish-items-lie.md
CHANGELOG.md
apps/pie-docs/package.json
package.json
turbo.json
yarn.lock

**pie-monorepo**
v1.27.1
*Febuary 21, 2022*
- Fixed issue where `pie-docs#build:dev` wasn't included in `turbo.json`.
- Fixed issue where linting would fail if dependency `dist` wasn't present.

pie-docs - Fix issue with build:dev command not executing tasks on dependencies

---

.changeset/fluffy-drinks-hang.md
apps/pie-docs/src/assets/styles/base/_layout.scss
apps/pie-docs/src/assets/styles/plugins/_prism.scss

- [Fixed] - code block responsive width for wide screens
📓  By default, grid/flex items don't shrink below their content size, thus, code snippets won't have the correct ratio without specifying `min-width: 0`.

Fix code block responsive width for wide screens

---

CHANGELOG.md
package.json
yarn.lock

- Updated `pie-icons` dependency to latest beta version (in root)

chore(pie-monorepo): updating pie-icons package version

---

.changeset/config.json
.changeset/wet-laws-prove.md
.github/workflows/build.yml

[ Fixed ] - Revert back to old changeset / GHA config to prevent CI not running on Release commits

revert(pie-monorepo): revert changes to GHA config

---

.changeset/big-cooks-fry.md
apps/pie-docs/src/assets/styles/components/_footer.scss

[Fixed] Footer styles based on designers feedback
[Fixed] The small divider between the two logos to be 1px wide
[Fixed] The PIE logo to be 24px high, and centre aligned to the other logo.
[Fixed] The space above and below the links to be 64px, not 56px.
[Fixed] The dot between ‘Privacy policy’ and ‘Updated on…’ to be centre aligned horizontally

cosmetic(pie-docs): update footer styles based on designers feedback

---

.changeset/curly-dots-sort.md
apps/pie-docs/.eleventy.js
apps/pie-docs/package.json
apps/pie-docs/src/_includes/head.njk
apps/pie-docs/src/_includes/scripts.njk
apps/pie-docs/src/assets/styles/_dependencies.scss
yarn.lock

[Changed] - Use f-cookie-banner package for cookie banner

fix(pie-docs): ensure cookie-banner css loads before js executes

---

.changeset/chilly-paws-pretend.md
apps/examples/wc-vue3/package.json
apps/pie-storybook/package.json
packages/components/pie-button/package.json
packages/tools/pie-eslint-config/package.json
packages/tools/pie-icons-react/package.json
packages/tools/pie-icons-vue/package.json
packages/tools/pie-icons/package.json
packages/tools/pie-stylelint-config/package.json

- Add missing Volta settings to package.json
Volta doesn't inherit the settings from the monorepo root as some might expect. `cd`ing into any directory will lead node to use whatever version is installed in the developer environment, and this can easily lead to confusion and random outcomes.
References:
- [GH issue](https://github.com/volta-cli/volta/issues/862)
- [GH issue](https://github.com/volta-cli/volta/issues/378)
- [Volta documentation](https://docs.volta.sh/advanced/workspaces)
`pie-docs` wasn't updated because it already has the necessary settings.

fix(pie-monorepo): add missing Volta settings

---

.changeset/great-pants-rule.md
apps/pie-docs/src/assets/styles/components/_nav.scss

[Fixed] Sticky nav on wider viewports now sticky again

fix(pie-docs): sticky nav on wider viewports now sticky again

---

.changeset/clean-kids-give.md
packages/components/pie-button/src/index.ts
yarn.lock

[Removed] Global declare statement
There seems to be a problem with using a global declare statement within the example projects (nuxt3). From what I can see this isn't necessary for LitElement based custom element to work. It looks like the declaration is mainly for TypeScript to provide strong typing with regards to the dom API.

fix(pie-button): remove global declare statement

---

.changeset/tame-years-change.md
.github/actions/amplify-deploy/action.yml
.github/workflows/build.yml

Some of the steps are running against the main branch (or merge queues) when they shouldn't be, this should fix that.
Now that we've disabled merge queues this isn't essential, but it's a good safeguard against any other potential issues in future.
e.g., https://github.com/justeattakeaway/pie/actions/runs/4676632186/jobs/8283287361

ci(pie-monorepo): Only run PR deployments against PRs

---

.changeset/polite-cooks-double.md
apps/examples/wc-next10/package.json
apps/examples/wc-next13/package.json
apps/examples/wc-nuxt2/package.json
apps/examples/wc-nuxt3/package.json
apps/examples/wc-react18/package.json
apps/examples/wc-vue3/package.json

This PR fixes a bug where example apps were trying to be versioned

fix(pie-monorepo): correct existing changeset files to no longer version example apps

---

.changeset/eighty-emus-think.md
.github/actions/changeset-release/action.yml
.github/workflows/ci.yml

[Fixed] - Issue where tokens weren't being provided to Changeset composite action

ci(pie-monorepo): pass environment variables to changeset action

---

.github/workflows/changeset-release.yml

This PR adds the GITHUB_TOKEN to the changeset dispatchable workflow action

ci(pie-monorepo): add environment variable to changeset action

---

.changeset/shiny-buses-rush.md
.changeset/tender-bears-accept.md
packages/components/pie-button/src/index.ts
yarn.lock

- [Updated] Yarn module resolution for `@lit-labs/ssr-dom-shim` to use the latest version (1.1.1)
- [Removed] the custom decorator and uses the native `customElement` decorator instead
More about the context can be found in this [GH discussion](https://github.com/justeattakeaway/pie/discussions/408).
The Lit team released [version 1.1.1](https://github.com/lit/lit/blob/main/packages/labs/ssr-dom-shim/CHANGELOG.md#111) of `@lit-labs/ssr-dom-shim` that solves the issue with Next.js dev mode reloads.
The new package was tested with both Next.js 10 and 13 example apps.

Upgrade lit ssr dom shim

---

apps/examples/wc-nuxt3/README.md
apps/examples/wc-nuxt3/nuxt.config.ts
apps/examples/wc-nuxt3/package.json
yarn.lock

feat(wc-nuxt3): setup nuxt-ssr-lit
refactor(wc-nuxt3): update nuxt.config.ts and remove unnecessary settings
feat(wc-nuxt3): update README
The beta version of `nuxt-ssr-lit` had an issue with hydration and the maintainers released version `1.5.1` to fix it.
A warning about "Multiple versions of Lit" is being printed and according to the maintainers, it is harmless.
https://github.com/prashantpalikhe/nuxt-ssr-lit/issues/73

Render button via ssr in nuxt

---

.changeset/fuzzy-stingrays-protect.md
.changeset/shy-onions-turn.md
renovate.json

[Added] - New renovate groupings for example apps
[Fixed] - Invalid JSON in `renovate.json`

chore(pie-monorepo): correct renovate config & add example app groupings

---

.changeset/funny-maps-jump.md
.github/actions/setup-repo/action.yml
.github/workflows/ci.yml

[Fixed] - Issue where deploys would fail when 'push' events occured to `feature-*` / `beta-*` branches due to no associated pull-request number. These branches will now only be triggered once a PR has been created.
[Fixed] - Issue where `--cached` flag was passed in scenarios where cache wasn't available, causing CI to fail.
This will fix the issue seen in this PR, where deploy-* jobs fail, but only for the `push` events - https://github.com/justeattakeaway/pie/pull/450

fix(pie-monorepo): fixed bug with 'push' events CI trigger for certain branches cause fail + remove cache flag

---

.github/actions/setup-repo/action.yml

This PR fixes an issue around our usage on node_modules caching. It should prevent issues like this occuring:
https://github.com/justeattakeaway/pie/actions/runs/5000836437/jobs/8958758557
Turns out we don't actually need to use `actions/cache`, as the `setup-node` action handles caching for us under-the-hood - https://github.com/actions/setup-node#caching-global-packages-data

fix(pie-monorepo): Remove duplicate caching functionality to prevent issues with node_modules cache

---

.changeset/five-dolphins-relax.md
packages/tools/pie-icons/bin/build-icons-json.js
packages/tools/pie-icons/bin/build-icons-object.js
packages/tools/pie-icons/package.json
yarn.lock

[Changed] - Replaced `html-minifier` by `html-minifier-terser`
[Changed] - Updated icons object builder function and script to async

refactor(pie-icons): fix vulnerability in pie-icons

---

.changeset/tidy-carrots-shave.md
apps/pie-docs/src/_includes/layouts/toggle-page-layout.njk
apps/pie-docs/test/system/colour-toggle.spec.js

- Test added for testing the page toggle on the Pie Docs colour page.

test(pie-docs): added colour page toggle system test

---

.changeset/good-drinks-compare.md
.changeset/new-actors-wave.md
.changeset/polite-waves-buy.md
.changeset/strong-doors-walk.md
apps/pie-storybook/stories/pie-modal.stories.ts
packages/components/pie-modal/package.json
packages/components/pie-modal/playwright-lit-visual.config.ts
packages/components/pie-modal/playwright-lit.config.ts
packages/components/pie-modal/playwright/index.html
packages/components/pie-modal/playwright/index.ts
packages/components/pie-modal/src/index.ts
packages/components/pie-modal/src/modal.scss
packages/components/pie-modal/test/visual/pie-modal.spec.ts
packages/tools/pie-wrapper-react/custom-elements.json
yarn.lock

- [Added] - Basic styling for modal default state
- [Added] - Modal heading added to component
- [Updated] - Added modal component to storybook file
[Changed] - Custom Element Definitions
[Updated] - yarn.lock

feat(pie-modal): add basic styling for the opened state

---

.changeset/cold-maps-breathe.md
.changeset/itchy-donkeys-grab.md
.changeset/long-yaks-grin.md
.changeset/mighty-moles-argue.md
.changeset/nasty-houses-perform.md
.changeset/shaggy-lions-work.md
apps/pie-storybook/stories/pie-modal.stories.ts
packages/components/pie-button/src/index.ts
packages/components/pie-icon-button/src/index.ts
packages/components/pie-modal/README.md
packages/components/pie-modal/package.json
packages/components/pie-modal/src/defs.ts
packages/components/pie-modal/src/index.ts
packages/components/pie-modal/test/component/pie-modal.spec.ts
packages/components/pie-modal/test/visual/pie-modal.spec.ts
packages/components/pie-webc-core/src/decorators/index.ts
packages/components/pie-webc-core/src/decorators/required-property.ts
packages/components/pie-webc-core/src/decorators/valid-property-values.ts
packages/components/pie-webc-core/src/test-helpers/components/web-component-test-wrapper/WebComponentTestWrapper.ts
packages/tools/pie-wrapper-react/custom-elements.json
packages/tools/pie-wrapper-react/scripts/add-react-wrapper.js

- adds heading props to modal
- modifies the react-wrapper script to take care of cases where the custom element is defined via a variable

feat(pie-modal): Modal heading props

---

.changeset/odd-cups-sin.md
.github/workflows/changeset-release.yml

- New PIE bot user created an added to justeattakeaway org - https://github.com/pie-design-system-bot
- Personal access token created that allows for pushing to repos / execution of GHA workflows
- new `CHANGESET_TOKEN` secret has been added to the repo with the value of this PAT.
- Token has been added to the changeset GHA yaml

ci(pie-monorepo): add new token to allow pie-design-system-bot to create changeset PRs

---

.changeset/moody-fans-pump.md
packages/tools/pie-icons-configs/__tests__/configs-react.test.js
packages/tools/pie-icons-configs/configs-react.js

Removes `class` attr application for React icon components

fix(pie-icons-configs): removes class attr application for react icons

---

.github/workflows/changeset-release.yml

ci(pie-monorepo): prevent changesets from using GHA user

---

.changeset/wet-hounds-trade.md
packages/tools/pie-icons-configs/__tests__/configs.test.js
packages/tools/pie-icons-configs/configs.js

[Fixed]: removes a console error if `iconSize` prop is not passed
[Changed]: in case of invalid `iconSize` being passed to large icons now the size defaults to the `largeIconSizeDefault`

fix(pie-icons-configs): removes a console error if iconSize prop is not passed

---

.changeset/mean-singers-camp.md
packages/components/pie-icon-button/src/index.ts
packages/components/pie-modal/src/index.ts

---
"@justeattakeaway/pie-icon-button": minor
"@justeattakeaway/pie-modal": minor
---
[Changed] - Ensure component implements it's props interface

feat(pie-monorepo): ensure modal and icon-button implement interfaces

---

.changeset/nice-ladybugs-provide.md
packages/tools/pie-wrapper-react/__tests__/__snapshots__/wrapper.test.js.snap
packages/tools/pie-wrapper-react/__tests__/mocks/mock-custom-elements.json
packages/tools/pie-wrapper-react/scripts/add-react-wrapper.js
yarn.lock

Ensures that React callbacks use camel case for events emitted from our lit components:
Before:
```javascript
import * as React from 'react';
import { createComponent, EventName } from '@lit-labs/react';
import { PieModal as PieModalReact } from './index';
export const PieModal = createComponent({
displayName: 'PieModal',
elementClass: PieModalReact,
react: React,
tagName: 'pie-modal',
events: {
onpiemodalopen: 'pie-modal-open' as EventName<CustomEvent>, // when the modal is opened.
onpiemodalclose: 'pie-modal-close' as EventName<CustomEvent>, // when the modal is closed.
},
});
```
After:
```javascript
import * as React from 'react';
import { createComponent, EventName } from '@lit-labs/react';
import { PieModal as PieModalReact } from './index';
export const PieModal = createComponent({ …
```

feat(pie-wrapper-react): use camelcase for react event callbacks

---

.changeset/great-baboons-rush.md
.changeset/stale-parents-attack.md
.changeset/warm-numbers-judge.md
apps/examples/wc-vanilla/index.html
apps/examples/wc-vanilla/main.js
apps/examples/wc-vanilla/package.json
apps/pie-storybook/.storybook/preview.js
apps/pie-storybook/stories/pie-button.stories.ts
packages/components/pie-button/README.md
packages/components/pie-button/src/button.scss
packages/components/pie-button/src/index.ts
packages/components/pie-button/test/visual/pie-button.spec.ts
packages/tools/pie-wrapper-react/custom-elements.json
yarn.lock

- [Added] - Slots for leading and trailing icons
- [Added] - expanded controls info and pie-button updated to include icon slots
- [Added] - Leading & Trailing Button Icons and Icon Button examples

feat(pie-button): DSW-867 added slots for leading and trailing icons

---

.changeset/quick-horses-visit.md
apps/examples/wc-vanilla/index.html
apps/examples/wc-vanilla/main.js
apps/examples/wc-vanilla/package.json
packages/components/pie-modal/README.md
packages/components/pie-modal/package.json
packages/components/pie-modal/src/index.ts
packages/components/pie-modal/src/modal.scss
yarn.lock

- [Changed] - updated Modal component dependencies adding the `dialog-polyfill` package
- [Changed] - updated Modal component to use `dialog-polyfill`
- [Changed] - updated Modal documentation regarding the legacy browser support for Dialog element and polyfill usage and limitations
- [Changed] - vanilla example app for testing Modal with `dialog-polyfill`
Behaviours noticed during legacy testing:
- I used the browser mentioned in the ticket (Safari 14) and Firefox 97 (which doesn't support the Dialog element)
- Safari 14
- ✅ The polyfill itself works with Safari 14
- ❌ Pie Web Components styles are not displayed
- ❌ Without the polyfill, the Modal component content is rendered as a regular div, regardless of the `isOpen` attribute value, likely due the lack of styles
- Firefox 97
- ✅ The …

feat(pie-modal): DSW-1013 implement dialog polyfill

---

.changeset/bright-students-doubt.md
packages/components/pie-icon-button/package.json
yarn.lock

---
"@justeattakeaway/pie-icon-button": patch
---
[Fixed] - Corrected the following peerDependency:
```js
"peerDependencies": {
"@justeat/pie-design-tokens": "5.4.0"
},
```

fix(pie-icon-button): DSW-000 fixed issue with incorrect peerDependency name

---

.changeset/sweet-sheep-tap.md
packages/tools/pie-icons-vue/package.json
packages/tools/pie-icons-vue/rollup.config.js
packages/tools/pie-icons-vue/scripts/build.js
yarn.lock

My hypothesis is that the reason that `pie-icons` could not be resolved by the `pie-icons-vue` build is that rollup was told to only resolve `pie-icons-configs`.
I think this turned out to be true but it revealed another issue where `@vue/babel-helper-vue-jsx-merge-props` was not being loaded properly, so I needed to add the commonjs plugin.

chore(pie-icons-vue): DSW-1109 update rollup node resolutions

---

.changeset/silver-snails-draw.md
packages/tools/pie-icons/nodemon.json
packages/tools/pie-icons/package.json
yarn.lock

I was looking at #738 but it appears that the package is no longer used, so this PR tries to remove it.
- Remove `nodemon` script and dependency from pie-icons.

chore(pie-icons): DSW-000 remove nodemon script and dependency

---

.changeset/warm-pillows-own.md
packages/components/pie-button/test/visual/pie-button.spec.ts
packages/components/pie-divider/test/visual/pie-divider.spec.ts
packages/components/pie-icon-button/test/visual/pie-icon-button.spec.ts
packages/components/pie-webc-testing/src/percy/breakpoints.ts
yarn.lock

- [Added] - Percy Breakpoints to `pie-webc-testing` for limiting percy screenshot widths for use across multiple components.
- Screenshots limited to 375px.
- [Updated] - `pie-button`, `pie-icon-button` & `pie-divider` to use the new percy widths.

refactor(pie-button): DSW-1108 updated button, icon-button and divider

---

.changeset/calm-cobras-behave.md
apps/pie-storybook/package.json
apps/pie-storybook/stories/pie-link.stories.ts
packages/components/pie-divider/test/visual/pie-divider.spec.ts
packages/components/pie-link/README.md
packages/components/pie-link/src/defs.ts
packages/components/pie-link/src/index.ts
packages/components/pie-link/src/link.scss
packages/components/pie-link/test/component/pie-link.spec.ts
packages/components/pie-link/test/visual/pie-link.spec.ts
yarn.lock

[Added] - allow the link component to behave like a button
[Changed] - fixed visual tests for the link and divider components

feat(pie-link): DSW-1121 allow the link component to behave like a button

---

.changeset/empty-panthers-drop.md
apps/examples/wc-vanilla/package.json
package.json
packages/tools/pie-css/test/css/__snapshots__/css.spec.ts.snap
packages/tools/pie-icons-vue/.eslintrc.cjs
packages/tools/pie-icons-vue/scripts/build.js
yarn.lock

---
---
[Changed] - Upgraded `@justeat/pie-design-tokens` to `5.7.0`
**Notes:**
- I have verified the Next13 example app displays the design tokens correctly in Safari 14 on Mac OS and iOS using Browserstack.
- I have verified the modal in Storybook displays the design tokens correctly in Safari 14 on Mac OS and iOS using Browserstack.

chore(pie-monorepo): DSW-1110 update ds token package

---

.changeset/soft-seas-fetch.md
apps/pie-docs/package.json
yarn.lock

---
"pie-docs": major
---
[Changed] - Upgraded site to use `@11ty/eleventy` `v2.0.1` from `v1.0.2`. Also upgraded `eleventy-sass` to `v2.2.3` from `v2.2.1`

chore(pie-docs): DSW-1146 upgrade to 11ty 2.0.1

---

.changeset/young-snakes-begin.md
packages/components/pie-toggle-switch/src/toggle-switch.scss

fix(pie-toggle-switch): DSW-1196 safari bug issue

---

.changeset/curvy-terms-move.md
packages/components/pie-toggle-switch/src/toggle-switch.scss

[Fixed] Safari ios checkbox disabled visual issue

fix(pie-toggle-switch): DSW-1220 safari ios bug

---

packages/components/pie-button/test/accessibility/pie-button.spec.ts
packages/components/pie-button/test/visual/pie-button.spec.ts
packages/components/pie-card-container/test/visual/pie-card-container.spec.ts
packages/components/pie-divider/test/visual/pie-divider.spec.ts
packages/components/pie-icon-button/test/accessibility/pie-icon-button.spec.ts
packages/components/pie-icon-button/test/visual/pie-icon-button.spec.ts
packages/components/pie-link/test/visual/pie-link.spec.ts

as suggested here https://github.com/justeattakeaway/pie/pull/789#discussion_r1321694061, this PR renames the variants visual test titles to be a bit clearer and more consistent with other tests

chore(pie-monorepo): DSW-000 rename some visual tests title

---

.changeset/stale-beans-fix.md
apps/pie-storybook/stories/pie-form-label.stories.ts
packages/components/pie-form-label/README.md
packages/components/pie-form-label/src/defs.ts
packages/components/pie-form-label/src/form-label.scss
packages/components/pie-form-label/src/index.ts
packages/components/pie-form-label/test/component/pie-form-label.spec.ts
packages/components/pie-form-label/test/visual/pie-form-label.spec.ts
packages/components/pie-link/src/index.ts

[Added] - Build the Pie Form Label component
📓 as a result of [ this discussion](https://github.com/justeattakeaway/pie/discussions/782), we agreed to pass the optional / trailing labels as named slots to the component, however, that didn't seem to be doable during implementation as slots aren't moved in the DOM tree, but they're rendered as if they were children of the `<slot>` so when the parent element (label) is a flex container, optional and trailing slots won't be considered 'flex children' as they aren't a direct child. 
Besides, marking them as a slot will require end users to set the html element alongside the slot such as 
```
<pie-form-label>
Label
<span slot='trailing'> X out X </span>
</pie-form-label>
```
and that's going to be tricky to validate since we only want to accept …

feat(pie-form-label): DSW-1188 build form label

---

.changeset/clean-deers-arrive.md
apps/pie-storybook/stories/pie-link.stories.ts
packages/components/pie-link/README.md
packages/components/pie-link/src/defs.ts
packages/components/pie-link/src/index.ts
packages/components/pie-link/src/link.scss

[Fixed] - When the `isStandalone` prop is `false`, underline can only be default and not reversed.
[Fixed] - When the `isStandalone` prop is `false`, icon's cannot be shown.
[Fixed] - When the link is small, the icon doesn't seem to be vertically centered with the text.
[Fixed] - The spacing between the text and icon should be fixed / hugging the length of the text.
[Fixed] - focus styles for the link component

fix(pie-link): DSW-1185 address design reviews

---

.changeset/nervous-yaks-run.md
packages/components/pie-button/package.json
packages/components/pie-card-container/package.json
packages/components/pie-cookie-banner/package.json
packages/components/pie-divider/package.json
packages/components/pie-form-label/package.json
packages/components/pie-icon-button/package.json
packages/components/pie-link/package.json
packages/components/pie-modal/package.json
packages/components/pie-toggle-switch/package.json
packages/tools/generator-pie-component/src/app/templates/__package__.json

---
"@justeattakeaway/pie-card-container": minor
"@justeattakeaway/generator-pie-component": minor
"@justeattakeaway/pie-cookie-banner": minor
"@justeattakeaway/pie-toggle-switch": minor
"@justeattakeaway/pie-icon-button": minor
"@justeattakeaway/pie-form-label": minor
"@justeattakeaway/pie-divider": minor
"@justeattakeaway/pie-modal": minor
"@justeattakeaway/pie-link": minor
---
[Added] - set sideEffects package.json property to correctly communicate to bundlers such as webpack that js files in the component dist folders contain side effects and should therefore not be treeshaken when the entire library is imported. [Reference](https://cube.dev/blog/how-to-build-tree-shakeable-javascript-libraries)

chore(pie-monorepo): DSW-1280 add sideEffects property to components

---

apps/pie-storybook/stories/pie-modal.stories.ts

This PR was supposed to be larger, containing a fix for the padding around the modal content, but I realised that I fixed that already as part of #878.
---
- Update default body text for modal on storybook

docs(pie-modal): DSW-1317 update default modal body text on storybook

---

.changeset/ten-lies-punch.md
.github/workflows/ci.yml

- Add Github action settings to ensure the required CI jobs are passing
A new check will appear under the name "Build / check-all-jobs".
In the [workflow view](https://github.com/justeattakeaway/pie/actions/runs/6507309654) you can see all the jobs "check-all-jobs" relies on:
In case some job fails, it will represented as usual:
Also, as an example the workflow of failed pipeline might look like this:
This is only an additional check and there's no need to change how we work.

ci(pie-monorepo): DSW-1193 ensure all GH checks are passing

---

.github/workflows/changeset-release.yml

I didn't realise the `.outputs` was needed on the line where we grab the array of published packages. Sorry!
Link to changeset docs - https://github.com/changesets/action#outputs

ci(pie-monorepo): DSW-000 add outputs keyword to prevent changesets job failure when pushing Slack notification.

---

.github/workflows/changeset-release.yml

- Minor update to change changesets published step from a boolean to a string.

ci(pie-monorepo): DSW-000 update changesets release logic from boolean to a string

---

.changeset/spotty-plums-doubt.md
.github/workflows/changeset-release.yml

[Fixed] - Issue with Slack notification functionality where $PRIORITIZED_BLOCKS had no value assigned, causing invalid JSON when $BLOCKS array was assigned a value

ci(pie-monorepo): DSW-000 fixed issue with Slack notifier

---

.changeset/rich-sloths-judge.md
packages/tools/pie-icons-webc/package.json
yarn.lock

Move two test package dependencies from dependencies to dev dependencies - otherwise this causes consumers to need to install these two packages when using the icons

chore(pie-icons-webc): DSW-000 move test package deps to devdependencies

---

renovate.json

Currently renovate does not correctly add a ticket number to its PRs which means that we have to manually add it once it has been approved prior to merging. This can be a little tedious especially if the PR rebases and you need to change it again.
- Trying to use [`commitMessageAction`](https://docs.renovatebot.com/configuration-options/#commitmessageaction) to shoehorn the ticket number into the commit message.
- All of the PRs that I have seen have used "update" as the action so hard-coding that as part of the new action _shouldn't_ be an issue.
- I'm removing DSW-000 from the other templates because they never seem to work.

ci(pie-monorepo): DSW-000 use commitMessageAction to provide default ticket number

---

.changeset/strong-pens-wave.md
packages/components/pie-modal/src/modal.scss

- Modal heading should be 20px for narrow and 24px for wide. Also updated line heights.

cosmetic(pie-modal): DSW-000 use narrow/wide font sizes for the modal heading

---

.changeset/silver-ties-warn.md
packages/components/pie-modal/src/modal.scss

[Changed] - The shadow effect for the unpinned footer spans the whole container. ( the shadow effect for this use case isn't 100% aligned with the design, but it's the closest I managed to get to with the current implementation and was approved by @RLumleyJET)
[Removed] - Heading shadow 
[Fixed] - The footer should sit at the bottom of a fullscreen modal, regardless of the content height

fix(pie-modal): DSW-1322 Address modal footer design feedback

---

.changeset/twenty-cats-burn.md
packages/components/pie-form-label/src/form-label.scss
packages/components/pie-form-label/src/index.ts

[Fixed] - If the optional wraps onto a second line and there is no label to the left, there should be no additional padding.
[Fixed] - When in RTL, the optional tag should be positioned to the left of the label.

fix(pie-form-label): DSW-1274 address form label design feedback

---

.changeset/five-buses-sing.md
apps/pie-storybook/package.json
apps/pie-storybook/stories/pie-cookie-banner.stories.ts
packages/components/pie-cookie-banner/README.md
packages/components/pie-cookie-banner/src/defs.ts
yarn.lock

- [Changed] - `hasPrimaryActionsOnly` prop description to be less tied to the copy
- [Removed] - explicit dependencies on the storybook actions and docs addons because these come through the essentials package

chore(pie-storybook): DSW-1397 remove extraneous storybook dependencies

---

.changeset/pink-guests-teach.md
apps/pie-docs/src/_11ty/shortcodes/notification.js
apps/pie-docs/src/assets/styles/base/_layout.scss

As part of the components template designs, we need to support the following variant for the notification shortcut, thus, this PR extends the notification shortcut to support that. We also need the shortcut to support a custom icon passed to it so the interface is extended to do so as well

feat(pie-docs): DSW-000 add a neutral variant to the notification shortcut

---

.changeset/polite-taxis-check.md
apps/pie-docs/src/_11ty/shortcodes/contentPageImage.js
apps/pie-docs/src/__tests__/_11ty/shortcodes/__snapshots__/contentPageImage.test.js.snap
apps/pie-docs/src/__tests__/_11ty/shortcodes/__snapshots__/shortcode-utilities.test.js.snap
apps/pie-docs/src/assets/styles/components/_contentImage.scss

as part of the components templet work, we need to extend the `contentImage` shortcut to support different variants as shown in the screenshot

feat(pie-docs): DSW-1325 support a variant prop to contentImage

---

.changeset/few-suns-grin.md
apps/pie-docs/src/assets/styles/components/_usage.scss

As part of the components template work, we need to ensure the usage items shortcut should have the same height. 
Before:
After:

fix(pie-docs): DSW-1325 usage cards should have the same height

---

apps/examples/wc-next10/README.md
apps/examples/wc-next10/package.json
apps/examples/wc-next13/README.md
apps/examples/wc-next13/package.json
apps/examples/wc-react17/package.json
apps/examples/wc-react18/README.md
apps/examples/wc-react18/package.json
configs/pie-components-config/vite.config.js
packages/components/pie-button/README.md
packages/components/pie-card/README.md
packages/components/pie-cookie-banner/README.md
packages/components/pie-divider/README.md
packages/components/pie-form-label/README.md
packages/components/pie-icon-button/README.md
packages/components/pie-link/README.md
packages/components/pie-modal/README.md
packages/components/pie-notification/README.md
packages/components/pie-spinner/README.md
packages/components/pie-switch/README.md
packages/tools/generator-pie-component/src/app/templates/README.md
packages/tools/pie-wrapper-react/CHANGELOG.md
packages/tools/pie-wrapper-react/__tests__/__snapshots__/wrapper.test.js.snap
packages/tools/pie-wrapper-react/package.json
yarn.lock

- This PR marks "@lit/react" as an external package so it isn't bundled as part of the react wrappers. 
- This is required to fix (DSW-1376) where the react-wrappers of our component will fall back to their default values when JS is disabled resulting in a rehydration error. 
- The lit team also suggested the package should be marked as `external` to avoid other edge cases. 
- the change was tested in all of our react examples and should be good to go 🥳 
the lit team also suggested to not bundle the package as that will just create duplications for consumers.

fix(pie-monorepo): DSW-1376 mark "lit/react" as an external dependency 

---

.changeset/short-coins-serve.md
packages/components/pie-modal/src/modal.scss

currently, our modal doesn't display fully in Safari when `isFooterPinned` is set to false. 
This PR ensures that the modal renders the correct height while maintaining the current behavior of `isFooterPinned` and `isFullWidthBelowMid`

fix(pie-modal): DSW-000 modal content doesn't span the whole height

---

.changeset/twelve-candles-carry.md
apps/pie-docs/package.json

---
"pie-docs": patch
---
[Fixed] - Issue where `dev` script wasn't running on port 8080, causing the browser tests to fail.

fix(pie-docs): DSW-000 fix issue where dev server was running on incorrect port for browser tests

---

.changeset/five-grapes-live.md
apps/pie-storybook/stories/pie-spinner.stories.ts
packages/components/pie-button/src/index.ts
packages/components/pie-icon-button/src/index.ts
packages/components/pie-modal/src/index.ts
packages/components/pie-spinner/README.md
packages/components/pie-spinner/src/defs.ts
packages/components/pie-spinner/src/index.ts
packages/components/pie-spinner/src/spinner.scss

- Refactors the sizes prop values to match the button size values as requested by design for better consistency

fix(pie-spinner): DSW-000 rename sizes to match new design specs

---

.changeset/blue-carrots-wonder.md
.changeset/silly-cherries-move.md
apps/pie-storybook/stories/pie-link.stories.ts
packages/components/pie-switch/package.json
yarn.lock

- Fixes an issue where `pie-link` stories don't display icons when the page is refreshed. 
- a type error because of an invalid value passed to "underline"

fix(pie-storybook): DSW-000 ensure icons are bundled as part of link story

---

.changeset/tough-icons-vanish.md
apps/pie-storybook/stories/pie-divider.stories.ts

when we introduced this [commit](https://github.com/justeattakeaway/pie/pull/976/commits/29b408a8feb8de81ed0bba0d480ff134e0187363#diff-49fec5f1927f17f5b3e531ef05b7fba91112ff6a58a49fa4571ad48f3d43317aR90) to center the content of our stories, the divider became invisible as the parent of the inner stories is set to flex / center and that will shrink children to only span their content, and the divider didn't have a width value set / content to span

fix(pie-monorepo): DSW-000 fix divider stories

---

.changeset/quick-ears-exist.md
packages/tools/pie-icons-react/package.json
yarn.lock

- the latest [release](https://github.com/justeattakeaway/pie/releases/tag/%40justeattakeaway%2Fpie-icons-react%404.12.0) of `pie-icons-react` throws the following error when it's installed.
this is happening because `@justeattakeaway/pie-icons-configs` is a private package and should be listed as a dev dependency. 
- the fix is tested in pie-aperture locally (pr to follow) 🟢

fix(pie-icons-react): DSW-000 list build dependencies as dev deps

---

.changeset/honest-icons-rest.md
packages/components/pie-icon-button/src/index.ts
packages/components/pie-icon-button/test/visual/pie-icon-button.spec.ts

- requested as part of the component design review
variant=primary, isLoading, disabled (before):
After:

fix(pie-icon-button): DSW-000 use the spinner brand variant for the primary disabled state

---

.changeset/three-turkeys-sit.md
packages/components/pie-button/src/index.ts

- Requested per the button design review, all variants of the disabled button should use the secondary spinner except for ghost-inverse
*isLoading + disabled for all variants except ghost-inverse:*
isLoading + disabled for ghost-inverse:
- Visual tests were already added, so Percy is expected to fail.

fix(pie-button): DSW-000 fix disabled button spinners

---

.github/actions/amplify-teardown/action.yml
.github/workflows/closed.yml

Composite Actions don't have access to secrets; this is by design to make actions more secure.
To solve this issue, we simply need to pass the secret as an input to the action.

ci(pie-monorepo): DSW-000 fix env var in teardown action

---

.github/actions/amplify-teardown/action.yml

The last PR works as expected, however only the deploys were getting deleted, not the environment:
As per the docs, this will remove the env from the 'environments' tab:
https://github.com/strumwolf/delete-deployment-environment?tab=readme-ov-file#deactives-and-removes-deployment-environment-also-from-settings

ci(pie-monorepo): DSW-000 remove 'ref' property so environment gets deleted, rather than last deploy

---

.changeset/blue-mayflies-collect.md
configs/pie-components-config/package.json

This PR fixes an issue where the `pie-components-config` dependency couldn't be resolved for components that are generated outside of the pie-monorepo

fix(pie-components-config): DSW-000 fixed generator for components outside of pie-monorepo

---

.changeset/dirty-tables-press.md
.changeset/late-fishes-pretend.md
apps/pie-docs/src/components/switch/code/props.json
apps/pie-storybook/stories/pie-switch.stories.ts
packages/components/pie-cookie-banner/src/defs.ts
packages/components/pie-cookie-banner/src/index.ts
packages/components/pie-cookie-banner/test/component/pie-cookie-banner.spec.ts
packages/components/pie-switch/src/defs.ts
packages/components/pie-switch/src/index.ts
packages/components/pie-switch/src/switch.scss
packages/components/pie-switch/test/component/pie-switch.spec.ts
packages/components/pie-switch/test/visual/pie-switch.spec.ts
packages/tools/pie-wrapper-react/scripts/add-react-wrapper.js
yarn.lock

- [Changed] - Rename `isDisabled` pie-switch prop to `disabled` to align with native attribute
- [Fixed] - Trailing whitespace linting error from react wrapper

feat(pie-switch): DSW-1571 rename isDisabled prop to disabled

---

packages/components/pie-switch/test/component/pie-switch.spec.ts

There was an issue where the switch component wasn't being announced properly by NVDA. I discovered that the styling changes that @jamieomaguire and I made as part of #1103 fixed the issue, so this PR adds a test which covers the key part of those changes to prevent a regression.

test(pie-switch): DSW-1556 add test to prevent accessibility regression

---

.changeset/chilled-snails-cry.md
.changeset/fluffy-dolls-flash.md
.changeset/hip-files-wash.md
packages/components/pie-button/src/button.scss
packages/components/pie-icon-button/src/iconButton.scss
packages/tools/pie-icons-webc/build.js

---
"@justeattakeaway/pie-icons-webc": patch
---
[Changed] - `--btn-icon-size` and `--btn-icon-display` to `--icon-display-override` and `--icon-size-override` variable for display, width and height icon styles for `:host svg`
---
"@justeattakeaway/pie-button": patch
---
[Changed] - `--btn-icon-display` and `--btn-icon-size` to `--icon-display-override` and `--icon-size-override` variables
---
"@justeattakeaway/pie-icon-button": patch
---
[Changed] - `--btn-icon-display` and `--btn-icon-size` to `--icon-display-override` and `--icon-size-override` variables

fix(pie-icons-webc): DSW-1539 icon display and size override variables

---

.changeset/tender-mugs-lie.md
packages/components/pie-button/test/visual/pie-button.spec.ts

[Fixed] - Button mount re-added to visual tests to fix visual regressions

fix(pie-button): DSW-1606 button mount readded to visual tests

---

.changeset/clever-rabbits-compete.md
.changeset/itchy-poets-dress.md
packages/components/pie-button/src/index.ts
packages/components/pie-webc-core/src/functions/defineCustomElement.ts
packages/components/pie-webc-core/src/mixins/formControl/formControlMixin.ts
packages/components/pie-webc-core/src/mixins/types/LitElementMixin.ts
yarn.lock

Tested in PIE Aperture NextJS (with SSR) and Vanilla JS
---
---
[Changed] - Use new FormControlMixin in `pie-button` and remove old form association code
---
"@justeattakeaway/pie-webc-core": minor
---
[Changed] - Updated LitElement imports where it is only used as a type to include the 'type' keyword (fixes a TS error in some consumers)

refactor(pie-button): DSW-1582 use FormControlMixin for form logic

---

.changeset/modern-bees-visit.md
.changeset/tricky-walls-perform.md
apps/pie-storybook/stories/pie-input.stories.ts
packages/components/pie-input/custom-elements.json
packages/components/pie-input/src/defs.ts
packages/components/pie-input/src/index.ts
packages/components/pie-input/test/component/pie-input.spec.ts

- PIE Aperture NextJS (SSR Enabled)
- Vanilla form integration is coming in a separate PR
---
---
[Added] - `value` property to input component
---
---
[Added] - value prop to pie-input stories

feat(pie-input): DSW-1582 add a value property to input

---

.changeset/cool-planets-battle.md
.changeset/early-hotels-travel.md
.changeset/itchy-owls-smile.md
apps/pie-storybook/stories/pie-input.stories.ts
packages/components/README.md
packages/components/pie-input/custom-elements.json
packages/components/pie-input/src/index.ts
packages/components/pie-input/test/component/pie-input.spec.ts
packages/components/pie-switch/custom-elements.json
packages/components/pie-switch/src/index.ts
packages/components/pie-webc-core/src/functions/index.ts
packages/components/pie-webc-core/src/functions/wrapNativeEvent.ts

---
"@justeattakeaway/pie-switch": minor
---
[Changed] - Use new event wrapper function to standardise the change event structure
---
---
[Added] - Readme section for how we use events in our web components
---
"@justeattakeaway/pie-webc-core": minor
---
[Added] - new wrapNativeEvent function to standardise how we structure custom versions of native browser events such as 'change'

feat(pie-input): DSW-1582 dispatch change event

---

.changeset/seven-buckets-compare.md
dangerfile.js

[Fixed] - Danger reporting when no categories added to changeset

fix(pie-monorepo): DSW-000 fix dangerjs reporting when no changeset category

---

.changeset/old-flowers-relax.md
packages/components/pie-form-label/test/visual/pie-form-label.spec.ts
packages/components/pie-input/test/visual/pie-input.spec.ts
packages/components/pie-link/test/visual/pie-link.spec.ts
packages/components/pie-switch/test/visual/pie-switch.spec.ts

- Updated - `pie-switch`, `pie-input`, `pie-form-label`, `pie-link` - Visual tests only take screenshots in 375px

test(pie-switch): DSW-1576 updated visual tests to only take screenshots at 375px

---

.changeset/many-plums-rhyme.md
.changeset/short-terms-tell.md
apps/pie-storybook/stories/pie-input.stories.ts
packages/components/pie-input/src/defs.ts
packages/components/pie-input/src/index.ts
packages/components/pie-input/test/component/pie-input.spec.ts

---
---
[Added] - Provide a `formResetCallback` method to enable HTML form resets

feat(pie-input): DSW-0 enable HTML form resets

---

.changeset/unlucky-oranges-divide.md
packages/components/pie-input/src/defs.ts
packages/components/pie-input/src/index.ts
packages/components/pie-input/test/component/pie-input.spec.ts

---
---
[Added] - Make the `value` property required and default to an empty string

fix(pie-input): DSW-0 required input value

---

.changeset/shy-snails-dress.md
packages/components/pie-modal/src/index.ts

-  Fixes `pie-modal` positioning in Safari when the page is scrolled down 
Unlike other browsers, some versions of Safari behave differently when the `body` element style is set with `overflow: hidden;`. Most browsers will scroll the content to the top, Safari doesn't.
On Chrome, when the document is scrolled, `window.scrollY` will have some positive value. When the scroll is locked and `overflow` is `hidden`, the `window.scrollY` will be `0`.
Scrolling back to the top, as it happens in every other browser,  provided the expected results for both `pie-modal` and `pie-cookie-banner` when used with a Safari browser.
- open the URL with the test page using updated versions of `pie-modal` and `pie-cookie-banner`:  https://pr55-aperture-nextjs-app.pie.design/modal-cookie-banner
- scroll to the …

fix(pie-modal): DSW-1671 Fix for modal rendering outside the viewport when scroll is locked

---

.changeset/angry-socks-cough.md
.changeset/dull-bags-count.md
.changeset/many-planes-joke.md
apps/pie-docs/src/assets/styles/components/_componentDetailsTable.scss
apps/pie-docs/src/assets/styles/components/_componentStatusTable.scss
apps/pie-docs/src/assets/styles/components/_list.scss
apps/pie-docs/src/assets/styles/components/_nav.scss
apps/pie-docs/src/assets/styles/components/_resourceTable.scss
apps/pie-docs/src/assets/styles/plugins/_prism.scss
packages/components/pie-modal/src/modal.scss
packages/tools/stylelint-no-logical-props-shorthands/README.md
packages/tools/stylelint-no-logical-props-shorthands/__tests__/__snapshots__/plugin.test.js.snap
packages/tools/stylelint-no-logical-props-shorthands/__tests__/plugin.test.js
packages/tools/stylelint-no-logical-props-shorthands/index.js

[Added] - missing shorthands for logical properties (inset-block/inset-inline)
[Fixed] - plugin logic to raise errors only when logical properties shorthands are used with CSS variables
[Fixed] - README.md title
[Fixed] - reverted unnecessary CSS updates for logical properties
[Fixed] - reverted unnecessary CSS updates for logical properties

fix(stylelint-no-logical-props-shorthands): DSW-000 update logic and revert unnecessary changes in CSS

---

.changeset/wicked-pots-appear.md
apps/pie-storybook/stories/pie-input.stories.ts
packages/components/pie-input/README.md
packages/components/pie-input/src/index.ts
packages/components/pie-input/test/component/pie-input.spec.ts
yarn.lock

[Added] - Leading and Trailing content slots to pie-input component

feat(pie-input): DSW-1588 add leading and trailing content slots

---

.changeset/sour-gorillas-marry.md
apps/pie-docs/src/foundations/iconography/overview.md
yarn.lock

During another work I noticed that a few image size values were incorrect on iconography overview page.
---
"pie-docs": patch
---
[Changed] - updates some image sizes for iconography foundation page.

docs(pie-docs): DSW-0 updates some images width on iconography page

---

package.json
yarn.lock

This PR fixes an issue where a missing dependency was causing the `test:coverage` script to fail.

fix(pie-monorepo): DSW-000 issue where vitest dep was causing test:coverage to fail

---

.changeset/forty-bats-float.md
packages/components/pie-assistive-text/src/index.ts

This PR fixes an issue with pie-assistive-text where the conditional rendering implementation for icons was causing slots not to render in SPA applications. Moving the conditional logic to the template seems to fix the issue.
I've tested my changes in Aperture using the snapshot, and the slot now renders as expected across all aperture apps 👍🏼 
No visual tests to review

chore(pie-assistive-text): DSW-1773 update conditional rendering

---

.changeset/four-cherries-tease.md

Only the changeset entry to release pie-icons-react, pie-icons-vue and pie-icons-webc after the last pie-icons update

release(pie-icons-react): DSW-1750 package release after the last pie-icons update

---

.changeset/eighty-suits-explode.md
apps/pie-docs/src/engineers/getting-started/structure.md
yarn.lock

Adds a correct link to https://webc.pie.design/ for the web components storybook page. Was previously a url going to a 404 page.

fix(pie-docs): DSW-000 add correct storybook link to webc page link

---

.changeset/long-peaches-learn.md
package.json
yarn.lock

---
"pie-monorepo": patch
---
[Changed] - Reverted `turbo` back to `1.10.16`. Our current caused a bug that resulted in the `check-change-type` CI job not corretly detecting changes in the repo, resulting in deployments not being triggered.

revert(pie-monorepo): DSW-000 revert turbo update

---

.changeset/eighty-pears-sip.md
.changeset/new-mayflies-wait.md
apps/pie-storybook/stories/pie-input.stories.ts
packages/components/pie-input/README.md
packages/components/pie-input/src/defs.ts
packages/components/pie-input/src/index.ts
packages/components/pie-input/test/component/pie-input.spec.ts

Adds a new `size` property to `pie-input`. Styling will come in an upcoming ticket.
(Reviewed by @xander-marjoram)

feat(pie-input): DSW-1586 add size property to input component

---

.github/workflows/changeset-snapshot/test-aperture.js
.github/workflows/test-aperture.yml
yarn.lock

This is a small PR (that's still a WIP) that will allow me to more easily test CI triggers between PIE <> Aperture, given GHA can be quite tricky to run on forked repositories.
This PR simply duplicates the existing snapshot JS, and adds some additional code to fire an event to PIE Aperture.
I've also duplicated the `/snapit` action, but instead, using `/test-aperture` to test these changes without impacting existing functionality.
The goal of this PR is just to use it for testing purposes until we've proven it works, afterwhich, it'll be refactored to make better use of our existing code.
GHA workflows that're triggered via comments need to exist within `main` for security reasons, hence why I'm looking to merge this in a WIP state.
**End goal**
The end goal for this work, is to allow …

ci(pie-monorepo): DSW-1755 trigger aperture workflows via /test-aperture comment

---

.github/workflows/changeset-snapshot/test-aperture.js

I was accidentally using the wrong function to trigger the PIE aperture repo from PIE. This PR should address it!

chore(pie-monorepo): DSW-1755 use correct function to dispatch pie-aperture workflow

---

packages/components/pie-button/src/button.scss
packages/components/pie-chip/src/chip.scss
packages/components/pie-icon-button/src/iconButton.scss
packages/components/pie-tag/src/tag.scss
packages/tools/pie-icons-webc/build.js

Looks like `--icon-display-override` var is not needed anymore if we set display style on the host. I also noticed that for pie-chip `--icon-size-override` was not set to any value so I corrected it as well.

feat(pie-icons-webc): DSW-000 set height and width on icon hosts (follow up)

---

.changeset/ninety-boats-yawn.md
.gitignore
configs/pie-components-config/vite.config.js
package.json
packages/components/README.md
packages/components/pie-webc-core/README.md
packages/components/pie-webc-core/vite.config.js
packages/tools/pie-icons-webc/README.md
packages/tools/pie-icons-webc/vite.config.js
yarn.lock

Adds a rollup bundle visualiser that runs during the build of our components, webc, webc-core and webc-icons packages. In future we may want to limit this to only run locally and not during CI. However it seemed like it would involve adding more environment context to our build process which I think is probably out of scope for this change.

chore(pie-monorepo): DSW-1868 add bundle visualiser to build scripts

---

.changeset/light-hounds-serve.md
.changeset/neat-geckos-end.md
.changeset/twenty-buttons-fetch.md
apps/pie-docs/src/componentStatusData.js
packages/components/pie-chip/package.json
packages/components/pie-chip/src/chip.scss
packages/components/pie-tag/package.json
yarn.lock

- fixes a bug where the loading spinner is not centered correctly when `isDismissed` is true 
before: 
after:
- updates the status of the Tag and Chip components to `Beta`

fix(pie-chip): DSW-1912 loading state isn't centred correctly

---

.changeset/strong-chefs-doubt.md
.github/workflows/changeset-snapshot/test-aperture.js
.github/workflows/test-aperture.yml

This PR fixes an issue where the action wasn't working due to use of `env.` keyword instead of `secrets.` when accessing the GITHUB_TOKEN.

fix(pie-monorepo): DSW-000 Fix `repo_token` param from request-comment-branch action

---

.changeset/fresh-otters-remain.md
apps/pie-storybook/stories/pie-checkbox.stories.ts
packages/components/pie-checkbox/README.md
packages/components/pie-checkbox/src/defs.ts
packages/components/pie-checkbox/src/index.ts

---
"@justeattakeaway/pie-checkbox": minor
---
[Added] - aria property to support aria-label, aria-labeledby and aria-describedby attributes.
[Changed] - updated README to include component properties and events
Feature url: https://pr1440-storybook.pie.design/?path=/story/checkbox--default

feat(pie-checkbox): DSW-1574 checkbox aria property

---

.changeset/fair-pants-drive.md
.changeset/gorgeous-seals-teach.md
.changeset/shy-tigers-hang.md
.changeset/twelve-carpets-applaud.md
apps/pie-storybook/stories/pie-checkbox.stories.ts
packages/components/pie-checkbox/src/defs-react.ts
packages/components/pie-checkbox/src/defs.ts
packages/components/pie-checkbox/src/index.ts
packages/components/pie-checkbox/test/component/pie-checkbox.spec.ts
packages/components/pie-switch/src/index.ts
packages/components/pie-text-input/test/component/pie-text-input.spec.ts
packages/components/pie-webc-testing/src/helpers/form-helpers.ts

---
"@justeattakeaway/pie-checkbox": minor
---
[Added] - form support
---
"@justeattakeaway/pie-switch": patch
---
[Changed] - renames onChange to handleChange and makes it private
---
"@justeattakeaway/pie-webc-testing": minor
---
[Added] - test form helper setupFormDataExtraction and getFormDataObject functions
---
"@justeattakeaway/pie-text-input": patch
---
[Changed] - form helper test functions are moved to pie-webc-helpers
Aperture PR: https://github.com/justeattakeaway/pie-aperture/pull/133
**Note:** Reset form logic will be covered by a separate ticket

feat(pie-checkbox): DSW-1574 checkbox form integration

---

apps/pie-docs/src/components/button/code/code.md
apps/pie-docs/src/components/card/code/code.md
apps/pie-docs/src/components/chip/code/code.md
apps/pie-docs/src/components/divider/code/code.md
apps/pie-docs/src/components/icon-button/code/code.md
apps/pie-docs/src/components/link/code/code.md
apps/pie-docs/src/components/modal/code/code.md
apps/pie-docs/src/components/notification/code/code.md
apps/pie-docs/src/components/switch/code/code.md
apps/pie-docs/src/components/tag/code/code.md
apps/pie-docs/src/patterns/cookie-banner/code/code.md
packages/components/pie-assistive-text/README.md
packages/components/pie-button/README.md
packages/components/pie-card/README.md
packages/components/pie-checkbox/README.md
packages/components/pie-chip/README.md
packages/components/pie-cookie-banner/README.md
packages/components/pie-divider/README.md
packages/components/pie-form-label/README.md
packages/components/pie-icon-button/README.md
packages/components/pie-link/README.md
packages/components/pie-modal/README.md
packages/components/pie-notification/README.md
packages/components/pie-spinner/README.md
packages/components/pie-switch/README.md
packages/components/pie-tag/README.md
packages/components/pie-text-input/README.md
packages/components/pie-webc/README.md

- Replaced the yarn and npm installation code snippets with just the code needed so that the copy buttons work correctly
- Replace usage of `32px` with the design token `spacing-f` for Storybook iframe embeds

docs(pie-docs): DSW-000 shorten yarn and npm installation examples

---

.github/workflows/ossf-scorecard.yml

Add a GitHub Actions workflow to run an OSSF scorecard scan on the repository.
I was chatting to @siggerzz in Slack and this happened to come up in conversation, and I said I'd already added this to all our public .NET repositories, so would be trivial to copy-paste into PIE.

ci(pie-monorepo): DSW-000 Add OSSF Scorecard

---

.github/workflows/pr-title-linter.yml

Just prevents PR titles from being linted when the PR is in draft mode. This reduces unnecessary noise when opening PRs.

chore(pie-monorepo): DSW-000 do not lint draft PR titles

---

.changeset/curly-mirrors-cross.md
packages/components/pie-assistive-text/src/defs.ts
packages/components/pie-button/src/defs.ts
packages/components/pie-card/src/defs.ts
packages/components/pie-checkbox/src/defs.ts
packages/components/pie-chip/src/defs.ts
packages/components/pie-cookie-banner/src/defs.ts
packages/components/pie-divider/src/defs.ts
packages/components/pie-icon-button/src/defs.ts
packages/components/pie-link/src/defs.ts
packages/components/pie-modal/src/defs.ts
packages/components/pie-modal/test/visual/pie-modal.spec.ts
packages/components/pie-notification/src/defs.ts
packages/components/pie-spinner/src/defs.ts
packages/components/pie-switch/src/defs.ts
packages/components/pie-tag/src/defs.ts
packages/components/pie-text-input/src/defs.ts
packages/components/pie-textarea/src/defs.ts
packages/components/pie-webc-core/src/types/component-default-props-generic.ts

- Update `ComponentDefaultPropsGeneric` to default to all props requiring a default value.
- This can be overridden in the same way as before, by providing a union of keys.
- Some `DefaultProps` types have been updated to use `Omit` where this helps to simplify.

refactor(pie-webc-core): DSW-000 update default props generic helper type to include all props by default

---

.changeset/blue-dots-chew.md
apps/examples/wc-vanilla/main.js
apps/examples/wc-vanilla/package.json

Adds pie-webc integration to wc-vanilla examples app.
[PIE Docs Template](?expand=1&template=docs_template.md)
[New Web Component Template](?expand=1&template=new_component_template.md)
═══════════════════════════════════════════════════════════

feat(pie-monorepo): DSW-2056 integrate pie-webc package into wc-vanilla

---

.changeset/modern-melons-draw.md
packages/components/pie-button/src/button.scss
packages/components/pie-button/src/index.ts
packages/components/pie-button/test/component/pie-button.spec.ts
packages/tools/pie-css/scss/mixins/_buttonInteractiveStates.scss
packages/tools/pie-css/test/scss/unit/mixins/buttonInteractiveStates.spec.ts

- [Changed] - Styles now use classmap
- [Fixed] - Fixed background colour when button is in `xsmall` or `small` size and responsive mode is true, where the bg-color wasn't updating to orange as required

feat(pie-button): DSW-000 Changing styles to use classmap

---

.changeset/neat-cooks-pay.md
packages/components/pie-checkbox/src/checkbox.scss
packages/components/pie-checkbox/src/defs.ts
packages/components/pie-checkbox/src/index.ts
packages/components/pie-switch/src/index.ts
packages/components/pie-switch/src/switch.scss
packages/components/pie-webc-core/src/mixins/rtl/rtlMixin.ts

---
"@justeattakeaway/pie-checkbox": patch
"@justeattakeaway/pie-switch": patch
"@justeattakeaway/pie-webc": patch
---
[Changed] - isRtl attr changed to data-is-rtl

feat(pie-webc): DSW-2182 isRtl attr changed to data-is-rtl

---

.changeset/six-adults-dance.md
.github/workflows/changeset-snapshot/test-aperture.js
apps/pie-docs/turbo.json
apps/pie-storybook/turbo.json
package.json
packages/tools/pie-css/turbo.json
packages/tools/pie-icons-react/turbo.json
packages/tools/pie-icons-vue/turbo.json
packages/tools/pie-icons-webc/turbo.json
packages/tools/pie-icons/turbo.json
turbo.json
yarn.lock

---
---
[Updated] - turbo version bump to 2.0.9

chore(pie-monorepo): DSW-000 Update Turborepo

---

.github/workflows/changeset-snapshot/test-aperture.js
.github/workflows/ci.yml

Not sure why this originally passed in my PR, but fixes a bug with Turborepo v2 and the change detection job as seen here:
https://github.com/justeattakeaway/pie/actions/runs/10110816899/job/27961509677?pr=1630
While this PR won't trigger a deploy, I have tested the commands locally to ensure they work.

fix(pie-monorepo): DSW-000 Turborepo change detection

---

.github/workflows/changeset-snapshot/test-aperture.js
apps/examples/wc-next13/package.json
apps/examples/wc-react17/package.json
apps/examples/wc-react18/package.json

Not sure how our example apps were working in some cases in CI, but Turborepo V2 highlighted a bug in CI - https://github.com/justeattakeaway/pie/actions/runs/10111687451/job/27964247901

fix(example-apps): DSW-000 Update script names

---

.changeset/heavy-moles-appear.md
.changeset/hot-dingos-joke.md
.changeset/swift-emus-wonder.md
.changeset/two-lemons-appear.md
apps/pie-docs/src/components/assistive-text/code/props.json
apps/pie-storybook/stories/pie-checkbox.stories.ts
packages/components/pie-assistive-text/README.md
packages/components/pie-assistive-text/src/assistive-text.scss
packages/components/pie-assistive-text/src/defs.ts
packages/components/pie-assistive-text/src/index.ts
packages/components/pie-checkbox-group/README.md
packages/components/pie-checkbox-group/src/defs.ts
packages/components/pie-checkbox-group/src/index.ts
packages/components/pie-checkbox/src/index.ts

**Problem:** shadow DOM limitation for ARIA attributes binding + fieldset with checkboxes not announcing aria-describedby element text in VoiceOver and NVDA (known bug in screenreaders)
More info: https://www.matuzo.at/blog/2023/web-components-accessibility-faq/aria-references/
**Solution:** making PIE Assistive Text component optionally visually hidden to pass error information down to each Checkbox in Checkbox Group for assistive tech to have the error info while visually error will be shown only under Checkbox Group.
No visual changes to components introduced. PIE Docs Percy test shows a new prop added to PIE Assistive Text.
Reviewer 1 - @xander-marjoram 
Reviewer 2 - @jamieomaguire

feat(pie-checkbox-group): DSW-1937 a11y improvements

---

.changeset/early-spoons-grin.md
packages/components/pie-toast/package.json
packages/components/pie-toast/src/defs.ts
yarn.lock

fix(pie-toast): DSW-000 add missing package dependencies

---

.changeset/thirty-carrots-heal.md
apps/pie-docs/src/foundations/radius/radius.md
apps/pie-docs/src/foundations/spacing/spacing.md
apps/pie-docs/src/foundations/typography/typography.md
apps/pie-docs/test/accessibility/accessibility.spec.js

- Exclude `iframe` elements from accessibility tests
- Fix a conflict in the page ordering in the Foundations section (both Radius and Motion had `order: 5`)

test(pie-docs): DSW-000 exclude storybook previews from a11y testing

---

.changeset/red-mails-explain.md
.changeset/smart-horses-confess.md
.changeset/ten-actors-guess.md
apps/pie-docs/src/components/notification/code/props.json
apps/pie-storybook/stories/pie-checkbox-group.stories.ts
apps/pie-storybook/stories/pie-notification.stories.ts
apps/pie-storybook/stories/pie-text-input.stories.ts
packages/components/pie-notification/src/defs.ts
packages/components/pie-notification/src/index.ts
packages/components/pie-notification/test/component/pie-notification.spec.ts
packages/components/pie-notification/test/visual/pie-notification.spec.ts

---
"@justeattakeaway/pie-notification": patch
---
[Fixed] - make sure custom and default icons work as expected.
[Fixed] - make `isDismissible` false by default
[Fixed] - use storybook mapping to render different slot content

fix(pie-notification): DSW-000 make sure custom and default icons work as expected

---

.changeset/new-poets-love.md
packages/components/pie-modal/src/modal.scss

**[Added] - indent to `pie-modal` when footer isn't rendered**
**1. Large text Content**
**2. isLoading = true and footer is rendered**
**3. isLoading = true and footer isn't rendered**

fix(pie-modal): DSW-2213 add indent to pie-modal when footer isn't rendered

---

.changeset/perfect-pugs-speak.md
packages/components/pie-chip/src/chip.scss
packages/components/pie-chip/src/index.ts

- Switch from using custom HTML attributes to CSS `classmap` for styling the chip component

feat(pie-chip): DSW-2280 use classmap for styling

---

.changeset/nice-clocks-prove.md
.github/workflows/ci.yml
dangerfile.js
yarn.lock

- Automatically commit the updated `yarn.lock` file if its a Version Packages PR
- Fail a danger check if the `yarn.lock` is missing after dependency updates if it is NOT a Version Packages PR
Example auto-commit:
Example Danger message:

chore(pie-monorepo): DSW-000 auto updated lockfile and dangerjs check for missing lock file

---

.changeset/light-badgers-sparkle.md
.changeset/popular-eggs-fetch.md
apps/pie-storybook/stories/pie-textarea.stories.ts
packages/components/pie-textarea/src/defs.ts
packages/components/pie-textarea/src/index.ts
packages/components/pie-textarea/src/textarea.scss
packages/components/pie-textarea/test/component/pie-textarea.spec.ts
packages/components/pie-textarea/test/visual/pie-textarea.spec.ts

[Added] - `assistiveText` property, `status` property with the possible values `default`, `success` and `error`
[Added] - storybook controls for the `assistiveText` and `status` properties

feat(pie-textarea): DSW-2141 add assistive text and status properties

---

.changeset/eighty-cobras-serve.md
.changeset/rude-dolphins-lick.md
apps/pie-docs/src/components/tag/code/code.md
apps/pie-docs/src/components/tag/code/props.json
apps/pie-storybook/stories/pie-tag.stories.ts
packages/components/pie-tag/src/defs.ts
packages/components/pie-tag/src/index.ts
packages/components/pie-tag/src/tag.scss
packages/components/pie-tag/test/visual/pie-tag.spec.ts
yarn.lock

- [Changed] - Rename `isDimmed` prop to `disabled`
- [Added] - `isInteractive` prop which renders the tag as a button
- [Added] - Interactive styling
- ~I have added thorough tests where applicable (unit / component / visual)~
- I tried this but I don't think it's currently possible with our Playwright/Percy setup. It works locally but the state doesn't make it as far as Percy.

feat(pie-tag): DSW-2323 add `isInteractive` prop and rename `isDimmed` to `disabled`

---

.changeset/brave-stingrays-provide.md
.changeset/young-beers-arrive.md
apps/pie-docs/src/components/textarea/code/code.md
apps/pie-docs/src/components/textarea/code/events.json
apps/pie-docs/src/components/textarea/code/props.json
apps/pie-docs/test/snapshots/expected-routes.snapshot.json
apps/pie-storybook/stories/pie-text-input.stories.ts
apps/pie-storybook/stories/pie-textarea.stories.ts

**[Changed]** - `pie-textarea` `maxLength` prop description and fixed typo
**[Added]** - code page for `pie-textarea` component
**Feature url:**  https://pr1818-docs.pie.design/components/textarea/code/

docs(pie-textarea): DSW-2127 add textarea code page

---

.changeset/large-moose-travel.md
packages/components/pie-checkbox/src/checkbox.scss
packages/components/pie-checkbox/src/index.ts
packages/components/pie-checkbox/test/component/pie-checkbox.spec.ts

---
"@justeattakeaway/pie-checkbox": minor
---
[Changed] - use ClassMap for styling with CSS classes rather than data attributes

feat(pie-checkbox): DSW-2280 use classmap for styling

---

.changeset/thin-lizards-listen.md
packages/components/pie-button/test/visual/pie-button.spec.ts

- Updated Pie Button tests to split the variations up by size.
- Screenshots should increase from **11** to **47** in number
This is to resolve issues such as:
- Screenshotted variations being cropped due to too large of a screenshot
- Improve screenshot readability and reviewability.

test(pie-button): DSW-2226 Split PIE Button visual tests by sizes

---

.changeset/metal-crabs-develop.md
apps/pie-docs/src/components/card/code/props.json
apps/pie-storybook/stories/pie-card.stories.ts
packages/components/pie-card/src/card.scss
packages/components/pie-card/src/index.ts
packages/components/pie-card/test/component/pie-card.spec.ts

[Fixed] - Ensure the card is not interactive when `disabled` is passed

fix(pie-card): DSW-2425 ensure the card is not interactive when it is disabled

---

.changeset/old-eyes-itch.md
packages/components/pie-modal/src/index.ts
yarn.lock

**Validated in an internal application where the bug was first spotted - this seems to fix it!**
This PR updates the modal's `disconnectedCallback` lifecycle method to ensure any scroll locks applied to the page are properly removed. Previously, scroll locks were only removed when the modal was closed via user interaction.
While this worked for most use cases, it introduced an edge-case bug: when a modal was destroyed directly, the scroll lock remained on the page because the reference to the destroyed element was lost, making it impossible to remove the lock.
With this update, modals will now reliably clean up scroll locks upon destruction.
- Utilised `AbortController` to simplify the cleanup of `EventListeners`, reducing code complexity.
- Ensured that `EventListeners` attached to the …

fix(pie-modal): DSW-2322 prevent page lock when modal closed

---

.changeset/eleven-tigers-happen.md
.changeset/tricky-apes-think.md
packages/components/pie-modal/src/index.ts
packages/components/pie-modal/test/component/pie-modal.spec.ts
yarn.lock

- Prevents `Escape` key presses from closing the modal when `iDismissible` is set to false
- Applies the same protection against reactive changes to the `isDismissible` property
- Enables the previously skipped test that captured the bug
1. Go to the default Modal story in the Storybook preview deploy
2. Try pressing escape
3. The Modal should close
4. Now set the `isDismissible` control to `false`
5. Try pressing escape
6. The Modal should not close
7. Try various combinations to see if lifecycle changes affect the behaviour (they don't when I have tested but worth a second person checking)

fix(pie-modal): DSW-2218 stop esc closing modal (isDismissible=false)

---

.changeset/fluffy-pears-decide.md
packages/components/pie-tag/src/tag.scss

[Fixed] - hover and active state of brand-06 should use hover-02 and active-02 tokens

fix(pie-tag): DSW-2465 update active and hover tokens for brand-06

---

.changeset/sweet-seahorses-dream.md
packages/components/pie-textarea/src/index.ts
packages/components/pie-textarea/test/visual/pie-textarea.spec.ts

- Ensures that when the `value` property is updated programmatically (e.g., through a Storybook control), the text area resizes correctly, just as it would if a user were typing directly into the input.

fix(pie-textarea): DSW-2470 allow resize on programmatic value change

---

packages/components/pie-cookie-banner/package.json

- Just bumps the cookie banner version to `stable`

docs(pie-cookie-banner): DSW-000 bump version to stable

---

.changeset/tricky-ads-allow.md
packages/tools/stylelint-config-pie/index.js

- [Changed] - Add file extensions to rule imports
Fixes issue in native ESM environments, where without the prefix, it throws an error.

fix(stylelint-config-pie): DSW-000 add js extension to rule imports for ESM compat

---

.changeset/pretty-dryers-sneeze.md
packages/components/pie-tag/src/tag.scss

- adds cursor pointer to interactive tags

fix(pie-tag): DSW-2524 fix interactive tags don't use the pointer cursor

---

.github/workflows/changeset-snapshot/test-aperture.js
package.json
turbo.json
yarn.lock

Fixes an issue with the following Turborepo config:
- Ensure `generate-component-statuses` is only run when `build` / `dev` commands are run for packages that depend on this task (currently `pie-docs` / `pie-storybook`).
- Fix the following error when running `yarn build:examples`:
```
Run failed: error preparing engine: Invalid turbo.json
- "//#generate:component-statuses". Use "generate:component-statuses" instead
- No "extends" key found
Turbo error: error preparing engine: Invalid turbo.json
- "//#generate:component-statuses". Use "generate:component-statuses" instead
- No "extends" key found
```

fix(pie-monorepo): DSW-000 generate-component-statuses / build:examples turbo config

---

apps/pie-storybook/.storybook/preview-head.html

- Added pre-loading on fonts in the `preview-head.html` file.
- This fixes a [future issue ](https://percy.io/4bc223d1/web/pie-divider/builds/37245666/changed/2029639200?browser=safari&browser_ids=59%2C60%2C63&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&test_case_ids=&viewLayout=overlay&viewMode=new&width=375&widths=375) of fonts not loading in storybook when Percy screenshots are made.

fix(pie-storybook): DSW-2321 updated pre-load in the preview-head.html in storybook

---

.changeset/little-beans-count.md
.github/workflows/changeset-snapshot/test-aperture.js
.github/workflows/install-build.yml
bundlewatch.config.json

---
"pie-monorepo": patch
---
[Fixed] - Bundlewatch base branch diff tracking
**Before** -  bundlewatch was tracking the wrong branch
*After** - Now bundlewatch is correctly trying to track main
This diff should be fixed for future PR's once this is merged.

fix(pie-monorepo): DSW-2507 bundlewatch base branch diff tracking

---

.github/workflows/labeler-get-labels.yml

- Updates the `labeler-get-labels.yml` workflow to use env vars

fix(pie-monorepo): DSW-000 use env var for branch name in workflow

---

.github/dependabot.yml
.vscode/extensions.json

Fixes an issue where the renovate config didn't align with the schema. As part of this PR I have:
- Fixed the underlying issues with the config.
- Added YAML schema validation
- Included  `redhat.vscode-yaml` as a VS Code recommended extension
> [!NOTE]
> Dependabot check is still failing in this PR, as GitHub Actions is reading the config from main

fix(pie-monorepo): DSW-000 Fix dependabot config.

---

.github/workflows/closed.yml

- Updated `closed.yml` to fix closing of test amplify deployments

ci(pie-storybook): DSW-2496 updated closed.yml

---

.github/workflows/amplify-deploy.yml
packages/tools/pie-monorepo-utils/changeset-snapshot/create-and-publish.js
packages/tools/pie-monorepo-utils/changeset-snapshot/test-aperture.js

- Updated `sub-domain-suffix` requirements to `false`, as it's not used by the example app deploys and was causing the workflow to fail.

ci(pie-monorepo): DSW-2496 updated sub-domain-suffix requirements

---

.changeset/chilled-rules-teach.md
packages/components/pie-notification/README.md
packages/components/pie-toast/README.md
packages/components/pie-toast/src/index.ts
packages/components/pie-toast/src/toast.scss

- To truncate text in CSS, we typically need a specified width for the container to determine when truncation should happen. Currently, we use JavaScript in `pie-toast` to calculate the container's width and various action widths to ensure proper text truncation.
- This PR simplifies the solution using a CSS flexbox trick that allows text truncation without knowing the exact container width, as shown in [this CodePen](https://codepen.io/unthinkingly/pen/XMwJLG) (Demo 3b).
- Updates the readme file for toast and notification to point to the docs site (cleanup)

fix(pie-toast): DSW-000 truncate text with css

---

.changeset/clever-trees-sort.md
.changeset/rotten-chefs-divide.md
packages/components/pie-button/src/button.scss
packages/components/pie-button/src/index.ts
packages/components/pie-button/test/visual/pie-button-size.spec.ts

- [Changed] - Styling allowing for text-overflow in buttons
- [-] N/A If it is a `PIE Docs` change, I have reviewed the PR preview

feat(pie-button): DSW-000 styling allowing for text-overflow in buttons

---

package.json
packages/tools/pie-css/turbo.json
packages/tools/pie-icons-react/turbo.json
packages/tools/pie-icons-vue/turbo.json
packages/tools/pie-icons-webc/turbo.json
packages/tools/pie-icons/turbo.json
turbo.json
yarn.lock

Adds `$TURBO_DEFAULT$` to all turbo.json `inputs` to ensure all folders / files relative to the packages package.json are considered when determining whether to miss / hit cache.
I've updated the `turbo` dependency too by a minor version and have run the following to ensure a clean build is executed.
```bash
git clean -fdx
yarn build --force
```
---
- [-] I have reviewed the …

fix(pie-monorepo): DSW-000 add $TURBO_DEFAULT$ to turbo.json inputs

---

.changeset/smart-olives-walk.md
apps/pie-docs/src/componentStatusData.js
packages/components/README.md
packages/components/pie-textarea/package.json

[Changed] - update the textarea component status to beta
Additionally I updated the README of the components with information about how the component status is handled. Please review if this is correct.

chore(pie-textarea): DSW-2653 update component status to beta

---

.changeset/breezy-experts-hear.md
.changeset/ten-chefs-rescue.md
apps/pie-storybook/stories/testing/pie-radio-group.test.stories.ts
apps/pie-storybook/turbo.json
bundlewatch.config.json
packages/components/pie-radio-group/src/index.ts
packages/components/pie-radio-group/test/component/pie-radio-group-new.spec.ts
packages/components/pie-radio/src/index.ts
packages/components/pie-webc-testing/src/helpers/page-object/base-page.ts
packages/components/pie-webc-testing/src/helpers/page-object/storybook-extensions.ts

- Introduces keyboard navigation inside the Radio Group component. This functionality should adhere to the behaviours outlined in [this W3 guide](https://www.w3.org/WAI/ARIA/apg/patterns/radio/). Image attached below showing the relevant section.
- I have opted to mirror the `Shift + Tab` behaviour displayed in Chrome, whereby focusing the radio group when no option is selected will focus the last item.
- RTL support is included. When in RTL, the left arrow key will go forwards and the right array will go backwards.
--- …

feat(pie-radio-group): DSW-2632 add keyboard navigation and focusing

---

.github/workflows/ci.yml
yarn.lock

As we're currently unable to upgrade `@playwright/test`, this PR changes the test jobs to run on the old Github Action runner that doesn't exhibit a playwright dep install error.
- [-] - N/A I have added thorough tests where applicable (unit / component / visual).
- [-] - N/A If changes will affect consumers of the package, I have created a changeset entry.
- [-] - N/A If a changeset file has been created, I have tested these changes in [PIE Aperture](https://github.com/justeattakeaway/pie-aperture/) using the `/test-aperture` command.
---
- [-] - N/A I have reviewed the `PIE Storybook`/`PIE Docs` PR preview.
- [-] - N/A I have reviewed the Aperture changes (if …

fix(pie-monorepo): WCP-000 downgrade GHA runner  to fix playwright dep issue with ubuntu-latest

---

apps/pie-storybook/stories/testing/pie-chip.test.stories.ts
packages/components/pie-chip/playwright-lit.config.ts
packages/components/pie-chip/test/accessibility/pie-chip.spec.ts
packages/components/pie-chip/test/component/pie-chip.spec.ts
packages/components/pie-chip/test/helpers/page-object/selectors.ts
packages/components/pie-chip/turbo.json

- refactor pie-chip component/a11y tests to use @playwright/test
- [-] - NA If changes will affect consumers of the package, I have created a changeset entry.
- [-] - NA If a changeset file has been created, I have tested these changes in [PIE Aperture](https://github.com/justeattakeaway/pie-aperture/) using the `/test-aperture` command.
- [-] - NA I have reviewed visual test updates properly before approving.
---
- [-] - NA I have reviewed the Aperture changes (if added)
- [-] - NA If there are visual test updates, I have reviewed them.
- [-] - NA I have reviewed the Aperture …

test(pie-chip): DSW-2373 refactor pie-chip component/a11y tests to use @playwright/test

---

apps/pie-storybook/stories/testing/pie-notification.test.stories.ts
apps/pie-storybook/utilities/index.ts
packages/components/pie-notification/playwright-lit-visual.config.ts
packages/components/pie-notification/playwright-lit.config.ts
packages/components/pie-notification/test/accessibility/pie-notification.spec.ts
packages/components/pie-notification/test/component/pie-notification.spec.ts
packages/components/pie-notification/test/helpers/page-object/selectors.ts
packages/components/pie-notification/test/visual/pie-notification.spec.ts
packages/components/pie-notification/turbo.json
yarn.lock

- Added Notification test story to Storybook testing folder
- Added turbo.json to stop component building locally
- Added missing `aria` props and controls into Storybook
- Updated `createVariantStory` to support option props.
- Updated `Component`, `Accessibility` and `Visual` tests from `@sand4rt/experimental-ct-web` package to `@playwright/test` as well as corresponding `playwright-lit` configs.
**_Note:_**
There is a minor problem we have found with the labelling for the iconSlot within the variants visual test that we were not able to solve. I have since created a follow up ticket to address this post refactors.
- [-] - NA If changes will affect consumers of the package, I have created a changeset …

refactor(pie-notification): DSW-2380 to use `@playwright/test` & storybook for testing

---

.changeset/wicked-windows-admire.md
apps/pie-storybook/stories/pie-thumbnail.stories.ts
apps/pie-storybook/stories/testing/pie-thumbnail.test.stories.ts
packages/components/pie-thumbnail/src/defs.ts
packages/components/pie-thumbnail/src/index.ts
packages/components/pie-thumbnail/src/thumbnail.scss
packages/components/pie-thumbnail/test/visual/pie-thumbnail.spec.ts

- Added the basic pie-thumbnail functionality - variant, src and alt props
- Added component to storybook
- Added visual tests
-  [x] If a changeset file has been created, I have tested these changes in [PIE Aperture](https://github.com/justeattakeaway/pie-aperture/) using the `/test-aperture` command.
---
| Aperture PR            | [🔗](https://github.com/justeattakeaway/pie-aperture/pull/239) |
| NextJS 14 deployment   | [🔗](https://pr239-aperture-nextjs-app-v14.pie.design/components/thumbnail) |
| …

feat(pie-thumbnail): DSW-2580 add basic thumbnail functionality

---

.changeset/two-boxes-lie.md
packages/components/pie-radio-group/src/index.ts
packages/components/pie-radio-group/test/component/pie-radio-group-new.spec.ts
packages/components/pie-radio/src/index.ts
packages/components/pie-radio/src/radio.scss
packages/components/pie-radio/test/component/pie-radio.spec.ts

- Updates the Radio and Radio Group components to ensure screenreaders correctly announce the index and selection size of inputs in a group. For example "2 of 6".
- Updates Radio to apply an `aria-checked` attribute to itself that reflects the checked state, so that screenreaders will say "selected" or similar when the radio is selected.
- New tests to check the features above
---
- Please visit each Aperture Radio Group page below and, with screen readers enabled, navigate through the radio buttons using your keyboard. The screenreader should correctly identify which position your selected radio button is in the group. …

feat(pie-radio-group): DSW-2634 make screenreaders narrate index and selected

---

.changeset/nasty-kings-hang.md
apps/pie-storybook/stories/pie-radio.stories.ts
packages/components/pie-radio-group/src/radio-group.scss
packages/components/pie-radio/src/radio.scss
packages/components/pie-radio/test/visual/pie-radio.spec.ts

- Ensures the radio always aligns to the first line of multi-line label text
- Uses `pie-button` for form buttons in Storybook
- Adds 8px spacing between the form label and first radio in `pie-radio-group`
- Adds some label spacing in the Story for `pie-radio-group`
---
| Aperture PR            | N/A |
| NextJS 14 deployment   | N/A |
| Nuxt 3 deployment      | N/A |
| Vanilla deployment     | N/A |
- …

cosmetic(pie-radio-group): DSW-2633 minor styling tweaks

---

apps/pie-storybook/stories/pie-link.stories.ts
apps/pie-storybook/stories/testing/pie-link.test.stories.ts
packages/components/pie-link/playwright-lit-visual.config.ts
packages/components/pie-link/playwright-lit.config.ts
packages/components/pie-link/src/index.ts
packages/components/pie-link/test/accessibility/pie-link.spec.ts
packages/components/pie-link/test/component/pie-link.spec.ts
packages/components/pie-link/test/helpers/page-object/selectors.ts
packages/components/pie-link/test/visual/pie-link.spec.ts
packages/components/pie-link/turbo.json
yarn.lock

- Added Link test story to Storybook testing folder
- Added turbo.json to stop component building locally
- Added missing `aria` props and controls into Storybook
- Updated `Component`, `Accessibility` and `Visual` tests from `@sand4rt/experimental-ct-web` package to `@playwright/test` as well as corresponding `playwright-lit` configs.
**_Note:_**
There is a minor problem we have found with the labelling for the iconSlot within the variants visual test that we were not able to solve. I have since created a follow up ticket to address this post refactors.
- [-] - NA If changes will affect consumers of the package, I have created a changeset entry.
- [-] - NA If a changeset file has been created, I have …

refactor(pie-link): DSW-2378 to use `@playwright/test` & storybook for testing

---

apps/pie-storybook/stories/testing/pie-tag.test.stories.ts
packages/components/pie-tag/playwright-lit-visual.config.ts
packages/components/pie-tag/playwright-lit.config.ts
packages/components/pie-tag/test/accessibility/pie-tag.spec.ts
packages/components/pie-tag/test/component/pie-tag.spec.ts
packages/components/pie-tag/test/helpers/page-object/selectors.ts
packages/components/pie-tag/test/visual/pie-tag.spec.ts
packages/components/pie-tag/turbo.json

- Added Tag test story to Storybook testing folder
- Added turbo.json to stop component building locally
- Updated `Component`, `Accessibility` and `Visual` tests from `@sand4rt/experimental-ct-web` package to `@playwright/test` as well as corresponding `playwright-lit` configs.
- [-] - NA If changes will affect consumers of the package, I have created a changeset entry.
- [-] - NA If a changeset file has been created, I have tested these changes in [PIE Aperture](https://github.com/justeattakeaway/pie-aperture/) using the `/test-aperture` command.
---
- [-] N/A - I have reviewed the Aperture changes (if added)
- [-] N/A - I have reviewed the Aperture changes (if …

refactor(pie-tag): DSW-2383 Refactored pie-tag to use @playwright/test

---

.changeset/wet-gorillas-attack.md
apps/pie-storybook/stories/testing/pie-radio-group.test.stories.ts
packages/components/pie-radio-group/src/index.ts
packages/components/pie-radio-group/test/component/pie-radio-group-new.spec.ts
packages/tools/pie-monorepo-utils/changeset-snapshot/test-aperture.js

- Ensures the `name` prop provided to the Radio Group component is correctly passed down to each radio button in it's slot
- Minor update to the `test-aperture` command to more cleary surface errors in the Github comments
---
| Aperture PR            | [🔗](https://github.com/justeattakeaway/pie-aperture/pull/241) |
| NextJS 14 deployment   | [🔗](https://pr241-aperture-nextjs-app-v14.pie.design/components/radio-group) |
| Nuxt 3 deployment      | …

feat(pie-radio-group): DSW-2636 apply name prop to child radio buttons and update test-aperture

---

apps/pie-storybook/stories/testing/pie-button.test.stories.ts
apps/pie-storybook/utilities/index.ts
configs/pie-components-config/playwright-native-config.js
packages/components/pie-assistive-text/test/component/pie-assistive-text.spec.ts
packages/components/pie-button/playwright-lit-visual.config.ts
packages/components/pie-button/playwright-lit.config.ts
packages/components/pie-button/test/accessibility/pie-button.spec.ts
packages/components/pie-button/test/component/pie-button.spec.ts
packages/components/pie-button/test/helpers/page-object/pie-button-anchor.page.ts
packages/components/pie-button/test/helpers/page-object/pie-button-default.page.ts
packages/components/pie-button/test/helpers/page-object/pie-button-form-attributes.page.ts
packages/components/pie-button/test/helpers/page-object/pie-button-form-integration-selectors.ts
packages/components/pie-button/test/helpers/page-object/pie-button-form-integration.page.ts
packages/components/pie-button/test/helpers/page-object/pie-button-form-submission.page.ts
packages/components/pie-button/test/helpers/page-object/pie-button.component.ts
packages/components/pie-button/test/visual/pie-button-anchor.spec.ts
packages/components/pie-button/test/visual/pie-button-size.spec.ts
packages/components/pie-button/test/visual/pie-button.spec.ts
packages/components/pie-button/turbo.json

- Refactors pie-button to use page object / `@playwright/test`.
- Adds functionality to `createVariantStory` to allow `multiColumn: bool` to be passed as part of the `StoryOptions` object to make better use of screen width for visual tests where many variations are rendered.
---
- [-] N/A I have reviewed the Aperture changes …

refactor(pie-button): DSW-2369 to use @playwright/test & storybook for testing

---

.changeset/sixty-schools-collect.md
packages/components/pie-thumbnail/src/index.ts

- Fixes the flickering issue where the thumbnail placeholder behavior doesn't render as expected in Nuxt and Next.js when the page reloads
- The issue is that the `onerror` event isn't triggered in SSR (see [facebook/react#15446](https://github.com/facebook/react/issues/15446)) so we need to ensure that the component is hydrated with the placeholder props if the image fails on the server.
---
| Aperture PR            | [🔗](https://github.com/justeattakeaway/pie-aperture/pull/239) |
| NextJS 14 …

fix(pie-thumbnail): DSW-2585 Ensure the placeholder logic is working properly with SSR

---

apps/pie-storybook/stories/testing/pie-toast.test.stories.ts
apps/pie-storybook/utilities/index.ts
configs/pie-components-config/playwright-native-config.js
packages/components/pie-toast/playwright-lit-visual.config.ts
packages/components/pie-toast/playwright-lit.config.ts
packages/components/pie-toast/src/defs.ts
packages/components/pie-toast/test/accessibility/pie-toast.spec.ts
packages/components/pie-toast/test/component/pie-toast.spec.ts
packages/components/pie-toast/test/helpers/page-object/selectors.ts
packages/components/pie-toast/test/visual/pie-toast.spec.ts
packages/components/pie-toast/turbo.json
yarn.lock

- Added Toast test story to Storybook testing folder
- Added turbo.json to stop component building locally
- Updated `Component`, `Accessibility` and `Visual` tests from `@sand4rt/experimental-ct-web` package to `@playwright/test` as well as corresponding `playwright-lit` configs.
- [-] - NA If changes will affect consumers of the package, I have created a changeset entry.
- [-] - NA If a changeset file has been created, I have tested these changes in [PIE Aperture](https://github.com/justeattakeaway/pie-aperture/) using the `/test-aperture` command.
---
- [-] N/A - I have reviewed the Aperture changes (if added)
- [-] N/A - I have reviewed the Aperture changes …

refactor(pie-toast): DSW-2386 refactored toast to use `@playwright/test`

---

.github/workflows/ci.yml
apps/pie-storybook/stories/testing/icons.test.stories.ts
packages/tools/pie-icons-webc/playwright-lit-visual.config.ts
packages/tools/pie-icons-webc/playwright-lit.config.ts
packages/tools/pie-icons-webc/test/component/icon-webc.spec.js
packages/tools/pie-icons-webc/test/helpers/page-object/selectors.ts
packages/tools/pie-icons-webc/test/visual/pie-icons-webc.spec.ts
packages/tools/pie-icons-webc/turbo.json
yarn.lock

- Refactors pie-icons-webc to use `@playwright/test`
Percy build - https://percy.io/4bc223d1/web/pie-icons-webc/builds/38438247/
---
- [] If there are visual test updates, I have reviewed them.

refactor(pie-icons-webc): DSW-2755 tests to use `@playwright/test`

---

.changeset/large-coins-design.md
packages/components/pie-radio/src/radio.scss

Please click the `Preview` tab and select a different PR template if your change isn't for an                                            existing web component.
[PIE Docs Template](?expand=1&template=docs_template.md)
[New Web Component Template](?expand=1&template=new_component_template.md)
═══════════════════════════════════════════════════════════
---
| Aperture PR            | [N/A](#) |
| NextJS 14 deployment   | N/A](#) |
| Nuxt 3 deployment      | N/A](#) |
| Vanilla deployment     | N/A](#) | …

fix(pie-radio): DSW-000 ensure focus ring only appears on keyboard focus

---

.changeset/shiny-coats-exercise.md
packages/components/pie-modal/src/index.ts

**Stats:**
_showModal() = 2.25ms / self time 0.25
disableBodyScoll = 87μs
Recalculate Styles = 1.45ms_
**Stats:**
_showModal() = 0.58ms / self time 0.25ms
disableBodyScoll = defers to 3rd task
_setupEscKeyListener = defers to next task
Recalculate Styles = 11ms
Recalculate Styles  (second batch)= 81 μs_
---
- [-] I …

performance(pie-modal): PEW-100 improves performance by deferring tasks

---

apps/pie-storybook/stories/testing/pie-radio.test.stories.ts
packages/components/pie-radio/playwright-lit-visual.config.ts
packages/components/pie-radio/playwright-lit.config.ts
packages/components/pie-radio/src/index.ts
packages/components/pie-radio/test/accessibility/pie-radio.spec.ts
packages/components/pie-radio/test/component/pie-radio.spec.ts
packages/components/pie-radio/test/helpers/page-object/selectors.ts
packages/components/pie-radio/test/visual/pie-radio.spec.ts
packages/components/pie-radio/turbo.json

- Refactors pie-radio to use `@playwright/test`
---

refactor(pie-radio): DSW-2770 tests to use `@playwright/test`

---

apps/pie-storybook/stories/testing/pie-radio.test.stories.ts
packages/tools/pie-icons-webc/test/visual/pie-icons-webc.spec.ts
turbo.json

- Fixes and issue where turbo would trigger a cache hit for `pie-storybook`, when a cache miss should have occured.
- Fixes existing linting issues.
---
- [-] NA I have verified that all acceptance criteria for this ticket have been completed.
- [-] NA I have reviewed the Aperture changes (if added)
- [-] NA I have verified that all acceptance criteria for this ticket have been completed.
- [-] NA I have reviewed the Aperture changes (if added)
- [-] If there are visual test …

format(pie-monorepo): DSW-000 fix linting config & linting issues

---

apps/pie-storybook/stories/testing/pie-webc-core.test.stories.ts
packages/components/pie-webc-core/playwright-lit.config.ts
packages/components/pie-webc-core/src/test/functions/dispatchCustomElement/MockComponent.ts
packages/components/pie-webc-core/src/test/functions/dispatchCustomElement/constants.ts
packages/components/pie-webc-core/src/test/functions/dispatchCustomElement/dispatchCustomEvent.browser.spec.ts
packages/components/pie-webc-core/src/test/mixins/formControlMixin/formControlMixin.browser.spec.ts
packages/components/pie-webc-core/turbo.json

- Refactors webc-core tests to use `@playwright/test`
---

refactor(pie-webc-core): DSW-2777 tests to use `@playwright/test`

---

.github/workflows/ci.yml

- Reverts https://github.com/justeattakeaway/pie/pull/2134
Now that we've upgraded `@playwright/test`, we should be able to use the latest GHA runner images.
---

ci(pie-monorepo): DSW-2674 update actions runners

---

.changeset/warm-snakes-press.md
packages/components/pie-text-input/src/index.ts

fix(pie-text-input): WCP-000 missing validPropertyValues decorator for size prop

---

.changeset/swift-buckets-press.md
packages/components/pie-cookie-banner/README.md

Adds a section to the readme on how to use the component with our CDN

docs(pie-cookie-banner): DSW-2679 add a CDN usage block to readme

---

.changeset/silly-shoes-rush.md
apps/pie-docs/src/components/link/code/props.json
apps/pie-docs/src/components/link/code/slots.json
apps/pie-storybook/stories/pie-link.stories.ts

- Update the pie-link props table to mention the iconPlacement won't take effect unless `isStandAlone` is set to true
- Make it clear that the icon size cannot be overridden
- Add example to Storybook

docs(pie-storybook): DSW-2900 update pie-link icon slot documentation

---

.changeset/lucky-spiders-kneel.md
apps/pie-storybook/stories/icons.stories.ts

When users visit the webc storybook and view the Icons gallery story, currently they must inspect elements in order to find the icons tag name. We can improve this by displaying the tag name in the story beneath each icon. This also means users can use the page search feature to find an icon.
https://pr2328-storybook.pie.design/?path=/story/icons--all-icons

docs(pie-storybook): DSW-2984 icon names in story

---

.changeset/silly-birds-cheer.md
packages/components/pie-select/src/select.scss

Small changes based on design review to:
- reduce right padding on select to 52px (not a token so it's hard coded)
- use the jet font via inheritance
- truncate longer select options 
---
| Aperture PR            | [N/A](#) |
| NextJS 14 deployment   | [N/A](#) |
| Nuxt 3 deployment      | [N/A](#) |
| Vanilla deployment     | [N/A](#) |

feat(pie-select): DSW-2982 design review tasks

---

.changeset/happy-eels-cough.md
packages/components/pie-checkbox/src/defs-react.ts
packages/components/pie-radio-group/src/defs-react.ts
packages/components/pie-radio/src/defs-react.ts
packages/components/pie-select/src/defs-react.ts
packages/components/pie-switch/src/defs-react.ts
packages/components/pie-text-input/src/defs-react.ts
packages/components/pie-textarea/src/defs-react.ts

Fixes the following TypeScript error when attaching any event to our React wrapper form elements.
```
Type '(event: InputEvent) => void' is not assignable to type '((event: InputEvent) => void) & FormEventHandler<HTMLInputElement>'.
```
- This happens because our React wrapper extends our component [types](https://github.com/justeattakeaway/pie/blob/main/packages/components/pie-text-input/src/defs-react.ts#L3) with `React.HTMLAttributes<HTMLInputElement>`, which automatically includes React-specific event handlers types like `onInput` and `onChange`.
- As a result, our component types end up with a union of event types we declare from Lit (InputEvent / CustomEvent) and React (SyntheticEvent), leading to a type conflict.
- The fix omits the React event types from the wrapper, as we only …

fix(pie-monorepo): DSW-2856 typescript compatibility issues with form element events in React

---

.changeset/tricky-dolls-mate.md
apps/pie-docs/src/components/toast/toast-provider/code.md
apps/pie-docs/src/components/toast/toast-provider/css-properties.json
apps/pie-storybook/stories/pie-toast-provider.stories.ts
apps/pie-storybook/stories/testing/pie-toast-provider.test.stories.ts
packages/components/pie-toast-provider/src/defs-react.ts
packages/components/pie-toast-provider/src/defs.ts
packages/components/pie-toast-provider/src/index.ts
packages/components/pie-toast-provider/src/toast-provider.scss
packages/components/pie-toast-provider/test/component/pie-toast-provider.spec.ts
packages/components/pie-toast-provider/test/visual/pie-toast-provider.spec.ts

- Refactors the `zIndex` prop to be a css property

refactor(pie-toast-provider): DSW-2949 z-index css property

---

.changeset/young-mails-cross.md
packages/components/pie-switch/src/switch.scss

- Fixes pie-switch check icon vertical alignment
https://github.com/user-attachments/assets/0ebcc942-3257-4695-968b-9539e15d3f08
---

fix(pie-switch): DSW-2819 fix check icon vertical alignment

---

.changeset/great-lemons-pull.md
.github/workflows/amplify-deploy.yml
.github/workflows/changeset-release.yml
.github/workflows/ci.yml
apps/pie-docs/README.md
apps/pie-docs/package.json
packages/tools/pie-icons/bin/create-changeset.mjs
packages/tools/pie-icons/bin/update-icons.mjs
packages/tools/pie-monorepo-utils/__tests__/changeset-snapshot/create-and-publish.spec.js
packages/tools/pie-monorepo-utils/changeset-snapshot/utils.js
turbo.json
yarn.lock

[Fixed] - Security patch to add scopes to private unpublished pkgs
---

fix(pie-monorepo): DSW-3025 security patch to add scopes to private unpublished pkgs

---

.changeset/gold-singers-cough.md
apps/pie-storybook/.storybook/preview.ts
apps/pie-storybook/stories/introduction/events.mdx

- Adds an 'Events' page to Storybook explaining how consumers can listen to component events

docs(pie-storybook): DSW-2999 component events page

---

.changeset/plenty-taxis-kneel.md
apps/pie-storybook/.storybook/preview.ts
apps/pie-storybook/stories/integration-guides/nextjs-14.mdx
apps/pie-storybook/stories/introduction/getting-started.mdx

- Adds a next.js 14 integration guide to storybook
- Updates the getting started guide to mention `@justeattakeaway/pie-icons-webc`

docs(pie-storybook): DSW-3061 add next.js 14 integration guide to sb

---

.github/actions/setup-repo/action.yml
.github/dependabot.yml

The version of this action we're using it currently reliant on a GitHub Service that was deprecated as of last week, causing timeout issues when trying to restore Node cache. - https://github.com/orgs/community/discussions/160793
This is visible in the logs for any `Setup Node` step in our CI:
Currently, this timeout cause this step to take ~6 minutes, resulting in slower CI time.
As you can see, this change no longer results in the error and only takes ~1min 30s
This change will also bring a `main` build back to a reasonable total duration. All the ~1hr times are since the deprecation

ci(pie-monorepo): DSW-000 upgrade `actions@setup-node@v4.4.0`

---

.changeset/good-crabs-confess.md
apps/pie-storybook/stories/contribution/overview.mdx

- add small guide on setting up new percy projects when generating components
https://pr2450-storybook.pie.design/?path=/docs/contribution-overview--docs#4-scaffold-a-new-component

docs(pie-docs): DSW-3100 add percy setup guide

---

.changeset/pink-elephants-dance.md
.changeset/violet-pumas-perform.md
apps/pie-storybook/stories/testing/pie-radio-group.test.stories.ts
packages/components/pie-radio-group/src/index.ts
packages/components/pie-radio-group/test/component/pie-radio-group-new.spec.ts

[Fixed] keyboard focus handling when one or more radio buttons are disabled
[Added] - new test stories for `PieRadioGroup` component
---
[-] If there are visual test updates, I have reviewed them.

fix(pie-radio-group): DSW-3076 fix keyboard focus handling when radio is disabled

---

.gitignore

Turborepo can be quite inconsistent at times when building our components, resulting in cache misses without any file modifications in the repo.
While i'm not entirely sure what the issue is, I have noticed that when building any web components, a `vite.config.js.timestamp.*` file can get generated, and then immediately deleted once the component has been built.
This is problematic, as if this file gets added to source control, it _could_ cause a chain-reaction with Turbo and invalidate a number of component caches.
By adding this file to `.gitignore`, we're telling Turborepo to ignore this file and not consider it when generating any hashes that are used for determining cache state.
---
[How do I test my …

chore(pie-monorepo): DSW-3205 add vite.config.timestamp files to .gitignore

---

package.json
yarn.lock

- Added `@vitest/coverage-v8` dependency to fix `pie-icons` publish at changesets CI step.
---
- [-] I …

ci(pie-icons): DSW-000 added missing deps for pie-icon

---

.github/workflows/ci.yml

Fixes typo that was causing Percy tests to fail in `main`.

ci(pie-monorepo): DSW-3344 fix typo that causes Percy errors in main

---

.changeset/gorgeous-lies-mate.md
.github/CODEOWNERS

Tighten up the CODEOWNERS file so only the senior engineer group will be a required approver. This, in combination with a change in the repo settings means that going forward we will require *1* reviewer (one of the codeowners) to merge PRs. However we advise 2 reviews in most cases.

chore(pie-monorepo): DSW-3390 tighten codeowners rules
